apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.ts
* When searching for candidates in the add member dialog, there was a
wrong parameter passed to the method. The attribute names were invalid.
=> AdminGui - bug fix of member addition

apps/admin-gui/src/app/app.module.ts, apps/admin-gui/src/app/core/components/auth-callback/auth-callback.component.ts, apps/admin-gui/src/app/core/services/api/api.service.ts, apps/admin-gui/src/app/core/services/common/app-config.service.ts, apps/admin-gui/src/app/core/services/common/auth.service.ts, apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.html, apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.ts, apps/admin-gui/src/assets/config/defaultConfig.json, apps/admin-gui/src/assets/config/instanceConfig.json, apps/admin-gui/src/environments/environment.cesnet-dev.ts, apps/admin-gui/src/environments/environment.ts, package-lock.json, package.json
* add runtime configuration
* finish footer(data are now taken from config file)
resolves #9
=> App configuration

apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts, apps/admin-gui/src/assets/i18n/en.json
* adding validation for input forms so now are required
* when dialog is canceled the data in table are not reloaded
resolves #14
=> Create group - add validation

apps/admin-gui/src/app/shared/components/resources-tags-list/resources-tags-list.component.html
* changing appearance of edit/save button in tag table
resolves #11
=> Edit tag button

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.html, apps/admin-gui/src/app/shared/components/groups-list/groups-list.component.html, apps/admin-gui/src/app/shared/components/groups-list/groups-list.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
* add to group list options for disable members group
resolves #8
=> Group list/tree - disableMembersGroup

apps/admin-gui/src/app/app.component.html, apps/admin-gui/src/app/app.component.scss, apps/admin-gui/src/app/app.component.ts, apps/admin-gui/src/styles.scss
* I have added a warning that appears on production instances. When the
admin gui is officially released, it can be removed.
=> AdminGui - BETA warning

apps/admin-gui/src/app/shared/components/report-issue-dialog/report-issue-dialog.component.html, apps/admin-gui/src/app/shared/components/report-issue-dialog/report-issue-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/report-issue-dialog/report-issue-dialog.component.ts, apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.html, apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.scss, apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/assets/i18n/en.json
* implement report issue dialog
resolves #22
=> Implement bug reporting for footer

apps/admin-gui/src/app/core/services/common/app-config.service.ts, apps/admin-gui/src/app/shared/components/notificator/notificator.component.html, apps/admin-gui/src/app/shared/components/notificator/notificator.component.scss, apps/admin-gui/src/app/shared/components/notificator/notificator.component.ts
* Also, added no chache headers for the calls getting the app
configurations.
=> AdminGui - notification positon fix with BETA alert

apps/admin-gui/src/app/shared/components/notificator/notificator.component.ts
* It was caused by notificator having the top css property set.
=> Fixed bug with unresponsiveness of content on mobile view

apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.ts, apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts
* Add the users page to cache
resolves #12
=> Add the users page to cache

apps/admin-gui/src/app/shared/components/dialogs/create-vo-dialog/create-vo-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-vo-dialog/create-vo-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/create-vo-dialog/create-vo-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.html, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/vo.service.ts
* Added dialog for creating new Vo, shown only if user is at least VoAdmin.
* Resolves #29 .
=> Create vo dialog component

apps/admin-gui/src/app/app.component.html, apps/admin-gui/src/app/app.component.ts, apps/admin-gui/src/app/core/services/api/api.service.ts, apps/admin-gui/src/app/core/services/common/app-config.service.ts, apps/admin-gui/src/app/core/services/common/auth-resolver.service.ts, apps/admin-gui/src/app/core/services/common/auth.service.ts, apps/admin-gui/src/app/core/services/common/store.service.spec.ts, apps/admin-gui/src/app/core/services/common/store.service.ts, apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.ts
* load principal in APP_INITIALIZE after authentication
resolves #36
=> load principal in APP_INITIALIZE after authentication

apps/admin-gui/src/app/core/services/common/app-config.service.ts
* There was missing a resolve function that casued in production the app
not being loaded at all.
=> AdminGui - fix loading in prod

apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.scss, apps/admin-gui/src/styles.scss
* Changed the color of links in side menu to match the overall dark
style of the side menu.
=> AdminGui - menu links colors change

apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.html, apps/admin-gui/src/assets/i18n/en.json, apps/admin-gui/src/styles.scss
* Created basic template for nav menu whick now contains link to user
profile and a button for logout which is not implemented yet.
=> AdminGui - created nav menu

apps/admin-gui/src/app/shared/components/dialogs/remove-vo-dialog/remove-vo-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-vo-dialog/remove-vo-dialog.component.scss, apps/admin-gui/src/app/shared/components/dialogs/remove-vo-dialog/remove-vo-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-vo-dialog/remove-vo-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/components/vo-select-table/vo-select-table.component.html, apps/admin-gui/src/app/vos/components/vo-select-table/vo-select-table.component.ts, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.html, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/vo.service.ts
* Added dialog component for removing one Vo at the time
* Resolves #38
=> Remove Vo dialog

apps/admin-gui/src/app/core/services/common/side-menu.service.ts, apps/admin-gui/src/app/main-menu-page/main-menu-page.component.html, apps/admin-gui/src/app/shared/components/user-profile/user-profile.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-root-item/side-menu-root-item.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu-root-item/side-menu-root-item.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu.component.ts
* Added new sidemenu item for user profile.
* Resolves: #52
=> User profile sidemenu

apps/admin-gui/src/app/app.component.ts, apps/admin-gui/src/app/app.module.ts, apps/admin-gui/src/app/core/services/common/app-config.service.ts, apps/admin-gui/src/app/core/services/common/auth.service.ts, apps/admin-gui/src/app/core/services/common/notificator.service.ts, apps/admin-gui/src/app/core/services/common/store.service.ts, apps/admin-gui/src/app/shared/shared.module.ts
fixing this issue: 
I think bug came with change in configs, when translation service couldn't get language choice soon enough to get results for notificator. 
This is just quick fix, maybe @xkureck or @Vojtech-Sassmann will find other way
=> translation fix for notificator service

apps/admin-gui/src/app/app-routing.module.ts
* After routing, the page is automatically scrolled to the top
* Resolves #65
=> Scroll to top of a page after routing

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.html, apps/admin-gui/src/app/shared/components/groups-list/groups-list.component.html, apps/admin-gui/src/app/shared/components/groups-list/groups-list.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html, apps/admin-gui/src/app/shared/components/user-detail-page/user-groups/user-groups.component.html, apps/admin-gui/src/app/shared/components/user-detail-page/user-groups/user-groups.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/members.service.ts, libs/perun/services/src/lib/users.service.ts
* implement user detail for groups
resolves #40
=> User detail - groups

apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-members-dialog/remove-members-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-members-dialog/remove-members-dialog.component.ts, apps/admin-gui/src/app/shared/pipes/member-candidate-email.pipe.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/group.service.ts, libs/perun/services/src/lib/members.service.ts, libs/perun/services/src/lib/vo.service.ts
* Implemented functionality for adding and removing members from group.
=> AdminGUI - add and remove members from group

package.json
* script: "ng serve admin-gui --public-host=http://localhost:4200 --disable-host-check"
* when someone want to run the Admin Gui, he/she can just run the script
=> added script to package.json 'start-dev-admin-gui'

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.ts, apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.ts
* fix of editing/creating notification
=> Fix of the add-edit notification dialog

apps/admin-gui/src/app/shared/components/attributes-list/attributes-list.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.scss
resolves #13 
create attribute dialog can be scrolled now
one thing i wasn't sure about is whether i should anchor title with buttons or not (now they are not anchored and will hide when content is scrolled down)
=> added scrolling for create attribute dialog

apps/admin-gui/src/app/shared/components/dialogs/change-member-status-dialog/change-member-status-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/change-member-status-dialog/change-member-status-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/change-member-status-dialog/change-member-status-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/components/members-list/members-list.component.html, apps/admin-gui/src/app/vos/components/members-list/members-list.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/members.service.ts
* add button to invalid icons, so users with 'INVALID' status can be manualy set to 'VALID'
resolves #82
=> Manual validation of invalid members

apps/admin-gui/src/app/shared/components/dialogs/show-notification-history-dialog/show-notification-history-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/show-notification-history-dialog/show-notification-history-dialog.component.scss
=> Between recent notifications there is not any margin

apps/admin-gui/src/app/facilities/facilities-routing.module.ts, apps/admin-gui/src/app/facilities/facilities.module.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.spec.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-group-from-resource-dialog/remove-group-from-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-group-from-resource-dialog/remove-group-from-resource-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-group-from-resource-dialog/remove-group-from-resource-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/resources.service.ts
* add page for resource's assigned groups
* add dialog for removing groups from resources
* add dialog for assign group to resource
- TO DO - add functionality for checkbox in dialog for assign group
=> Resource groups

apps/admin-gui/src/app/core/services/common/notification-storage.service.ts, apps/admin-gui/src/app/shared/components/notification/notification.component.html, apps/admin-gui/src/app/shared/components/notification/notification.component.ts, apps/admin-gui/src/app/shared/components/notificator/notificator.component.html, apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.html, apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.ts, apps/admin-gui/src/app/shared/shared.module.ts
* Added badge to display how many new notifications are there
* New notifications counter decreases also when user views notification detail right after it was created
* Resolves #89
=> Add badge to the notifications bell

apps/admin-gui/src/app/shared/components/dialogs/add-ext-source-dialog/add-ext-source-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-ext-source-dialog/add-ext-source-dialog.component.scss, apps/admin-gui/src/app/shared/components/dialogs/add-ext-source-dialog/add-ext-source-dialog.component.ts, apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.html, apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.ts, apps/admin-gui/src/app/shared/pipes/ext-source-type.pipe.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-extsources/vo-settings-extsources.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-extsources/vo-settings-extsources.component.ts, apps/admin-gui/src/app/vos/vos.module.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/vo.service.ts
resolves #81 
* external sources list
* add external sources
* remove external sources
=> VO: SETTINGS: External sources

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-resource-dialog/remove-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-resource-dialog/remove-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/resources-list/resources-list.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-preview/vo-resources-preview.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-preview/vo-resources-preview.component.ts, apps/admin-gui/src/assets/i18n/en.json
* add possibility to remove multiple resources from Vo, remove resource button in Vo now works
* previously you could remove only one resource from facility, now you can remove multiple
=> Remove resource

angular.json, apps/admin-gui/src/app/admin/pages/admin-page/admin-overview/admin-overview.component.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-visualizer/visualizer-overview/visualizer-overview.component.ts, apps/admin-gui/src/app/core/services/api/custom-icon.service.ts, apps/admin-gui/src/app/core/services/common/app-config.service.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-overview/resource-settings-overview.component.ts, apps/admin-gui/src/app/main-menu-page/main-menu-page.component.html, apps/admin-gui/src/app/main-menu-page/main-menu-page.component.scss, apps/admin-gui/src/app/shared/components/menu-buttons-field/menu-buttons-field.component.html, apps/admin-gui/src/app/shared/components/menu-buttons-field/menu-buttons-field.component.scss, apps/admin-gui/src/app/shared/components/user-detail-page/user-overview/user-overview.component.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts, apps/admin-gui/src/app/shared/models/MenuItem.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu-root-item/side-menu-root-item.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-overview/vo-resources-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-overview/vo-settings-overview.component.ts, apps/admin-gui/src/assets/config/defaultConfig.json, apps/admin-gui/src/styles.scss, package-lock.json, package.json
* Added option to change the color of all entities in the configuration
file.
=> Custom entity colors

apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.html, apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/models/src/lib/Candidate.ts, libs/perun/services/src/lib/registrar.service.ts, libs/perun/utils/src/lib/perun-utils.ts
* invitation to group implemented
* adding member to vo now also support adding people from external sources
* resolves #75
=> Invite members to group/vo

apps/admin-gui/src/app/shared/components/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html, apps/admin-gui/src/app/shared/components/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.scss, apps/admin-gui/src/app/shared/components/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.ts
* Added option to move list values of an attribute in settings
resolves #90
=> Attributes chip list make movable

apps/admin-gui/src/app/shared/components/dialogs/create-vo-dialog/create-vo-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-vo-dialog/create-vo-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json
* There was an validation issue where Vo's fullname could consist of whitespaces only
=> Bugfix: Newly created Vos could have empty names

apps/consolidator/src/app/components/identities/identities.component.ts
* The new openAPI generated new model for attribute with object as a
type of value property.
=> Fixed bug with attribute conversion value

apps/admin-gui/src/app/admin/pages/admin-page/admin-visualizer/user-destination-relationship/user-destination-graph/user-destination-graph.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-groups/user-groups.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-managers/group-settings-managers.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts, libs/perun/services/src/lib/facility.service.ts, libs/perun/services/src/lib/group.service.ts, libs/perun/services/src/lib/users.service.ts
* Old methods from GroupService that already have an OpenAPI equivalent were replaced, other remain unchanged
* Resolves #108
=> OpenAPI - group service

apps/admin-gui/src/app/admin/admin-routing.module.ts, apps/admin-gui/src/app/admin/admin.module.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-ext-sources/admin-ext-sources.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-ext-sources/admin-ext-sources.component.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-overview/admin-overview.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-ext-source-dialog/add-ext-source-dialog.component.ts, apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.html, apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-extsources/vo-settings-extsources.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/index.ts, libs/perun/services/src/lib/ext-source.service.ts, libs/perun/services/src/lib/vo.service.ts
resolves #101 
* show all external sources
* load external sources
=> ADMIN: EXTERNAL SOURCES

apps/admin-gui/src/app/core/services/common/notification-storage.service.ts, apps/admin-gui/src/app/core/services/common/notificator.service.ts, apps/admin-gui/src/app/shared/components/dialogs/show-notification-history-dialog/show-notification-history-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/show-notification-history-dialog/show-notification-history-dialog.component.ts, apps/admin-gui/src/app/shared/components/notification/notification.component.html, apps/admin-gui/src/app/shared/components/notification/notification.component.ts, apps/admin-gui/src/app/shared/components/notificator/notificator.component.html, apps/admin-gui/src/app/shared/components/notificator/notificator.component.ts, apps/admin-gui/src/app/shared/models/NotificationData.ts, apps/admin-gui/src/assets/i18n/en.json
* Added button to clear stored notifications.
* Stored notifications now also have timestamp.
* After clicking on newly created notification, it disappears and reduces counter of new notifications.
* Resolves #119
=> Notifications improvement

apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.ts
=> ADMIN: ATTRIBUTES: bug fix, entityless attributes paginator

apps/admin-gui/src/app/core/services/common/notification-storage.service.ts
* Notifications are now displayed in the correct order
* Resolves #129
=> Notifications order

apps/admin-gui/src/app/admin/pages/admin-page/admin-visualizer/user-destination-relationship/user-destination-relationship.component.html
* fix id that was part of the input but it shouldn't be
=> user-destination-relationship

apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts
* I have removed some spaces that were not needed and caused
distraction.
=> Redundant spaces were removed

apps/admin-gui/src/app/admin/admin.module.ts, apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/shared/shared.module.ts, package-lock.json, package.json
* Now, the routing modules are NOT preloaded. This should speed up the
loading of the application.
* Some libraries were moved from the shared module to the admin module,
because they were used only there.
=> Added webpack-size-analyzer and reimplemented routing modules

apps/admin-gui/src/assets/i18n/en.json
* I removed dots from buttons labebels.
=> Remove dots from button labels

apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html, libs/perun/openapi/src/lib/api/registrarManager.service.ts
* Updated registrarManager with a fixed version of openApi.
* Resolves #171
=> Fixed bug appearing during work with applications

apps/admin-gui/src/app/admin/admin-routing.module.ts, apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html, apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-roles/user-roles.component.html, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-roles/user-roles.component.scss, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-roles/user-roles.component.spec.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-roles/user-roles.component.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts, apps/admin-gui/src/app/shared/components/user-profile/user-profile.component.html, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/assets/i18n/en.json
* User roles component for displaying roles and their corresponding ids was implemented
* Resolves #174
=> User roles works

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-attributes/facility-settings-attributes.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-attributes/resource-settings-attributes.component.ts, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-dialog/edit-attribute-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-dialog/edit-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-attributes/user-settings-attributes.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-attributes/group-settings-attributes.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-attributes/member-settings-attributes.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-attributes/vo-settings-attributes.component.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #117 
Used in facility, resource, group, member, vo and user attributes pages.
=> Confirmation dialog for editing attributes value

apps/admin-gui/src/app/facilities/facilities-routing.module.ts, apps/admin-gui/src/app/facilities/facilities.module.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-managers/facility-settings-managers.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-managers/facility-settings-managers.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/assets/i18n/en.json
* added facility managers page
resolves #197
=> Facility managers page

apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list-delete-dialog/attribute-value-list-delete-dialog.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list-delete-dialog/attribute-value-list-delete-dialog.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list-edit-dialog/attribute-value-list-edit-dialog.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list-edit-dialog/attribute-value-list-edit-dialog.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.scss, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.ts, libs/perun/components/src/lib/perun-components.module.ts
* added handle for moving to attribute list component
* added edit button and edit dialog for editing the value
* added delete dialog to delete action
resolves #165
=> Attribute list value component

apps/admin-gui/src/app/main-menu-page/main-menu-page.component.scss, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-tags/vo-resources-tags.component.html, libs/perun/components/src/lib/menu-buttons-field/menu-buttons-field.component.scss
* Fixed localization text in a filter.
* Adjusted sizes of menu buttons.
=> Various fixes

libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-boolean/attribute-value-boolean.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.ts, libs/perun/pipes/src/index.ts, libs/perun/pipes/src/lib/is-virtual-attribute.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts, package-lock.json
* Virtual attributes are now disabled for edition and removal
* Value fields are now more visible
* Resolves #120
=> Attributes improvement

libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-boolean/attribute-value-boolean.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-boolean/attribute-value-boolean.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value.component.ts
* Added option to display whole attributes list in read-only mode (this will be used in user-profile)
=> Attributes list change

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-attributes/facility-settings-attributes.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-attributes/resource-settings-attributes.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.html, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-attributes/user-settings-attributes.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-attributes/group-settings-attributes.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-attributes/member-settings-attributes.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-attributes/vo-settings-attributes.component.html, apps/admin-gui/src/assets/i18n/en.json, apps/user-profile/src/app/pages/privacy-page/privacy-page.component.html, apps/user-profile/src/app/pages/privacy-page/privacy-page.component.ts, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-boolean/attribute-value-boolean.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
* Attributes list can now be correctly set as readonly
* Translations were moved to SHARED_LIB part
* Attributes list now supports hiding columns
* Newly added functionalities were integrated to user-profile
=> Attributes list improvement

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-relation-dialog/create-relation-dialog.component.html, apps/admin-gui/src/app/shared/components/user-detail-page/user-groups/user-groups.component.html, apps/user-profile/src/app/pages/groups-page/groups-page.component.html, apps/user-profile/src/app/pages/services-page/services-page.component.html, apps/user-profile/src/app/pages/vos-page/vos-page.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.scss, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/components/src/lib/resources-list/resources-list.component.html, libs/perun/components/src/lib/resources-list/resources-list.component.scss, libs/perun/components/src/lib/resources-list/resources-list.component.ts, libs/perun/components/src/lib/vo-select-table/vo-select-table.component.html, libs/perun/components/src/lib/vo-select-table/vo-select-table.component.scss, libs/perun/components/src/lib/vo-select-table/vo-select-table.component.ts
* Disable routing input parameter has been added for resources-list, vo-select-table and groups-list
* InDialog option in groups-list was replaced by disableRouting option
* Changes were also integrated to components using those features
=> Disable routing feature in lists

apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-dialog/delete-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-dialog/edit-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-resource-attributes/member-settings-resource-attributes.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-resource-attributes/member-settings-resource-attributes.component.spec.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-resource-attributes/member-settings-resource-attributes.component.ts, apps/admin-gui/src/app/vos/vos-routing.module.ts, apps/admin-gui/src/app/vos/vos.module.ts, apps/admin-gui/src/assets/i18n/en.json
* Added page for viewing, adding, editing and removing member-resource attributes
* This pull request is part of the solution to issue #212
=> Page for viewing member-resource attributes

libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-integer/attribute-value-integer.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-integer/attribute-value-integer.component.spec.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-integer/attribute-value-integer.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value.component.html, libs/perun/components/src/lib/perun-components.module.ts
* Added handling for editing integer values of attributes
=> Integer attribute value changing implemented

apps/user-profile/src/assets/i18n/cz.json, apps/user-profile/src/assets/i18n/en.json
* Missing czech translations were added to user-profile app
=> Czech translations added to user-profile app

apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-dialog/delete-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-dialog/edit-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.spec.ts, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.html, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.spec.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-resource-attributes/group-settings-resource-attributes.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-resource-attributes/group-settings-resource-attributes.component.spec.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-resource-attributes/group-settings-resource-attributes.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-group-attributes/member-settings-group-attributes.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-group-attributes/member-settings-group-attributes.component.spec.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-group-attributes/member-settings-group-attributes.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-resource-attributes/member-settings-resource-attributes.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-resource-attributes/member-settings-resource-attributes.component.ts, apps/admin-gui/src/app/vos/vos-routing.module.ts, apps/admin-gui/src/app/vos/vos.module.ts, apps/admin-gui/src/assets/i18n/en.json
* Settings for all two entity attributes currently used in Perun were implemented
* Generic component for two entity settings pages was created
* Resolves #212
=> Settings of two-entity attributes finished

apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts, apps/admin-gui/src/app/shared/components/users-list/users-list.component.html, apps/admin-gui/src/app/shared/components/users-list/users-list.component.ts, apps/admin-gui/src/app/shared/pipes/user-logins.pipe.spec.ts, apps/admin-gui/src/app/shared/pipes/user-logins.pipe.ts, apps/admin-gui/src/app/shared/shared.module.ts, libs/perun/openapi/src/lib/api/usersManager.service.ts, libs/perun/openapi/src/lib/model/attributeDefinition.ts, libs/perun/urns/src/lib/perun-urns.ts, libs/perun/utils/src/lib/perun-utils.ts
* Added logins to the users list.
* Generated openApi methods with new method for receiving rich users
with only specific attributes.
=> Users list - logins

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-owners/facility-settings-owners.component.ts
* There was an invalid component selector. Fixed to a correct one.
=> Fixed lint

apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
* Fixed incorrect url while routing to member-resource attributes settings from side menu
=> Bugfix: Fixed routing to member-resource attributes settings

apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.ts
* Side menu now displays only the menu of the lowest entity
* Resolves #231
=> Side menu rework

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/tag-section/tag-section.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-ext-source-dialog/add-ext-source-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-definition-dialog/create-attribute-definition-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-relation-dialog/create-relation-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-vo-dialog/create-vo-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-definition-dialog/delete-attribute-definition-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-definition-dialog/edit-attribute-definition-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-relation-dialog/remove-relation-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-vo-dialog/remove-vo-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/show-notification-history-dialog/show-notification-history-dialog.component.html
Resolves#237
I united style of buttons to mat-flat-button.
=> ISSUE 237: Unify dialogs cancel/close buttons

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.ts
Resolves #248 
* when creating resource it is now possible to filter vos by both name and short name
* filtration is no longer restricted to beginning of string
* dialog window shows vos name and short name
* dialog window is wider to fit both name and short name of vo
=> Create resource - vo search

apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.ts, apps/admin-gui/src/assets/config/defaultConfig.json, apps/admin-gui/src/tsconfig.app.json, package.json, tsconfig.json
* proper version is now in perun-footer
=> Version update

apps/user-profile/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/i18n/cz.json, apps/user-profile/src/assets/i18n/en.json
* repairing labels in profile app
=> Checking labels in profile

angular.json, apps/admin-gui/src/app/admin/admin-routing.module.ts, apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-service-identities/user-settings-service-identities.component.html, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-service-identities/user-settings-service-identities.component.spec.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-service-identities/user-settings-service-identities.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/assets/i18n/en.json, package-lock.json
Resolves #267 
-  user page for setting service identities added
-  contains add and remove button without binding and is also added to side menu
=> user settings service identities page added

apps/admin-gui/src/app/app.module.ts, apps/admin-gui/src/assets/i18n/en.json, apps/user-profile/src/app/app.component.scss, apps/user-profile/src/app/app.module.ts, apps/user-profile/src/app/components/dialogs/change-email-dialog/change-email-dialog.component.ts, apps/user-profile/src/app/components/dialogs/remove-user-ext-source-dialog/remove-user-ext-source-dialog.component.ts, apps/user-profile/src/app/components/dialogs/request-change-data-quota-dialog/request-change-data-quota-dialog.component.html, apps/user-profile/src/app/pages/identities-page/identities-page.component.ts, apps/user-profile/src/app/pages/profile-page/profile-page.component.ts, apps/user-profile/src/assets/i18n/cz.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/bug-report-dialog/bug-report-dialog.component.html, libs/perun/components/src/lib/bug-report-dialog/bug-report-dialog.component.scss, libs/perun/components/src/lib/bug-report-dialog/bug-report-dialog.component.ts, libs/perun/services/src/index.ts, libs/perun/services/src/lib/api.service.ts
* Change email now works correctly
* Added attribute validation into profile page
* Fixed removing external identities
=> User profile update

apps/admin-gui/src/app/admin/admin-routing.module.ts, apps/admin-gui/src/app/admin/admin.module.ts, apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
* Routing to user-facility attributes now works correctly
* Resolves #271
=> User facility routing bugfix

apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html, apps/admin-gui/src/styles.scss
Resolves #246
* Fixed displaying of long words in application detail
=> Application overview line break

apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/vo-select-table/vo-select-table.component.html
Resolves #252 
* added short name display in organization selection
* added short name display in organization detail
=> Vo short name

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-host-dialog/remove-host-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-host-dialog/remove-host-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-host-dialog/remove-host-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #282 
* Add button now works properly
* Remove button now works properly
=> Facility hosts button functionality (again)

apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
Resolves #286 
* Removed service identities from home side-menu
* Removed service identities button from home settings overview
=> Service identities

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-owners/facility-settings-owners.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-owners/facility-settings-owners.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-facility-owner-dialog/add-facility-owner-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-facility-owner-dialog/add-facility-owner-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/add-facility-owner-dialog/add-facility-owner-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-facility-owner-dialog/remove-facility-owner-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-facility-owner-dialog/remove-facility-owner-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-facility-owner-dialog/remove-facility-owner-dialog.component.ts, apps/admin-gui/src/app/shared/components/owners-list/owners-list.component.html, apps/admin-gui/src/app/shared/components/owners-list/owners-list.component.spec.ts, apps/admin-gui/src/app/shared/components/owners-list/owners-list.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/assets/i18n/en.json
* Implemented facility owner page with all the functionality
* Resolves #264
=> Owners page implemented

apps/admin-gui/src/app/facilities/facilities-routing.module.ts, apps/admin-gui/src/app/facilities/facilities.module.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts-detail/facility-hosts-detail.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts-detail/facility-hosts-detail.component.spec.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts-detail/facility-hosts-detail.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-dialog/delete-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-dialog/edit-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html, apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #288 
* Facility hosts are now clickable
* Added host detail, showing host attributes
* Added option to create/edit/remove host attributes
=> Facility hosts detail

apps/admin-gui/src/app/shared/components/dialogs/group-sync-detail-dialog/group-sync-detail-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/group-sync-detail-dialog/group-sync-detail-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/group-sync-detail-dialog/group-sync-detail-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/components/groups-tree/groups-tree.component.html, apps/admin-gui/src/app/vos/components/groups-tree/groups-tree.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/notification/notification.component.html, libs/perun/models/src/lib/GroupFlatNode.ts, libs/perun/models/src/lib/TreeGroup.ts, libs/perun/openapi/src/lib/api/cabinetManager.service.ts, libs/perun/openapi/src/lib/api/groupsManager.service.ts, libs/perun/pipes/src/lib/group-sync-icon-color.pipe.ts, libs/perun/pipes/src/lib/group-sync-icon.pipe.ts, libs/perun/pipes/src/lib/group-sync-tool-tip.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts, libs/perun/urns/src/lib/perun-urns.ts
* Added feature to groups tree view that shows sync status and enables
forcing of synchronizations. It can even work with groupStructure
synchronizations.
=> Group synchronization force

apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.ts, apps/admin-gui/src/assets/config/defaultConfig.json
* Added divider between first and second entity headers inside the side menu
* Resolves #285
=> Divider added to side menu

README.md, libs/perun/services/src/lib/ApiInterceptor.ts, libs/perun/services/src/lib/init-auth.service.ts, libs/perun/services/src/lib/store.service.ts
* Fixed option `skip_oidc`.
* Updated README.md file
=> Improvements for allowing contribution

apps/admin-gui/src/app/shared/pipes/application-state.pipe.ts
* change icon of application state
=> change icon

apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, package-lock.json
Resolves #325 
I deleted the path from home/settings the roles and from file side-menu-item.service in function getUserItem
=> ISSUE 325: Removed roles path

apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html
Resolves #317 
I removed comma from selection between vo.name and vo.shortName and added style text-muted to vo.shortName
=> ISSUE 317: styling vo.name and vo.shortName

apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.html, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html, apps/admin-gui/src/app/shared/components/users-list/users-list.component.html, apps/admin-gui/src/app/shared/components/users-list/users-list.component.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #319 
* removed checkbox column from users table
* added icon to indicate if user is service or person in users table
=> Perun Admin users

apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.html, libs/perun/components/src/lib/notification/notification.component.html, libs/perun/components/src/lib/notification/notification.component.ts
Resolves #323 
* Fix bug with recent notifications timestamp showing wrong time
* Moved log out to end of menu
=> Page head changes

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-overview/resource-settings-overview.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-preview/vo-resources-preview.component.html, apps/admin-gui/src/app/vos/vos-routing.module.ts, libs/perun/components/src/lib/resources-list/resources-list.component.html, libs/perun/components/src/lib/resources-list/resources-list.component.ts, libs/perun/pipes/src/index.ts, libs/perun/pipes/src/lib/get-resource-route.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts
* Resource now shows in side menu under entity it has been opened from
* Resolves #341
=> Side menu - resource rework

apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.html, apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-facility-dialog/create-facility-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-facility-dialog/create-facility-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/create-facility-dialog/create-facility-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-facility-dialog/delete-facility-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-facility-dialog/delete-facility-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-facility-dialog/delete-facility-dialog.component.ts, apps/admin-gui/src/app/shared/components/facility-select-table/facility-select-table.component.html, apps/admin-gui/src/app/shared/components/facility-select-table/facility-select-table.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #318 
* added create/delete option in facility select page
=> Facility create/delete

apps/admin-gui/src/app/facilities/facilities-routing.module.ts, apps/admin-gui/src/app/facilities/facilities.module.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-managers/resource-settings-managers.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-managers/resource-settings-managers.component.spec.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-managers/resource-settings-managers.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-overview/resource-settings-overview.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.ts, apps/admin-gui/src/app/vos/vos-routing.module.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #326 
* created page for Resource Managers in Resource Setting
=> Resource managers

apps/admin-gui/src/app/admin/admin-routing.module.ts, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-dialog/delete-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.ts, apps/admin-gui/src/app/shared/components/identity-detail/identity-detail.component.html, apps/admin-gui/src/app/shared/components/identity-detail/identity-detail.component.spec.ts, apps/admin-gui/src/app/shared/components/identity-detail/identity-detail.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, libs/perun/components/src/lib/attributes-list/edit-attribute-dialog/edit-attribute-dialog.component.ts, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.scss, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts
Resolves #320 
* user identities in Perun Admin are now clickable
* created user identity detail page
* added option to add/remove/edit user identity attributes
=> Identity detail

apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts, apps/admin-gui/src/assets/config/defaultConfig.json
* When creating group, additional name validation regex can be used
* The new validation regex and custom error message are set in the GUI config
* Create group dialog code was adjusted
* Resolves #361
=> Group name secondary regex

apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html, apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.scss, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html, apps/admin-gui/src/assets/i18n/en.json, apps/admin-gui/src/styles.scss
Resolves #375 
* added additional information to entities titles
=> Entities information

apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.ts, apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json
* Added validation while adding a new member to Group or VO
* Resolves #384
=> Add member validation added

apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #390 
* added invite button to Vo members
=> Vo invite members

apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts, apps/admin-gui/src/app/shared/side-menu/side-menu.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.scss, libs/perun/services/src/lib/gui-auth-resolver.service.ts
authorization algorithm implemented
=> Authorization

apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.ts, apps/admin-gui/src/assets/i18n/en.json
* Added notifications whether was application form copied
* Selected group now resets when VO is changed
* Resolves #351
=> Copy empty application form - warning message

apps/admin-gui/src/assets/i18n/en.json, apps/user-profile/src/app/app.component.html, apps/user-profile/src/app/app.component.scss, apps/user-profile/src/app/app.module.ts, apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.html, apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.scss, apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.spec.ts, apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.ts, apps/user-profile/src/assets/i18n/cz.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/show-value-dialog/show-value-dialog.component.html, package-lock.json, package.json
* New component for breadcrumb navigation was added as replacement for old library
=> User profile - Breadcrumb update

apps/admin-gui/src/app/app.module.ts, apps/admin-gui/src/app/shared/pipes/member-status-tooltip.pipe.ts, apps/admin-gui/src/app/shared/pipes/transform-member-status.pipe.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/components/members-list/members-list.component.html, apps/admin-gui/src/app/vos/components/members-list/members-list.component.scss, apps/admin-gui/src/app/vos/components/members-list/members-list.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.scss, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, apps/admin-gui/src/styles.scss, libs/perun/components/src/index.ts, libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.html, libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.scss, libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.spec.ts, libs/perun/components/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/urns/src/lib/perun-urns.ts, libs/perun/utils/src/lib/perun-utils.ts
* Added dialog template for setting membership expiration
* Membership statuses VALID/INVALID were changed to ACTIVE/INACTIVE
* On hover over a status icon, the expiration date is displayed (for group memberships, if group expiration is not available, Vo expiration is shown)
* Added button to change member's expiration while in member detail
* Resolves #382
=> Member expiration improvements

apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts, libs/perun/services/src/lib/auth.service.ts
* There was a bug that caused redirect to the home page even when it was
not needed.
=> Fixed redirect to home after refresh

apps/admin-gui/src/app/shared/components/user-detail-page/user-identities/user-identities.component.html
Resolves#376
I made addition in user-identities.component.html when data are loading table is hidden.
=> Issue 376: User - Identities

apps/admin-gui/src/styles.scss
* Fixed bug, where header checkbox was not aligned with other checkboxes
=> Header checkbox position fix

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts, apps/admin-gui/src/app/shared/components/dialogs/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.spec.ts, apps/admin-gui/src/app/shared/components/dialogs/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/openapi/src/lib/api/groupsManager.service.ts
- Resolves #328 
- edit buttons with dialogs added to facility, resource, vo and group pages
=> Edits for facility, resource, vo, group implemented

apps/admin-gui/src/app/shared/components/user-detail-page/user-dashboard/user-dashboard.component.ts, apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.ts, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts
Resolves #398
- Added authorization check to dashboard if needed, also removed unnecessary check.
- Added authorization for attributes list
=> Authorization home section

libs/perun/components/src/lib/group-menu/group-menu.component.html, libs/perun/components/src/lib/group-menu/group-menu.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts
* Fixed bug, where user was rerouted after clicking on any item in group menu
=> Group list routing fix

apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-settings/member-settings-overview/member-settings-overview.component.ts, apps/admin-gui/src/app/vos/vos-routing.module.ts, apps/admin-gui/src/app/vos/vos.module.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/index.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-integer/attribute-value-integer.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-string/attribute-value-string.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts
Resolves #397 
Added authorization for:
* Overview - items, expiration attribute (authorization for this attr. is hardcoded for now)
* Sidemenu items
* Groups - Add/Remove buttons, routing, Add dialog (display of group)
* Resources - Add button, routing, Add dialog (disabled selection)
* Attributes - attribute list now disables checkbox and input for attributes that user cannot edit, on hover a hint is displayed
=> Authorization member section

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-services/resource-assigned-services.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-dialog/delete-attribute-dialog.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts, apps/admin-gui/src/app/shared/components/services-list/services-list.component.scss, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/vos-routing.module.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html, libs/perun/components/src/lib/attributes-list/edit-attribute-dialog/edit-attribute-dialog.component.ts
* Authorization for resource section was added (except for managers page)
* Resolves #396
=> Authorization - resource section

apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.html
Resolves #451 
* fixed selection of group in copy application form dialog
=> Vo/Group application form - copy form dialog

apps/user-profile/src/app/pages/identities-page/identities-page.component.html, apps/user-profile/src/app/pages/settings-page/settings-ssh-keys/settings-ssh-keys.component.html, apps/user-profile/src/app/pages/settings-page/settings-ssh-keys/settings-ssh-keys.component.scss, apps/user-profile/src/app/services/user-profile-config.service.ts, apps/user-profile/src/assets/i18n/cz.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.scss, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts
* Fixes for bugs caused (primarily) by recent updates to the admin-gui
=> User profile bugfixes

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-facility-dialog/create-facility-dialog.component.html, apps/admin-gui/src/app/shared/components/facility-select-table/facility-select-table.component.html, apps/admin-gui/src/assets/i18n/en.json
Resolves #439 
* added option to unselect copy option when creating facility
* added vo id in allowed groups
* facility table is now sorted by name from the beginning
=> Small fixes in facility section

apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #427 
* added invite button to groups members section
=> Group invitation

libs/perun/services/src/lib/notificator.service.ts
Resolves #416 
* fixed error message when error is undefined
=> Undefined error message

apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts, libs/perun/services/src/lib/init-auth.service.ts
Resolves #452 
* principal is reloaded after creating Vo, Group or Facility
=> Reload principal

apps/admin-gui/src/app/shared/pipes/member-status-icon.pipe.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, libs/perun/services/src/lib/members.service.ts, libs/perun/utils/src/lib/perun-utils.ts
Resolves #449 
* member status SUSPENDED was removed
=> Remove suspended status

apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/components/src/lib/vo-search-select/vo-search-select.component.html, libs/perun/components/src/lib/vo-search-select/vo-search-select.component.spec.ts, libs/perun/components/src/lib/vo-search-select/vo-search-select.component.ts, package-lock.json, package.json
* Added new library with search select.
* Implemented first usage in the create resource dialog.
=> Search select

apps/admin-gui/src/app/vos/components/members-list/members-list.component.html, apps/admin-gui/src/app/vos/components/members-list/members-list.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, libs/perun/utils/src/lib/perun-utils.ts
Resolves #329 
* added column with logins to member list
=> Member list logins

apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, libs/perun/components/src/lib/members-list/members-list.component.html, libs/perun/components/src/lib/members-list/members-list.component.ts, libs/perun/utils/src/lib/perun-utils.ts
Reverts CESNET/perun-web-apps#450
=> Revert "Member list logins"

apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/index.ts
Resolves #458 
* added info about synchronization to group detail
* disabled add button in group members if group is synched to some ext. source
=> Group synch indication

apps/admin-gui/src/app/facilities/facilities-routing.module.ts, apps/admin-gui/src/app/facilities/facilities.module.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-task-results/facility-task-results.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-task-results/facility-task-results.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-task-result-dialog/delete-task-result-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-task-result-dialog/delete-task-result-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/assets/i18n/en.json, libs/config/table-config/src/lib/table-config.service.ts, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/components/src/lib/services-status-list/services-status-list.component.html, libs/perun/components/src/lib/task-results-list/task-results-list.component.css, libs/perun/components/src/lib/task-results-list/task-results-list.component.html, libs/perun/components/src/lib/task-results-list/task-results-list.component.ts
Resolves #459 
* added page with task results of services
=> Facility task results

apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-data-dialog/edit-application-form-item-data-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-data-dialog/edit-application-form-item-data-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html, apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #465 
* added option to edit data in application form submitted by user, if the application was not approved/rejected yet
=> Appliation detial - edit form item data

apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts
Resolves #485 
* selection in this dialog is disabled for groups that are synchronized and groups that user is already member of
=> AddMemberGroupDialog changes

apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/group-search-select/group-search-select.component.html, libs/perun/components/src/lib/group-search-select/group-search-select.component.ts, libs/perun/components/src/lib/perun-components.module.ts
Resolves #487 
* added option of creating subgroup from scratch to create group dialog
=> Create group as subgroup

package.json
* Now, the version command also builds the user-profile app and adds it
to releases.
=> Add user-profile to releases

apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/group-search-select/group-search-select.component.html, libs/perun/components/src/lib/group-search-select/group-search-select.component.ts, libs/perun/components/src/lib/perun-components.module.ts
Resolves #473 
* fixed bug when copy form items dialog would load Vos that user cannot access
=> Copy form item privilege bug fix

apps/user-profile/src/app/components/side-menu/side-menu.component.html, apps/user-profile/src/app/components/side-menu/side-menu.component.ts, apps/user-profile/src/app/services/side-menu-item.service.ts, apps/user-profile/src/assets/config/defaultConfig.json, libs/perun/openapi/src/lib/api.module.ts
* Added config option to add link to external services
=> User profile - External services

apps/user-profile/src/app/app.module.ts, apps/user-profile/src/app/components/side-menu/side-menu.component.html, apps/user-profile/src/app/components/side-menu/side-menu.component.ts, apps/user-profile/src/app/pipes/localization-label.pipe.ts, apps/user-profile/src/assets/config/defaultConfig.json
=> User profile - External services fix

apps/user-profile/src/app/pages/profile-page/profile-page.component.ts
* Invalid timezones were removed
=> User profile timezones fix

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts
Resolves #494 
* added filter to allowed groups page
* group list organization column now shows name of organization instead of id
=> Allowed groups filter, Group list org column

apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts, apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.ts, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts
Resolves #471 
* added cache to select Vo/Facility page
=> Add cache to access and facility management

libs/perun/components/src/lib/groups-tree/groups-tree.component.html, libs/perun/dialogs/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.ts
Resolves #503 
* fixed opening of edit dialog, in groups table in Vo section
=> Edit group button in Vo section

apps/admin-gui/src/app/shared/components/facility-select-table/facility-select-table.component.html, apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html, apps/admin-gui/src/app/shared/components/services-list/services-list.component.html, apps/admin-gui/src/app/shared/components/users-list/users-list.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.html, apps/admin-gui/src/app/shared/side-menu/side-menu-root-item/side-menu-root-item.component.html, apps/admin-gui/src/app/vos/components/application-list-details/application-list-details.component.html, apps/admin-gui/src/app/vos/components/application-list-details/application-list-details.component.ts, apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.html, apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-tree/groups-tree.component.html, libs/perun/components/src/lib/members-list/members-list.component.html, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/components/src/lib/resources-list/resources-list.component.html, libs/perun/components/src/lib/services-status-list/services-status-list.component.html, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html, libs/perun/components/src/lib/vo-select-table/vo-select-table.component.html, libs/perun/directives/src/index.ts, libs/perun/directives/src/lib/middle-click-router-link.ts
Resolves #496 
* Added middle click action to sidemenu and tables
=> Middle click action

apps/admin-gui/src/app/admin/admin-routing.module.ts, apps/admin-gui/src/app/admin/admin.module.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-destinations/service-destinations.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-destinations/service-destinations.component.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-overview/service-overview.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.ts, apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html, apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-services-destination-dialog/add-services-destination-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-services-destination-dialog/add-services-destination-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-destination-dialog/remove-destination-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-destination-dialog/remove-destination-dialog.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #457 
* added page with destinations to service detail
=> Service destinations

apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-application-form-item-dialog/add-application-form-item-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-application-form-item-dialog/add-application-form-item-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-user-ext-source-dialog/add-user-ext-source-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-user-ext-source-dialog/add-user-ext-source-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/connect-identity/connect-identity.html, apps/admin-gui/src/app/shared/components/dialogs/connect-identity/connect-identity.ts, apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json
Resolves #448 
- added FormControls to dialogs and components with search. If search filed is empty and search button is clicked, search field will show standard error message
=> Search changes

apps/user-profile/src/app/app.component.scss, apps/user-profile/src/app/components/dialogs/request-change-data-quota-dialog/request-change-data-quota-dialog.component.ts, apps/user-profile/src/app/components/header/header.component.html, apps/user-profile/src/app/pages/identities-page/identities-page.component.html, apps/user-profile/src/app/pages/identities-page/identities-page.component.ts, apps/user-profile/src/app/pages/profile-page/profile-page.component.html, apps/user-profile/src/app/pages/profile-page/profile-page.component.ts, apps/user-profile/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/i18n/cz.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, package-lock.json
* Added option in config to hide identity certificates
* Added possibility to display additional user attributes in profile tab based on config
=> User profile - Fixes and changes based on feedback

apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.ts
Resolves #517 
* added new selectors to copy notification dialog
=> Copy notification new selectors

libs/perun/components/src/lib/members-list/members-list.component.ts
Resolves #549 
* members are now sorted with respect to Czech alphabet order
* there might be room for optimisation if needed
=> Sorting members using Czech alphabet

apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.ts, apps/admin-gui/src/app/shared/components/blacklist-list/blacklist-list.component.ts, apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.ts, apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.ts, apps/admin-gui/src/app/shared/components/facility-select-table/facility-select-table.component.ts, apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.ts, apps/admin-gui/src/app/shared/components/owners-list/owners-list.component.ts, apps/admin-gui/src/app/shared/components/resources-tags-list/resources-tags-list.component.ts, apps/admin-gui/src/app/shared/components/security-teams-list/security-teams-list.component.ts, apps/admin-gui/src/app/shared/components/services-list/services-list.component.ts, apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts, apps/admin-gui/src/app/shared/components/users-list/users-list.component.ts, apps/admin-gui/src/app/vos/components/application-list-details/application-list-details.component.ts, apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.ts, apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.ts, libs/perun/components/src/lib/attributes-list/attributes-list.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/components/src/lib/groups-tree/groups-tree.component.html, libs/perun/components/src/lib/groups-tree/groups-tree.component.ts, libs/perun/components/src/lib/members-list/members-list.component.ts, libs/perun/components/src/lib/resources-list/resources-list.component.ts, libs/perun/components/src/lib/services-status-list/services-status-list.component.ts, libs/perun/components/src/lib/task-results-list/task-results-list.component.ts, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts, libs/perun/components/src/lib/vo-select-table/vo-select-table.component.ts
Resolves #546 
* id of entities in tables is now only visible for perun admins
=> Ids in tables

libs/perun/components/src/lib/groups-tree/groups-tree.component.ts
Resolves #547 
* fixed filtering in vo groups by changing the filter element
=> Filtering in vo groups fixed

apps/admin-gui/src/app/facilities/facilities-routing.module.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts
Resolves #541 
* changed position of attribute page in overview/sidemenu to be second to last / last depending on existence of advanced settings 
for given entity
=> Attributes position in overview/sidemneu

apps/admin-gui/src/app/shared/pipes/attribute-friendly-name.pipe.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.scss, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/assets/config/defaultConfig.json, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/store.service.ts, libs/perun/utils/src/lib/perun-utils.ts
Resolves #504 
* added table with member personal info to member overview
* added default personal info to be shown to default config
=> Member profile

apps/admin-gui/src/app/admin/pages/admin-page/admin-overview/admin-overview.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts, libs/perun/components/src/lib/menu-buttons-field/menu-buttons-field.component.html, libs/perun/components/src/lib/menu-buttons-field/menu-buttons-field.component.scss, libs/perun/models/src/lib/MenuItem.ts
Resolves #495 
* added drop down menu for overview buttons that redirect to another overview
* this works like a sign for the user and can also be used for quicker access
* added authorisation to drop-down menu items
=> Overview button leads to more buttons sign

apps/admin-gui/src/app/admin/pages/admin-page/admin-overview/admin-overview.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts, libs/perun/components/src/lib/menu-buttons-field/menu-buttons-field.component.html, libs/perun/components/src/lib/menu-buttons-field/menu-buttons-field.component.scss, libs/perun/models/src/lib/MenuItem.ts
Reverts CESNET/perun-web-apps#528
=> Revert "Overview button leads to more buttons sign"

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.ts
* hopefully fixed problem with sponsor role not having voId
=> Home page not loding

apps/admin-gui/src/app/app.component.ts, apps/admin-gui/src/app/shared/components/dialogs/new-version-dialog/new-version-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/new-version-dialog/new-version-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/assets/config/version.json, apps/admin-gui/src/assets/i18n/en.json, create-version-file.sh, package.json
* THE FUNCTIONALITY IS YET TO BE TESTED
* Added periodic check (every 30 seconds), whether the version of GUI changed and if so, the app is reloaded
* Resolves #544
=> Detection of new version of GUI

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-relation-dialog/create-relation-dialog.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-groups/user-groups.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-relations/group-settings-relations.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.html, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.scss, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts, libs/perun/openapi/src/lib/model/inputCreateSponsoredMember1.ts, libs/perun/pipes/src/index.ts, libs/perun/pipes/src/lib/group-expiration.pipe.ts, libs/perun/pipes/src/lib/parse-date.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts
* Actual OpenAPI methods were generated
* Added expiration column into groups-list
* Resolves #466
=> Expiration of member in groups

apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html, apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts, apps/admin-gui/src/assets/i18n/en.json
* added button with dialog for password reset to sponsored-members-list
=> Password reset of existing sponsored user

apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/edit-member-sponsors-dialog/edit-member-sponsors-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-member-sponsors-dialog/edit-member-sponsors-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts, apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html, apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/index.ts, libs/perun/components/src/lib/expiration-select/expiration-select.component.css, libs/perun/components/src/lib/expiration-select/expiration-select.component.html, libs/perun/components/src/lib/expiration-select/expiration-select.component.ts, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.html, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts, libs/perun/openapi/src/lib/model/roleManagementRules.ts, package-lock.json
* added setting of sponsorship of existing sponsored members as well as when creating new one
=> Sponsored user expiration

apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html
resolves #567 
I changed buttons positions. Button 'Add' instead of button 'Invite' and the other way around.
=> Issue 567: Change button position

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-overview/resource-settings-overview.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-overview/vo-settings-overview.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/gui-auth-resolver.service.ts
Related task: # 6813
* added authorisation in managers page for:
* selected roles and their 'mode' based on Perun rules
* add/remove buttons
* missing sidemenu and overview authorisation
=> Managers page authorisation

apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.scss, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/assets/i18n/en.json
Related to: https://homeproj.cesnet.cz/issues/6877
* Added status selection to group members page
* Changed search methods to filter by selected statuses
=> Search group members with status

apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.ts, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts, libs/perun/services/src/lib/ApiInterceptor.ts
Related to: https://homeproj.cesnet.cz/issues/6747
* perun principal will be reloaded after every post request
* other, now redundant, principal reloading calls were removed
=> Reload principal on POST request

apps/admin-gui/src/app/shared/components/dialogs/create-attribute-definition-dialog/create-attribute-definition-dialog.component.ts
Related to: https://homeproj.cesnet.cz/issues/6883
* removed option to assign LargeString or LargeArray to attribute definition
=> Remove large attributes

apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts, libs/perun/components/src/lib/recently-viewed-icon/recently-viewed-icon.component.css, libs/perun/components/src/lib/recently-viewed-icon/recently-viewed-icon.component.html
* wrong policy for applications deleted
* changed color of icon for recently viewed
=> minor fixes

libs/perun/components/src/lib/services-status-list/services-status-list.component.html, libs/perun/components/src/lib/services-status-list/services-status-list.component.ts
* Fixed recent bug, where services status list didn't work, because paginator wasn't initialized correctly
=> Services status list fix

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.scss, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.ts, apps/admin-gui/src/assets/i18n/en.json
* added right menu to dashboard where user can modify his personal settings
=> dashboard settings right menu implemented

apps/user-profile/src/app/pages/identities-page/identities-page.component.html, apps/user-profile/src/app/pages/identities-page/identities-page.component.scss, apps/user-profile/src/app/pages/identities-page/identities-page.component.ts, apps/user-profile/src/app/pages/profile-page/profile-page.component.html, apps/user-profile/src/app/pages/profile-page/profile-page.component.scss, apps/user-profile/src/app/pages/profile-page/profile-page.component.ts, apps/user-profile/src/app/services/side-menu-item.service.ts, apps/user-profile/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, package-lock.json
* Updated localisation files in user profile app
* Fixed displaying of user attributes with long names
* Attributes displayed in the Profile page are now all specified in config, including their order
* Added option to change the order of side-menu items displayed through config
* Added tooltip to clarify "Other" identities in the Identities tab
* Preferred language attribute value meaning czech changed from 'cz' to 'cs'
=> User profile - few fixes

apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.ts
* fixed adding external identity into the VO/Group - to this day user couldnt add candidate because we were sending the method wrong data
=> fix add external identity to VO

apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.ts, apps/admin-gui/src/assets/i18n/en.json, apps/admin-gui/src/styles.scss, libs/perun/components/src/lib/date-range/date-range.component.html, libs/perun/components/src/lib/date-range/date-range.component.ts, libs/perun/components/src/lib/perun-components.module.ts, libs/ui/material/src/lib/ui-material.module.ts
* In Vo and Group has been added date filter which is by default set to display one year old applications.
* User can edit range of the date and this setting is also saved into local storage.
* In Vo has been also added other new filter which allows user to display only applicaions to Vo (without Groups applications).
=> Added filters for applications in Vo/Group

apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json
* Now Vo admin or Group admin is able to set new attribute for his Vo/group, which disabled manual member adding.
* If this attribute is set for Vo, then this configuration will be set also for all groups in this Vo.
=> Added support for disable manually add members to specific Vo or group

apps/admin-gui/src/app/app.component.ts, libs/perun/components/src/lib/back-button/back-button.component.html, libs/perun/components/src/lib/back-button/back-button.component.ts, libs/perun/services/src/lib/store.service.ts
* back button is not visible when it would cause user to leave the app
=> Back button visibility

apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts, apps/admin-gui/src/app/shared/components/users-list/users-list.component.html, apps/admin-gui/src/assets/i18n/en.json
* removed selector for mode
* instead managers page now has tabs for users and groups
=> Managers page select mode changed

apps/admin-gui/src/app/admin/pages/admin-page/admin-attributes/admin-attributes.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-definition-dialog/create-attribute-definition-dialog.component.ts, libs/perun/utils/src/lib/perun-utils.ts
* The core attributes were filtered on the admin page, however, we want
to be able to see them.
* Also, we want to be able to create core attributes.
=> Admin - core attributes

apps/admin-gui/src/app/users/pages/user-detail-page/user-resources/user-resources.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-resources/user-resources.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/resources-list/resources-list.component.html
- Enable sorting for VO/Facility/Tags columns
in Resources-List component.
- Support Resources-List filtering on User Resources
page.
=> Add filter and sorting to user resources page

apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json
- Added groups-list filtering in add-group-manager-dialog.
=> Added filter to add-group-manager-dialog

apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-services-destination-dialog/add-services-destination-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-services-destination-dialog/add-services-destination-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json
* When creating hosts, we now validate the format, if all of the given
hosts are valid.
* When creating a destination, we validate the format of the destination
depending on the selected host type.
=> AdminGui - host and destination format validation

libs/perun/services/src/lib/table-checkbox.service.ts
* Table checkbox service was optimized
=> Table checkbox optimization

apps/admin-gui/src/app/shared/side-menu/side-menu.component.ts
* Changed behavior of Perun admin side menu for better UX in Users section and Services section.
=> Perun admin side menu

apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/members-list/members-list.component.html
* Label for filter was changed.
* Header of table for status column was changed.
=> Edited member status in group section

apps/admin-gui/src/app/admin/admin-routing.module.ts, apps/admin-gui/src/app/admin/admin.module.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-overview/admin-overview.component.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-owners/admin-owners.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-owners/admin-owners.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts, apps/admin-gui/src/app/shared/components/add-owner-dialog/add-owner-dialog.component.html, apps/admin-gui/src/app/shared/components/add-owner-dialog/add-owner-dialog.component.ts, apps/admin-gui/src/app/shared/components/delete-owner-dialog/delete-owner-dialog.component.html, apps/admin-gui/src/app/shared/components/delete-owner-dialog/delete-owner-dialog.component.ts, apps/admin-gui/src/app/shared/components/owners-list/owners-list.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/custom-icon.service.ts
* Owners page was added to 'Perun admin' section
* Owners can be added, deleted, filtered and sorted
=> Owners page added

apps/admin-gui/src/app/shared/components/statistics-card/statistics-card.component.html, apps/admin-gui/src/app/shared/components/statistics-card/statistics-card.component.scss, apps/admin-gui/src/app/shared/components/statistics-card/statistics-card.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts, apps/admin-gui/src/assets/i18n/en.json
* added table with members count per status to vo overview
=> Vo overview statistics

apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/user-search-select/user-search-select.component.html, libs/perun/components/src/lib/user-search-select/user-search-select.component.ts, libs/perun/services/src/lib/gui-auth-resolver.service.ts
* added option to choose different sponsor when user is authorized to do so
* implemented stepper to "create sponsored member" dialog
=> Set different sponsor when creating sponsored member

apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts
* group observer now can go to vo-members, group-members, member-overview and member-groups without him getting priviledge exception
=> group observer role fixed

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-members/resource-assigned-members.component.html, apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/members-list/members-list.component.html, libs/perun/components/src/lib/members-list/members-list.component.scss, libs/perun/components/src/lib/members-list/members-list.component.ts, libs/perun/openapi/src/lib/api/membersManager.service.ts, libs/perun/openapi/src/lib/api/tasksManager.service.ts, libs/perun/openapi/src/lib/api/usersManager.service.ts
* Now users can sponsor some member who is already sponsored by someone else.
* In sponsor existing member dialog is new column that represent state if member is already sponsored or not.
=> Sponsor already sponsored members

apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.ts
* dialog create-sponsored-member - choosing somebody else sponsor -  only direct sponsors of the vo were displayed
* now all sponsors are acquired and user can choose from all sponsors
=> fix getting sponsors of the Vo

apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts, apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, package.json
* added cache for page with sponsored users
* added functionality with middle click to the sponsored-members-list.component.html
* redesign button "create" and "create in bulk"
* updated version
=> sponsored members experience improved

apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/openapi/src/lib/api/usersManager.service.ts
* added option to list users that are not member of any organization to  perun admin - users section
=> Find users without organization

apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/openapi/src/lib/api/groupsManager.service.ts
- Added two statistic cards to group overview - members counts by group
and VO status.
=> Group overview statistics

apps/password-reset/src/app/app.component.ts, apps/password-reset/src/app/app.module.ts, apps/password-reset/src/app/dialogs/password-reset-dialog/password-reset-dialog.component.html, apps/password-reset/src/app/dialogs/password-reset-dialog/password-reset-dialog.component.scss, apps/password-reset/src/app/dialogs/password-reset-dialog/password-reset-dialog.component.ts, apps/password-reset/src/app/dialogs/token-expired-dialog/token-expired-dialog.component.html, apps/password-reset/src/app/dialogs/token-expired-dialog/token-expired-dialog.component.scss, apps/password-reset/src/app/dialogs/token-expired-dialog/token-expired-dialog.component.ts, apps/password-reset/src/assets/config/defaultConfig.json, apps/password-reset/src/assets/i18n/en.json, apps/password-reset/src/index.html, apps/password-reset/src/styles.scss, libs/perun/openapi/src/lib/api/tasksManager.service.ts, libs/perun/openapi/src/lib/api/usersManager.service.ts, libs/perun/services/src/lib/ApiInterceptor.ts
* it is now possible to change password in Password reset app
* added password strength check
* added token validity check
=> Password reset implementation

apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts, apps/admin-gui/src/app/shared/pipes/application-form-item-disabled.pipe.ts, apps/admin-gui/src/app/shared/pipes/application-form-item-hidden.pipe.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/index.ts, libs/perun/components/src/lib/app-form-item-search-select/app-form-item-search-select.component.html, libs/perun/components/src/lib/app-form-item-search-select/app-form-item-search-select.component.spec.ts, libs/perun/components/src/lib/app-form-item-search-select/app-form-item-search-select.component.ts, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/openapi/src/lib/model/applicationFormItem.ts, libs/perun/utils/src/lib/perun-utils.ts, package.json
* From now, it is possible to set new parameters for application items.
* Updatable - if checked, the item can be updated after application
submission.
* Hidden - defines, when the item will be hidden during application
submission.
* Hidden dependency - another item from the same application form, if
specified, the hidden condition is evaluated on this item instead.
* Disabled - defines, when the item will be disabled during application
submission.
* Disabled dependency - another item from the same application form, if
specified, the disabled condition is evaluated on this item instead.
=> AdminGUI - form items rework

apps/user-profile/src/app/components/add-token-info-dialog/add-token-info-dialog.component.ts, apps/user-profile/src/assets/config/defaultConfig.json, package-lock.json
* URL for adding TOTP device can now be changed from configuration file
=> Moving URL for TOTP to config

apps/publications/src/app/pages/create-publication-page/create-publication-page.component.html, apps/publications/src/app/pages/create-publication-page/create-publication-page.component.scss, apps/publications/src/assets/i18n/en.json
* added layout to create publication page
* implementation of importing/creating publication is not part of this PR
=> Create publication layout

apps/admin-gui/src/app/shared/components/dialogs/delete-entity-dialog/delete-entity-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-entity-dialog/delete-entity-dialog.component.scss, apps/admin-gui/src/app/shared/components/dialogs/delete-entity-dialog/delete-entity-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts, apps/admin-gui/src/assets/i18n/en.json
* created new dialog for deleting entities so far only Vo is implemented
* added option to delete Vo on its detail
* replaced existing remove dialog
=> Delete Vo dialog

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/tag-bar/tag-bar.component.ts, apps/admin-gui/src/assets/i18n/en.json
* Added description of the new {redirectUrl} tag to the notification
edit dialog.
=> Admin GUI - redirectUrl tag

apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-statistics/vo-statistics.component.ts, libs/perun/openapi/src/lib/api/vosManager.service.ts
* VO statistics used to get data from two methods. Now this component is using only one method for that.
=> Get data for VO statistics from one method

libs/perun/dialogs/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.ts
* While editing name of a subgroup, only name of subgroup is shown
=> Validation of name in subgroup fix

libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-map/attribute-value-map.component.scss
* key and value in map attributes are now closer to each other
* map attributes are now aligned to the left to match other attribute types
=> Map attributes margin reduced

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-members/resource-assigned-members.component.html, apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/members-list/members-list.component.html, libs/perun/components/src/lib/members-list/members-list.component.scss, libs/perun/components/src/lib/members-list/members-list.component.ts
* Added column to members-list containing membership type
* Disabled removing of indirect members
* This is a preparation for further changes
=> Displaying membership type implemented

package.json
- Upgraded due to a new release which already uses this version.
=> Upgraded package.json to 0.20.0

apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.html
small change in member-overview.component.html visuals
=> small change in change-expiration-dialog.component.html visuals

apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html, apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html, apps/admin-gui/src/assets/i18n/en.json
* changed icon for new type of application
* on application detail the EMBEDDED_GROUP_APPLICATION cant be edited
* added slide-toogle to group-settings-application-form.component to add/remove the group from the set of groups to register
=> changes for epic - EMBEDDED_GROUP_APPLICATION

apps/admin-gui/src/assets/config/defaultConfig.json, libs/perun/services/src/lib/auth.service.ts
* Configurable authentication filter was added
* Filter can be applied by adding query parameter
* Contents of default config regarding this change are there just for inspiration and will be removed before merge
=> Add authentication filter

package-lock.json, package.json
* There was an invalid command which was used to generate the openapi library.
=> build(openapi): fix command to generate openapi library

apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/members-list/members-list.component.html, libs/perun/components/src/lib/members-list/members-list.component.ts, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/dialogs/src/lib/member-tree-view-dialog/member-tree-view-dialog.component.html, libs/perun/dialogs/src/lib/member-tree-view-dialog/member-tree-view-dialog.component.scss, libs/perun/dialogs/src/lib/member-tree-view-dialog/member-tree-view-dialog.component.ts, libs/perun/dialogs/src/lib/perun-dialogs.module.ts, libs/perun/openapi/src/lib/api/groupsManager.service.ts, libs/perun/pipes/src/index.ts, libs/perun/pipes/src/lib/parse-group-name.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts
* Added dialog for displaying paths to member's direct groups
* Dialog support filtering the paths to direct/included groups
* Newest OpenAPI was generated
=> Dialog for displaying indirect member's origin 

apps/user-profile/src/app/app.component.html, apps/user-profile/src/app/app.component.scss, apps/user-profile/src/app/app.component.ts, apps/user-profile/src/app/app.module.ts, apps/user-profile/src/app/components/header/header.component.html, apps/user-profile/src/app/components/header/header.component.ts, apps/user-profile/src/app/components/profile-login-screen-base/profile-login-screen-base.component.html, apps/user-profile/src/app/components/profile-login-screen-base/profile-login-screen-base.component.ts, apps/user-profile/src/styles.scss
* Added support for login screen to the user profile.
=> feat(profile): added login screen

apps/admin-gui/src/app/app.component.ts, libs/perun/services/src/lib/auth.service.ts
* The idpFilter query parameter is now kept in the URL.
=> feat(auth): keep idpFilter in URL after route change

apps/publications/src/app/app.module.ts, apps/publications/src/app/components/authors-list/authors-list.component.html, apps/publications/src/app/components/authors-list/authors-list.component.ts, apps/publications/src/app/dialogs/add-authors-dialog/add-authors-dialog.component.html, apps/publications/src/app/dialogs/add-authors-dialog/add-authors-dialog.component.scss, apps/publications/src/app/dialogs/add-authors-dialog/add-authors-dialog.component.ts, apps/publications/src/app/pages/authors-page/authors-page.component.html, apps/publications/src/app/pages/publication-detail/publication-detail.component.html, apps/publications/src/app/pages/publication-detail/publication-detail.component.ts, apps/publications/src/assets/i18n/en.json
* Created new dialogs for adding and removing authors from publication detail.
* User can consecutively searches more authors and then adds them all at once.
=> Add and remove authors form publication detail

package.json
* Changed the `version` script so the publications app is build as well and added to releases.
=> build(npm): add publications app to releases

apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.ts, apps/admin-gui/src/assets/i18n/en.json
- Preferred mail change requests can now be validated in admin GUI.
=> Admin: preferred mail change validation

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.ts, apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-entity-dialog/delete-entity-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-entity-dialog/delete-entity-dialog.component.scss, apps/admin-gui/src/app/shared/components/dialogs/delete-entity-dialog/delete-entity-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-facility-dialog/delete-facility-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-facility-dialog/delete-facility-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/delete-group-dialog/delete-group-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-group-dialog/delete-group-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-resource-dialog/remove-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-resource-dialog/remove-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/remove-vo-dialog/remove-vo-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-vo-dialog/remove-vo-dialog.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts, apps/admin-gui/src/assets/i18n/en.json
* groups, facilities and resource can now be deleted from detail
=> Delete entities from detail

libs/perun/services/src/lib/ApiInterceptor.ts, libs/perun/services/src/lib/auth.service.ts, libs/perun/session-expiration/src/lib/session-expiration-dialog/session-expiration-dialog.component.html, libs/perun/session-expiration/src/lib/session-expiration-dialog/session-expiration-dialog.component.ts
* session expiration dialog now redirects user to authentication page  directly
=> Session expiration dialog behaviour

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.ts, apps/admin-gui/src/assets/i18n/en.json, apps/user-profile/src/app/pages/profile-page/profile-page.component.ts, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/dialogs/src/index.ts, libs/perun/dialogs/src/lib/mail-change-failed-dialog/mail-change-failed-dialog.component.html, libs/perun/dialogs/src/lib/mail-change-failed-dialog/mail-change-failed-dialog.component.ts, libs/perun/dialogs/src/lib/perun-dialogs.module.ts
* In case user is redirected to user-profile or admin-gui from link with invalid query parameters for changing preferred mail, dialog with info is displayed and query parameters are cleared
=> Invalid preferred mail change request handling

package.json
=> Package.json version increased

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-attributes/facility-attributes.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-attributes/facility-attributes.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts, apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.html, apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.ts, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-attributes/user-attributes.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-attributes/user-attributes.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-attributes/vo-attributes.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-attributes/vo-attributes.component.ts
* new component one-entity-attribute-page.component added for page where we are viewing attributes of one entity
=> add user and facility-user attributes as tab to member attributes page

apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts, libs/perun/components/src/lib/members-list/members-list.component.ts
* fix filtering in sponsored-members-list.component.ts and members-list.component.ts
=> fix filtering in sponsored members and members list

apps/admin-gui/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/config/defaultConfig.json
* In admin gui and user profile was fixed property in defaultConfig.json for supported languages.
=> Fix supported languages

angular.json
* fix Angular 12 CSS optimization inline event handler with Content
Security Policy
=> fix(perun-web-apps): fix of Angular 12 css optimalization

apps/user-profile/src/app/pages/profile-page/profile-page.component.ts
* Removed i/m option for preferred mail change in new profile
* New admin GUI did not have i/m option implemented
=> refactor(profile): remove deprecated preferred mail change methods

apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, package-lock.json
* added refresh button to vo and group members page
* table content is refresh with each change to filter value
=> Refresh member list

apps/user-profile/src/app/pages/groups-page/groups-page.component.html
* with commit to change the input from hideColumns to displayColumns a
extra semicolon appeared where it shouldnt
* this commit removes it
=> fix(user-profile): fix of user profile build

.github/workflows/lint.yml
* Enable ts lint for pull requests and pushes to master
=> ci(GithubCI): Enable ts lint

apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html
* The input for user search was in a label element, which was wrong.
=> fix(admin): Fix user search input width

apps/admin-gui/src/assets/config/defaultConfig.json, apps/publications/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/config/defaultConfig.json, libs/perun/services/src/lib/auth.service.ts
* If no idpFilter is specified, default idp filter is used
* Default filter is not shown in query parameters
=> feat(perun-web-apps): add default filter to idpFilter

apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts, libs/perun/openapi/src/lib/api/resourcesManager.service.ts, libs/perun/openapi/src/lib/api/usersManager.service.ts, libs/perun/openapi/src/lib/model/assignedResource.ts
* Resource tags were missing in this table
=> fix(admin): show resource tags for group's resources

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/tag-bar/tag-bar.component.ts, apps/admin-gui/src/assets/i18n/en.json
- Added notification tag {fromApp-itemName} with its description
to tag-bar component.
=> feat(admin): Notification tags from applications

apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/openapi/src/lib/api/resourcesManager.service.ts, libs/perun/openapi/src/lib/api/usersManager.service.ts
* Added option to assign group to resource a/synchronously
=> feat(admin): group to resource asynchronous assignment

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts
* method getAssignedGroups was returning all attributes because none was specified and that drastically decreased performance
* added one attribute to return so that the method doesnt return all attributes
=> perf(admin-gui): optimalization of assigned groups to resource

angular.json
* angular.json has been edited to support building the apps in dev mode by default
=> build: enabling dev mode

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/group-resource-status/group-resource-status.component.html, libs/perun/components/src/lib/group-resource-status/group-resource-status.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/components/src/lib/resources-list/resources-list.component.html, libs/perun/components/src/lib/resources-list/resources-list.component.ts, libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.html, libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.scss, libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.ts, libs/perun/dialogs/src/lib/perun-dialogs.module.ts
* group-resource assignment can be activated or deactivated from both group and resource lists
=> feat(admin): change status of group-resource assigment

apps/admin-gui/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/config/defaultConfig.json, libs/perun/services/src/lib/auth.service.ts
* removing default idpFilter from defaulConfig of user profile and admin
gui
=> fix: remove default idpFilter

apps/admin-gui/src/assets/config/defaultConfig.json, apps/publications/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/config/defaultConfig.json, libs/perun/components/src/lib/perun-footer/perun-footer.component.html, libs/perun/pipes/src/index.ts, libs/perun/pipes/src/lib/localised-link.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts
* Added support for localisation of URLs in the footer links
BREAKING CHANGE: in the footer config every "label" was renamed to "label_en"
=> feat: add multi-lang support for footer links

apps/admin-gui/src/app/shared/components/dialogs/create-edit-service-dialog/create-edit-service-dialog.component.html
* create-edit-service dialog was wider than the dialog and scrollbar
appeared
* this commit fixed this behaviour
=> fix(admin-gui): fix vision bug of create edit service dialog

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-assigned-members/resource-assigned-members.component.html, apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts, apps/admin-gui/src/app/shared/components/users-list/users-list.component.html, apps/admin-gui/src/app/shared/components/users-list/users-list.component.ts, apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.html, apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.ts, libs/perun/components/src/lib/facilities-list/facilities-list.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.css, libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html, libs/perun/components/src/lib/members-list/members-list.component.html, libs/perun/components/src/lib/members-list/members-list.component.scss, libs/perun/components/src/lib/members-list/members-list.component.ts, libs/perun/components/src/lib/resources-list/resources-list.component.ts, libs/perun/components/src/lib/vos-list/vos-list.component.ts, libs/perun/utils/src/lib/perun-utils.ts
* optimalizations of some tables rendering the items
=> perf(admin-gui): tables optimilizations

apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.ts
* on application detail group manager couldnt approve application
* this
was cause by the wrong parent params which failed the authorization
=> fix(admin-gui): fix of auth rights on application detail

libs/perun/dialogs/src/lib/bug-report-dialog/bug-report-dialog.component.ts, libs/perun/models/src/lib/RPCError.ts, libs/perun/services/src/lib/ApiInterceptor.ts
* when reporting error there was wrong format of the text
* payload of
the message is fixed and added full url to the error text
=> fix(admin-gui): fix of text when reporting error

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.scss, apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/tag-bar/tag-bar.component.scss, apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/tag-section/tag-section.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/tag-section/tag-section.component.scss, apps/admin-gui/src/assets/i18n/en.json
* aligned tags text
* changed tag text to be more visible
* moved hide/show button to the bottom of dialog
=> fix(admin-gui): Text style changes in notification editing dialog

.github/workflows/build.yml
* Added new workflow yml file for buld and eslint check for every pull request and push to this
repo.
=> ci(githubci): add test build and eslint check for all pull requests and pushes

apps/admin-gui/src/index.html, apps/admin-gui/src/styles.scss, apps/user-profile/src/index.html, apps/user-profile/src/styles.scss
* add new pre app loader to admin gui and user profile
=> feat: add preAppLoader to admin gui and user profile

apps/publications/src/app/app.component.ts, apps/publications/src/app/components/header/header.component.html, apps/publications/src/app/components/header/header.component.scss, apps/publications/src/app/components/header/header.component.ts, apps/user-profile/src/app/components/header/header.component.html, apps/user-profile/src/app/components/header/header.component.scss, apps/user-profile/src/app/components/header/header.component.ts
* Added "isDevel" configuration to user-profile and publications
* Fixed warning about expression check in publications
=> feat: add configuration "isDevel" to other applications

apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-service-to-resource-dialog/assign-service-to-resource-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/components/src/lib/service-package-search-select/service-package-search-select.component.html, libs/perun/components/src/lib/service-package-search-select/service-package-search-select.component.ts
* add-service-to-resource dialog now allows to add service packages
=> feat(admin): Add service package to resource

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts, libs/perun/utils/src/lib/perun-utils.ts
* Tooltip was added to all entities on dashboard and group tooltip was extended by VO name.
* This PR also fixes group tooltip when user has no recently visited object in local storage.
=> feat(admin): improve recently visited objects dashboard

apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.html, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
* Added option to specify alert text when attributes list is empty
=> feat: change alert text in attributes list

apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.ts, apps/admin-gui/src/assets/i18n/en.json
* Now if user wants to delete application, he/she needs to confirm it in confirmation dialog.
=> fix(admin): add confirmation dialog for application deletion

apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.ts, apps/admin-gui/src/assets/i18n/en.json
* service status info added to service detail
* service status can be changed by using the status icon
=> feat(admin): change service status from detail

apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
* two entity attributes component now preselects group based on context
* this functionality can be easily expanded to support different entities in the future
=> feat(admin): preselect group from context on two entity attributes

apps/admin-gui/src/app/app-routing.module.ts, apps/admin-gui/src/app/app.component.html, apps/admin-gui/src/app/app.component.ts, apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/login/src/index.ts, libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.css, libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.html, libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts, libs/perun/login/src/lib/perun-login.module.ts, libs/perun/services/src/lib/ApiInterceptor.ts, libs/perun/services/src/lib/auth.service.ts, libs/perun/services/src/lib/init-auth.service.ts
* Now is possible to access admin-gui via basic authentication. This type of authentication is
available on address "/service-access".
=> feat(admin): add support for Basic Auth

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts, libs/perun/openapi/src/lib/model/assignedMember.ts
* now any assignment status will add member to resource-member attributes page
* status of the assignment can be further used
=> fix(admin): show all members on resource-member attributes page

libs/perun/services/src/lib/auth.service.ts
=> feat(admin-gui): enable basic auth

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.ts
* fix of checking auth rights when checking the lifeness of entity in
recently viewed
=> fix(admin-gui): fix of checking auth rights in home page

apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/password-reset/password-reset.component.html, libs/perun/components/src/lib/password-reset/password-reset.component.ts, libs/perun/dialogs/src/lib/change-password-dialog/change-password-dialog.component.css, libs/perun/dialogs/src/lib/change-password-dialog/change-password-dialog.component.html, libs/perun/dialogs/src/lib/change-password-dialog/change-password-dialog.component.ts, libs/perun/dialogs/src/lib/perun-dialogs.module.ts
* added option to change password on selected namespace(if supported)
* added shared dialog for changing the password
=> feat(user-profile): change password

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-attributes/group-attributes.component.ts
* wrong policies used when getting attributes
* i merged https://github.com/CESNET/perun-web-apps/pull/846 PR then I realized that kuba forget to change the policies
=> fix(admin-gui): fix of policies when getting attributes

apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json
* during creation of service member, there is no longer displayed notification about password when user didn't set any password
* fixed text in filter on service members page
=> feat(admin): fixed notification when creating service member

apps/publications/src/app/components/side-menu/side-menu.component.html, apps/publications/src/app/services/side-menu-items.service.ts, apps/user-profile/src/app/components/side-menu/side-menu.component.html, libs/ui/material/src/lib/ui-material.module.ts
* add click animation to left menu to publications and user profile
=> fix: add mat ripple to publications and user profile

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.ts
* fixed infinite loading at dashboard buttons when user was not authorized to view a recently viewed entity
=> fix(admin): fix infinite loading at dashboard buttons

apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.ts, libs/perun/dialogs/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.html, libs/perun/dialogs/src/lib/edit-facility-resource-group-vo-dialog/edit-facility-resource-group-vo-dialog.component.ts
* group, resource and facility description restrictions were changed to match backend requirements
* removed length restriction and changed description to be optimal
=> feat(admin): fix enity description restrictions

apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.ts
* added missing switch case for user external source to create attribute dialog
=> fix(admin): adding new ues attributes

apps/admin-gui/src/app/shared/components/member-overview-membership/member-overview-membership.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.css, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.html, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.ts, libs/perun/dialogs/src/lib/change-group-expiration-dialog/change-group-expiration-dialog.component.html, libs/perun/dialogs/src/lib/change-group-expiration-dialog/change-group-expiration-dialog.component.ts, libs/perun/dialogs/src/lib/change-vo-expiration-dialog/change-vo-expiration-dialog.component.html, libs/perun/dialogs/src/lib/change-vo-expiration-dialog/change-vo-expiration-dialog.component.ts
* if a member is in 'EXPIRED' state, changing his/her expiration to a date in future or to 'never' now changes also member's status to 'VALID'
=> feat(admin): allow setting member expiration in future

libs/perun/components/src/lib/password-reset/password-reset.component.ts, libs/perun/components/src/lib/vos-list/vos-list.component.ts, libs/perun/dialogs/src/index.ts, libs/perun/dialogs/src/lib/perun-dialogs.module.ts, libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts, libs/perun/services/src/lib/api.service.ts, libs/perun/services/src/lib/perun-api-service.ts, package.json
* Fixed script to run the lint on all projects.
* In this PR are also fixed lint errors/warnings.
=> fix: run the lint on all projects

apps/admin-gui/src/assets/i18n/en.json, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts
* Disable deleting ues, which cannot be deleted.
* Fixed error in development mode - NG0100: Expression has changed after it was checked.
=> fix(lib): disable deleting persistent ues

apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/index.ts, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/components/src/lib/selection-item-search-select/selection-item-search-select.component.html, libs/perun/components/src/lib/selection-item-search-select/selection-item-search-select.component.ts
* created SelectItem search select component
* new component is used in application formular
=> feat(admin): add source/destination attribute search select

apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html, apps/admin-gui/src/assets/i18n/en.json
* beter caption of invite in language button
=> fix(admin-gui): beter caption of invite in language button

apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.ts
* empty description is send as empty string insead of null
=> fix(admin): create resource without description

apps/password-reset/src/app/app.module.ts
* password-reset now uses new oidc library
=> fix: password-reset app uses new oidc library

libs/perun/components/src/lib/password-reset/password-reset.component.ts
- Password change in a specific namespace is now addressable through
URL /profile/settings/passwordReset?namespace=namespace.
=> feat(profile): address change password through URL

apps/admin-gui/src/assets/config/defaultConfig.json, apps/password-reset/src/assets/config/defaultConfig.json, apps/publications/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/config/defaultConfig.json, libs/perun/services/src/lib/ApiInterceptor.ts, libs/perun/services/src/lib/auth.service.ts
* from implicit flow the default configuration is now code flow
* the
refreshing of access token is setup for code flow only
=> feat: migration from implicit flow to PKCE

libs/perun/namespace-password-form/src/lib/password-form/password-form.component.html, libs/perun/namespace-password-form/src/lib/password-form/password-form.component.scss
* when setting up a password, whole error message is now displayed
=> feat(admin): show whole error message when setting up a password

apps/password-reset/src/app/app.component.ts, apps/password-reset/src/app/services/password-reset-config.service.ts, apps/password-reset/src/assets/config/defaultConfig.json
* password-reset app now reacts to language and auth filter in url
=> feat: Set lang and auth filter in password-reset

apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.html, apps/admin-gui/src/assets/i18n/en.json
* fix when in init of the account page there was no organization
preselected, which caused some problems
* fixed margin of loading
spinners
* fixed behaviour when user has no organization
=> fix(admin): fix of user account page

apps/admin-gui/src/app/shared/components/users-list/users-list.component.html, apps/admin-gui/src/app/shared/components/users-list/users-list.component.ts, apps/admin-gui/src/assets/img/PerunWebImages/service_identity-black.svg, libs/perun/components/src/lib/users-dynamic-list/users-dynamic-list.component.html, libs/perun/components/src/lib/users-dynamic-list/users-dynamic-list.component.ts, libs/perun/services/src/lib/custom-icon.service.ts
* icons for service-identities change to robots
=> fix(admin): change of service-identity icon

apps/admin-gui/src/app/shared/components/dialogs/password-reset-request-dialog/password-reset-request-dialog.component.ts, libs/perun/openapi/src/lib/api/membersManager.service.ts
* Added parameter to method to allow address a new pwd reset app in email.
=> feat: address link to new pwd reset app in email message

apps/admin-gui/src/app/shared/components/dialogs/update-application-form-dialog/update-application-form-dialog.component.html
* put labels to input fields as placeholders
=> fix(admin): use placeholders in application settings dialog

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.scss
* object names at user dashboard are truncated if they are too long
=> feat(admin): shorten object names at dashboard

apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
* visual and control elements of pages with attributes settings were unified
* filter has been added to two-entity attribute pages
=> feat(admin): unify elements of attributes settings

apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts, apps/password-reset/src/app/services/password-reset-config.service.ts, apps/password-reset/src/assets/config/defaultConfig.json, apps/publications/src/app/app-routing.module.ts, apps/publications/src/app/app.component.html, apps/publications/src/app/app.component.ts, apps/publications/src/app/services/publications-config.service.ts, apps/publications/src/assets/config/defaultConfig.json, apps/publications/src/assets/i18n/en.json, apps/user-profile/src/app/app-routing.module.ts, apps/user-profile/src/app/app.component.html, apps/user-profile/src/app/app.component.ts, apps/user-profile/src/app/components/breadcrumbs/breadcrumbs.component.ts, apps/user-profile/src/app/services/user-profile-config.service.ts, apps/user-profile/src/assets/i18n/en.json, libs/config/src/lib/app-config.service.ts
* add support for basic auth to user profile
* add support for basic
auth to publications
* move method setApiUrl to common service
=> feat: add support for basic auth to user profile and publications

apps/admin-gui/src/app/users/pages/user-detail-page/user-identities/user-identities.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-identities/user-identities.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.html, libs/perun/components/src/lib/user-ext-sources-list/user-ext-sources-list.component.ts
* unification in terminology in user - Identity page
* also widened add
and remove dialog
* added filter to the page
=> fix(admin): Identity page unification

apps/admin-gui/src/assets/i18n/en.json
* unification of how we show the user label "Id" previously exsted "ID"
"id" "Id" and in the whole application we wanted in unified
* in tables
headers the column "id" was also not unified, this commit unifies the
labes of the table headers column "Id" from "Entity ID" -> "Id"
=> fix(admin): "Id" unification

apps/admin-gui/src/app/shared/components/audit-messages-list/audit-messages-list.component.ts, apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.scss, apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json
* Added "Actor" and "Created at" to this dialog.
* Added new tab for audit message and copy button to both tabs.
* JSON object syntax is now highlighted.
=> feat(admin): improve audit message detail component

apps/admin-gui/src/app/shared/components/dialogs/connect-identity-dialog/connect-identity-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/connect-identity-dialog/connect-identity-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/disconnect-identity-dialog/disconnect-identity-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/disconnect-identity-dialog/disconnect-identity-dialog.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-associated-users/user-settings-associated-users.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/user-settings-service-identities.component.ts, apps/admin-gui/src/assets/i18n/en.json
* several texts related to service account management were unified
=> feat(admin): service identity terminology unification

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.html, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-attributes/resource-attributes.component.ts
* fix loading of resource attributes
* due to unify page component
loading there was added bug of using unidentified variable
=> fix(admin): fix loading of resource attributes

apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html
* due to unify page component loading there was added bug when changing
group resource assigment status
=> fix(admin): fix loading of changing status of group-resource status

apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html, apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
* action buttons of stepper like "Back" were moved outside the stepper
=> feat(admin): improve UX of dialogs that use stepper

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/application-re-send-notification-dialog/application-re-send-notification-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/application-re-send-notification-dialog/application-re-send-notification-dialog.component.ts, apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.ts, apps/admin-gui/src/assets/i18n/en.json, package-lock.json
- Added new notification for users when their group application is
created and it can be approved (after the user becomes member in VO).
- This type of notification is only displayed for groups.
=> feat(admin): add new delayed group application notification

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts-detail/facility-hosts-detail.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-task-results/facility-task-results.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-task-results/facility-task-results.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-identities/user-identities.component.html
* fixed gaps between buttons in facility-host-detail and user-identity
components
* fixed console error on facility-task-results.component
* added mat-spinner to facility-hosts-detail.component.html
=> fix(admin): bugfixes of the visuals

apps/admin-gui/src/app/shared/components/identity-detail/identity-detail.component.html, apps/admin-gui/src/assets/i18n/en.json
* identity detail page filled with additional information about identity
the user is watching
people from Proxy requested this
=> feat(admin): identity detail page information extended

apps/user-profile/src/app/components/dialogs/add-ssh-dialog/add-ssh-dialog.component.html, apps/user-profile/src/app/components/dialogs/add-ssh-dialog/add-ssh-dialog.component.scss, apps/user-profile/src/app/components/dialogs/add-ssh-dialog/add-ssh-dialog.component.ts, apps/user-profile/src/app/pages/settings-page/settings-ssh-keys/settings-ssh-keys.component.ts, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json
* added info alert about all supported key formats
* improved validation of new SSH keys
=> fix(profile): adding SSH key fixed

apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts, apps/password-reset/src/app/components/password-reset-form/password-reset-form.component.ts, libs/perun/dialogs/src/lib/change-password-dialog/change-password-dialog.component.ts, libs/perun/utils/src/lib/custom-validators.ts
* changed parameters of method group(...) from FormBuilder to use it's non-deprecated variant
=> chore(admin): change deprecated method group(...) from FormBuilder

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.scss, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/advanced-filter/advanced-filter.component.html, libs/perun/components/src/lib/advanced-filter/advanced-filter.component.scss, libs/perun/components/src/lib/advanced-filter/advanced-filter.component.ts, libs/perun/components/src/lib/perun-components.module.ts
* Advanced filter according to prototype was added to section assigned users.
* Part of this new component is resuable, so it was placed to libs directory.
=> feat: advanced filter for assigned users

libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.html
* Fix width to 100% of parent form field width.
=> fix(lib): width of input fields for list attributes

libs/perun/components/src/lib/perun-footer/perun-footer.component.html, libs/perun/pipes/src/index.ts, libs/perun/pipes/src/lib/footer-logo-path.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts
* added possibility to set absolute/relative path when adding logos to footer
=> feat: allow absolute/relative paths to logos in footer

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.ts
* removed the name of the facility from the dialog title
=> feat(admin): dialog for adding hosts clean-up

apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html, apps/admin-gui/src/assets/i18n/en.json
* transfered disabled info from tooltip to input itself
=> fix(admin): login disabled info visible when creating service account

apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.html
* otherwise candidates won't show up in a table
=> fix(admin): use candidate name if richUser is not provided

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.html, apps/publications/src/app/pages/all-publications-page/all-publications-page.component.ts, apps/publications/src/app/pages/my-publications-page/my-publications-page.component.ts
* fixed refresh button removing filter in 'facility - allowed groups'
* fixed refresh button removing filter in 'VO - member - groups'
* fixed refresh button removing filter in 'VO - member - resources'
* fixed refresh button removing filter in 'all publications' and 'my publications'
=> fix(admin/publications) make refreshing not delete filter value

libs/perun/services/src/lib/auth.service.ts
* authentication flow tries to refresh access token so user doesn't need to sign-in again
=> feat: don't force sign-in on new tab

apps/admin-gui-e2e/cypress.json, apps/admin-gui-e2e/src/integration/group-management-perun_admin.spec.js, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-boolean/attribute-value-boolean.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-tree/groups-tree.component.html
* implemented e2e tests for group management
=> test(admin): e2e tests for group management

apps/password-reset/src/app/app.component.html, apps/password-reset/src/app/app.component.ts
* fixed initial position of footer in password reset app according to the monitor size
* fixed error in console regarding reading value from null object
=> fix(pwd-reset): fixed footer position in password-reset app

apps/admin-gui/src/app/shared/components/dialogs/create-vo-dialog/create-vo-dialog.component.scss, apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts
* In create vo dialog was unnecessary scroll bar which has been removed.
=> fix(admin): remove unnecessary scroll bar

apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.ts
* Application form item used to have yellow color also after refresh. This bug has been fixed.
=> fix(admin): application form item color

apps/publications/src/app/dialogs/add-category-dialog/add-category-dialog.component.ts, apps/user-profile/src/app/pages/settings-page/settings-mailing-lists/settings-mailing-lists.component.ts
* fix ts ignore anotation after prettier changes
=> fix: fix ts ignore anotation after prettier changes

apps/admin-gui/src/app/app.component.scss, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.scss
* changes dashboard min height to fill rest of view height
=> fix(admin): dashboard white stripe

apps/admin-gui/src/assets/i18n/en.json
* Fixed notification message, when attributes list is empty
=> fix(admin): Notification message bug

package-lock.json
Reverts CESNET/perun-web-apps#975
=> Revert "build(deps): bump follow-redirects from 1.13.0 to 1.14.8"

apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts
* Fixed broken links when loading subgroups
=> fix(admin): subgroup name bug

apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.html, apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.ts
* Required items in the application form items list and on preview are marked with a star.
=> fix(admin): add a star to required items

apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html, apps/admin-gui/src/assets/i18n/en.json
* Removed unnecessary stars next to required items. Also removed help text on the bottom of this
page.
=> fix(admin): required items on application detail page

libs/perun/components/src/lib/group-resource-status/group-resource-status.component.html, libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.html
* allowed group-resource status change from failed state
=> feat(admin): revalidate group resource assigment from failed state

apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html, apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.ts, apps/user-profile/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/services/src/lib/auth.service.ts
* added functionality to enforce MFA
=> feat(profile): enforce MFA

libs/perun/components/src/lib/groups-list/groups-list.component.ts
* fixed status tab error in Perun Admin Accounts
=> fix(admin): Fixed status tab in Accounts

libs/perun/services/src/lib/ApiInterceptor.ts
* when user is logged in and then doesnt use the web browser for some
time the browser operating system can put the browser to sleep so the
refresh of the tokens is not working
* when user then go back to the
browser and go to some page where there is multiple independent call to
rpc, multiple session expiration dialog appears and user must click to
"sing in" on all of them
* this fix ensures that the session expiration
dialog is opened only once
=> fix: session expiration dialog fix

apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.ts
* fixed infinite loading in Authentication page when MFA is not available for the user
=> fix(profile): fixed infinite loading in Authentication page

apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-overview/user-settings-overview.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-detail-page/service-identity-overview/service-identity-overview.component.ts, apps/admin-gui/src/assets/img/PerunWebImages/roles.svg, libs/perun/services/src/lib/custom-icon.service.ts
* on some overview we have same icons for different things - thats
something we dont want - this PR doesnt resolve this problem completely
(only partially)
* created new icon for roles
* changed some other icon to more appropriate icons
=> fix(admin): icon change on overviews

apps/admin-gui/src/app/admin/pages/admin-page/admin-owners/admin-owners.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html, apps/admin-gui/src/app/shared/components/add-owner-dialog/add-owner-dialog.component.html, libs/perun/components/src/lib/debounce-filter/debounce-filter.component.ts, libs/perun/login/src/lib/login-screen-base/login-screen-base.component.html
* page admin owners have correct theme set
* page admin users have autofocus set on input
* added shadow to header in the login screen
=> fix: minor improvements

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.html, libs/perun/components/src/lib/menu-buttons-field/menu-buttons-field.component.html
* removed directive from links causing to open 2 windows on wheel click
=> fix(admin): fix duplicate window open

libs/perun/services/src/lib/ApiInterceptor.ts, libs/perun/services/src/lib/auth.service.ts
* fix validity of access token
* fix storing the refresh token right after the login in
=> fix: fix refresh token

apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/connect-identity-dialog/connect-identity-dialog.component.html
* Text inputs have maximum width of form field
=> fix(admin): fixed text inputs

apps/admin-gui-e2e/src/integration/vo-management-perun_admin.spec.js
* fix of create vo e2e test
* after the tenant vo commit was merge the
e2e test were broken
=> fix(admin): fix create vo e2e test

apps/user-profile/src/app/app-routing.module.ts, apps/user-profile/src/app/app.module.ts, apps/user-profile/src/app/pages/settings-page/settings-local-account/settings-local-account.component.html, apps/user-profile/src/app/pages/settings-page/settings-local-account/settings-local-account.component.ts, apps/user-profile/src/app/pages/settings-page/settings-overview/settings-overview.component.ts, apps/user-profile/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/services/src/lib/other-applications.service.ts
* created new page in settings for local account management
* users can active account or change password (via password-reset app)
* based on user login existence in given namespace
=> feat(profile): Local account management page

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.ts
* information if destination is blocked/allowed was missing in this view
=> fix(admin): show destination status on facility service detail

apps/admin-gui/src/app/app.component.ts, apps/password-reset/src/app/app.component.ts, apps/publications/src/app/app.component.ts, apps/user-profile/src/app/app.component.ts
* fixed accesing of undefined footer on login pages
=> fix: undefined footer element

apps/publications/src/styles.scss
=> fix(publications): fix pre application loader

apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
* extended CSV output when generating sponsored members
* note, if present, is included in CSV output
=> feat(admin): generate sponsored members - note in CSV output

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.scss
* increased name length in tiles to 2 lines
=> feat(admin-gui): increased name length

apps/admin-gui/src/app/shared/components/consent-hubs-list/consent-hubs-list.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-required-attributes-dialog/add-required-attributes-dialog.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-member-organizations/add-member-organization-dialog/add-member-organization-dialog.component.html, libs/perun/components/src/lib/consents-list/consents-list.component.html, libs/perun/dialogs/src/lib/universal-confirmation-items-dialog/universal-confirmation-items-dialog.component.html
* We changed the alert selector due to eslint configuration, but at some places there was still the
wrong one.
=> fix(admin): wrong alert selector

apps/user-profile/src/app/components/dialogs/add-auth-img-dialog/add-auth-img-dialog.component.html, apps/user-profile/src/app/components/dialogs/add-auth-img-dialog/add-auth-img-dialog.component.scss, apps/user-profile/src/app/components/dialogs/add-auth-img-dialog/add-auth-img-dialog.component.ts, apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html, apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.scss, apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.ts, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json
shrink image down to 100x100 and try even smaller sizes up to 50x50 until the desired size is reached
Requires more work and testing.
=> feat(user-profile): downsize antiphishing images

apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts, libs/perun/services/src/lib/route-policy.service.ts
* added correct policy to the pages organization-members, group-members
=> fix(admin): fix policies for get members of vo/group

apps/user-profile/src/app/pages/settings-page/settings-mailing-lists/settings-mailing-lists.component.html, apps/user-profile/src/app/pages/settings-page/settings-mailing-lists/settings-mailing-lists.component.ts, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json
* The mailing lists segment of profile settings now allows routing via VO shortname / resource name
* By adding '/unsubscribe' or '/subscribe' user can quickly opt in and out of mailing list
* Added a notification when opting in/out
=> feat(profile): url routing based on selected vo/resource

libs/perun/utils/src/lib/perun-utils.ts
* due to fixing eslint error there were problems with exporting context
of table
=> fix(admin): fix export of table

apps/admin-gui/src/app/shared/components/settings-toggle-item/settings-toggle-item.component.ts, apps/admin-gui/src/app/vos/components/expiration-settings/expiration-settings.component.html, apps/admin-gui/src/app/vos/components/expiration-settings/expiration-settings.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-service-members/vo-settings-service-members.component.ts
* Service accounts page - fixed parameter which was broking loading of all this page.
* Membership page - fixed correct loading of initial values and fixed behavior while clicking on toggles.
=> fix(admin): bugfixes in vo section

apps/admin-gui/src/app/admin/pages/admin-page/admin-services/admin-services.component.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.ts, apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts, apps/admin-gui/src/app/shared/components/audit-messages-list/audit-messages-list.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-edit-service-dialog/create-edit-service-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/edit-enforce-consents-dialog/edit-enforce-consents-dialog.component.html, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-groups/user-groups.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts
* one bigger bug founded in page user-account
* the other are just 1 line improvements
=> fix(admin): Bugfixes of perun admin section

apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.ts, libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.ts
* Fixed advanced filter for facility allowed users.
* Added route cache for facility allowed users page.
* Fixed ExpressionChangedAfterItHasBeenCheckedError while removing last value from list attribute.
=> fix(admin): bugxifes in facility section

apps/admin-gui/src/app/shared/components/dialogs/move-group-dialog/move-group-dialog.component.ts, apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.html, apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.ts
* fixed moving group to top-level
* fixed expiration settings
* fixed error popping up when dynamic list of applications is empty
=> fix(admin): bugfixes in groups and member section

apps/admin-gui/src/app/admin/admin-routing.module.ts, apps/admin-gui/src/app/facilities/facilities-routing.module.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-overview/resource-overview.component.ts, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-settings/resource-settings-overview/resource-settings-overview.component.ts, apps/admin-gui/src/app/shared/route-auth-guard.service.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-overview/vo-resources-overview.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-overview/vo-settings-overview.component.ts, apps/admin-gui/src/app/vos/vos-routing.module.ts, libs/perun/services/src/lib/route-policy.service.ts
* Route authorization is now implemented in the whole admin gui.
* In member side menu and overview was replaced Vo object by Member object.
* In group overview was extended the setting policy by extsourcesAuth.
=> feat(admin): route policies for whole admin gui

apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts
* fix delete of vo from the select vo page
=> fix(admin): fix delete of vo

apps/admin-gui-e2e/src/integration/group-management-perun_admin.spec.js, apps/admin-gui-e2e/src/integration/vo-management-perun_admin.spec.js
=> test(admin): fix add member to vo/group

apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/user-settings-service-identities.component.ts
* fixed wrong check of userId on Service accounts page when accessing from My profile
=> fix(admin): fixed check of userId on Service accounts page

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.scss, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.ts, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts, libs/perun/openapi/src/lib/api/facilitiesManager.service.ts
* user can now filter resources by services that are assigned to those resources
requires that https://github.com/CESNET/perun/pull/3632 is merged into backend
=> feat(admin): add a service search filter on facility resources list

apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/urns/src/lib/perun-urns.ts
* display group status on User accounts page
* display group status on Member VO detail page
=> fix(admin): correctly display group status when listing groups for member

apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts
* fixed searching for users to be associated with service member
* fixed bug when it wasn't possible to create service member without specifying namespace
=> fix(admin): small bugfixes in create service member dialog

apps/user-profile/src/app/app.module.ts, apps/user-profile/src/app/components/dialogs/activate-local-account-dialog/activate-local-account-dialog.component.html, apps/user-profile/src/app/components/dialogs/activate-local-account-dialog/activate-local-account-dialog.component.ts, apps/user-profile/src/app/pages/settings-page/settings-local-account/settings-local-account.component.html, apps/user-profile/src/app/pages/settings-page/settings-local-account/settings-local-account.component.ts, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json
* local acount activation is performed in user-profile
* before this action had to be done in password-reset app
=> feat(profile): activate local account on profile

libs/perun/services/src/lib/perun-translate.service.ts
Create a new service that extends TranslateService.
=> feat(lib): create new translate service

apps/password-reset/src/app/components/header/header.component.html, apps/password-reset/src/app/components/header/header.component.scss, apps/publications/src/app/components/header/header.component.html, apps/publications/src/app/components/header/header.component.scss, apps/publications/src/index.html, apps/user-profile/src/app/pages/settings-page/settings-data-quotas/settings-data-quotas.component.html, apps/user-profile/src/app/pages/settings-page/settings-data-quotas/settings-data-quotas.component.scss, apps/user-profile/src/app/pages/settings-page/settings-ssh-keys/settings-ssh-keys.component.html, libs/perun/facility-services-config/src/lib/service-configurator/service-configurator.component.html, libs/perun/facility-services-config/src/lib/service-configurator/service-configurator.component.scss, libs/perun/login/src/lib/login-screen-base/login-screen-base.component.html, libs/perun/login/src/lib/login-screen-base/login-screen-base.component.scss
* inline styling has been removed from html files
=> fix: removed inline styling in html files

libs/config/src/lib/app-config.service.ts, libs/perun/models/src/index.ts, libs/perun/models/src/lib/ConfigProperties.ts, libs/perun/services/src/index.ts, libs/perun/services/src/lib/store.service.ts
* created new method `getProperty` in `StoreService`
* old method `get` is marked as deprecated
* created interfaces to represent config properties
=> feat: getter for typed config properties

apps/admin-gui/src/app/app.component.html, apps/admin-gui/src/app/app.component.scss, apps/admin-gui/src/app/app.module.ts, package-lock.json, package.json
* Library ngx-perfect-scrollbar has the last release (version 10.0.0) and it will not be updated
anymore, so it's recommended to replace this library with another library such as angular native
ngx-scrollbar.
* Ngx-scrollbar is now using insted of ngx-perfect-scrollbar and the ngx-perfect-scrollbar library has been uninstalled.
=> feat(admin): replace ngx-perfect-scrollbar by ngx-scrollbar

apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts, apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html, apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.scss, apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-roles/group-roles.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-roles/group-roles.component.ts, apps/admin-gui/src/app/vos/vos-routing.module.ts, apps/admin-gui/src/app/vos/vos.module.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/services/src/lib/route-policy.service.ts
* added page with group roles accessible via group detail
* refactored user-roles component and extracted common logic
=> feat(admin): add group roles page

apps/admin-gui-e2e/cypress.json, apps/admin-gui-e2e/src/integration/resource-management-perun_admin.spec.js, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html, apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/remove-group-from-resource-dialog/remove-group-from-resource-dialog.component.html, libs/perun/components/src/lib/resources-list/resources-list.component.html
Added e2e tests for resource management.
=> test(admin): e2e tests for resource management

apps/admin-gui-e2e/src/integration/perun-admin-management-perun_admin.spec.js, apps/admin-gui/src/app/admin/pages/admin-page/admin-attributes/admin-attributes.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/admin-services.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html, apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html, apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html, apps/admin-gui/src/app/shared/components/audit-messages-list/audit-messages-list.component.html, apps/admin-gui/src/app/shared/components/consent-hubs-list/consent-hubs-list.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-attribute-definition-dialog/create-attribute-definition-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-edit-service-dialog/create-edit-service-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-definition-dialog/delete-attribute-definition-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-user-dialog/edit-user-dialog.component.html, apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.html, apps/admin-gui/src/app/shared/components/services-list/services-list.component.html, apps/admin-gui/src/app/shared/components/users-list/users-list.component.html, libs/perun/components/src/lib/attribute-search-select/attribute-search-select.component.html, libs/perun/components/src/lib/debounce-filter/debounce-filter.component.html, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html, libs/perun/components/src/lib/immediate-filter/immediate-filter.component.html, libs/perun/components/src/lib/users-dynamic-list/users-dynamic-list.component.html
- Added e2e tests for PERUNADMIN.
=> test(admin): e2e tests for PERUNADMIN

apps/admin-gui-e2e/src/integration/perun-admin-management-perun_admin.spec.js
- DB data were changed in e2e-perun repository. Therefore, the e2e
tests need to be updated to use the new data.
=> fix(admin): update DB changes in e2e tests for PERUNADMIN

apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html, libs/perun/components/src/lib/facilities-list/facilities-list.component.html, libs/perun/components/src/lib/facilities-list/facilities-list.component.scss, libs/perun/components/src/lib/facilities-list/facilities-list.component.ts, libs/perun/components/src/lib/vos-list/vos-list.component.html, libs/perun/components/src/lib/vos-list/vos-list.component.scss
* Disable routing for membership entities, members are not allowed to see entity detail
=> fixup! feat(admin): show entities of membership role on user roles page

apps/admin-gui/src/app/shared/components/services-list/services-list.component.html, apps/admin-gui/src/app/shared/components/services-list/services-list.component.scss
* changed color of service status icons in tables (green for enabled and red for disabled)
=> feat(admin): changed service status color

libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
Reverts CESNET/perun-web-apps#1097
=> Revert "fix(admin): fixed a bug where checkboxes were disabled in group members page"

apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.ts
* fixed bug where MFA settings would be stuck on infinite loading after server error other than that user is logged in without MFA
=> fix(profile): fixed bug where MFA settings may be stuck on infinite loading

apps/user-profile/src/app/pages/identities-page/identities-page.component.ts, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/pipes/src/lib/get-mail-from-attributes.pipe.ts, libs/perun/urns/src/lib/perun-urns.ts
* Label identities changed to accounts accros user-profile.
* New column "mail" added to the table "Your linked accounts".
=> feat(profile): consolidator user testing feedback

apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json
* fix texts of remove account dialog
=> fix(user-profile): fix texts of remove account dialog

apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.html, apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.ts, apps/user-profile/src/assets/config/defaultConfig.json, libs/perun/models/src/lib/ConfigProperties.ts
* We can now hide detail settings for mfa via instanceConfig.
=> feat(profile): configurable mfa detail settings

apps/linker/src/app/app.module.ts, apps/linker/src/app/components/send-message-dialog/send-message-dialog.component.html, apps/linker/src/app/components/send-message-dialog/send-message-dialog.component.ts, apps/linker/src/app/components/show-result/show-result.component.ts, apps/linker/src/assets/i18n/en.json, apps/linker/src/styles.scss, libs/lib-linker/src/lib/consolidation-result/consolidation-result.component.html, libs/lib-linker/src/lib/consolidation-result/consolidation-result.component.ts
* Forkflow changed - when user tries to send message to user support, new dialog will be opened. In
this dialog is textarea with general message which can be changed by the user. This message will be merged with some technical info before sending to user support.
* Some texts were too.
=> feat(linker): consolidator user testing feedback

apps/linker/src/assets/config/defaultConfig.json, libs/perun/services/src/lib/auth.service.ts
* when we want to prompt login but we still want to do the offline
access then in the customQueryParams['prompt'] needs to be both 'login'
and 'prompt' so in the end the value needs to be 'prompt login'
=> fix(linker): fixed prompt

apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.html, apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.scss, apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.ts, package-lock.json
* Buttons which hide/show other toggles were not responsive for mobile devices.
* Refactor: deprecated parameters for subscribe method were replaced by recommended observer parameter.
=> style(profile): responsive design for detail mfa settings

apps/admin-gui-e2e/cypress.config.ts, apps/admin-gui-e2e/src/e2e/trusted-facility-admin-perun_admin.cy.js, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html, libs/perun/components/src/lib/group-resource-status/group-resource-status.component.html, libs/perun/components/src/lib/group-resource-status/group-resource-status.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.html
* Added e2e tests for the TRUSTEDFACILITYADMIN role.
=> feat(admin): e2e tests for TRUSTEDFACILITYADMIN

apps/admin-gui-e2e/cypress.config.ts, apps/admin-gui-e2e/src/e2e/group-management-group_observer.cy.js, apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.html, apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.html, apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.html, libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
=> feat(admin): e2e tests for GROUPOBSERVER

apps/admin-gui-e2e/cypress.config.ts, apps/admin-gui-e2e/src/e2e/facility-management-facility_observer.cy.js, apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html, apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, libs/perun/components/src/lib/owners-list/owners-list.component.html, libs/perun/components/src/lib/services-status-list/services-status-list.component.html, libs/perun/components/src/lib/task-results-list/task-results-list.component.html, libs/perun/pipes/src/lib/multi-word-data-cy.pipe.ts
* Added e2e tests for the role FACILITYOBSERVER.
=> feat(admin): e2e tests for FACILITYOBSERVER

apps/admin-gui-e2e/cypress.config.ts, apps/admin-gui-e2e/src/e2e/resource-observer-perun_admin.cy.js, apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.html
* Added e2e tests for the RESOURCEOBSERVER role
=> feat(admin): e2e tests for RESOURCEOBSERVER

apps/admin-gui-e2e/cypress.config.ts, apps/admin-gui-e2e/src/e2e/vo-observer-perun_admin.cy.js, apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-detail-page.component.html
* Added e2e tests for the VOOBSERVER role
=> feat(admin): e2e tests for VOOBSERVER

apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.ts
* service is now correctly saved on service detail page
* other pages on service detail can now get the service from entity storage
=> fix(admin): set service to entity storage service

apps/admin-gui/src/app/admin/pages/admin-page/admin-ext-sources/admin-ext-sources.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.ts, apps/admin-gui/src/assets/i18n/en.json
* added refresh button to notification pages (vo, group)
* refresh button on ext sources page was changed to be consistent
=> fix(admin): add missing refresh button

libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.html, libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
* changing page from bottom paginator scrolls user to top of table
=> feat(admin): scroll to top of table on page change

apps/admin-gui-e2e/cypress.config.ts, apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_observer.cy.js, apps/admin-gui/src/app/admin/pages/admin-page/admin-attributes/admin-attributes.component.html, apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html, apps/admin-gui/src/app/shared/components/audit-messages-list/audit-messages-list.component.html, apps/admin-gui/src/app/shared/components/dialogs/audit-message-detail-dialog/audit-message-detail-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-definition-dialog/edit-attribute-definition-dialog.component.html
- Added e2e tests for PERUNOBSERVER.
- Added 3 missing tests for PERUNADMIN as well.
- Fixed test 'change users name' in PERUN ADMIN tests.
=> feat(admin): e2e tests for PERUNOBSERVER

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.ts
* fixed a bug where the facility assigned resources table would refresh on page open
=> fix(admin): facility resources page double load

apps/admin-gui-e2e/cypress.config.ts, apps/admin-gui-e2e/src/e2e/sponsor-management-perun_admin.cy.js, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-member-sponsors-dialog/edit-member-sponsors-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/password-reset-request-dialog/password-reset-request-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html, apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.html, libs/perun/components/src/lib/members-list/members-list.component.html, libs/perun/namespace-password-form/src/lib/password-form/password-form.component.html
* Added e2e tests for the SPONSOR role
=> feat(admin): e2e tests for SPONSOR

apps/admin-gui/src/assets/config/defaultConfig.json, libs/perun/components/src/lib/perun-footer/perun-footer.component.html, libs/perun/components/src/lib/perun-footer/perun-footer.component.ts
* the footer contains information about latest backend version
=> feat(admin): show backend version

apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html, apps/admin-gui/src/app/shared/components/blacklist-list/blacklist-list.component.html, apps/admin-gui/src/app/shared/components/consent-hubs-list/consent-hubs-list.component.html, apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html, apps/admin-gui/src/app/shared/components/ext-sources-list/ext-sources-list.component.html, apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html, apps/admin-gui/src/app/shared/components/members-candidates-list/members-candidates-list.component.html, apps/admin-gui/src/app/shared/components/resources-tags-list/resources-tags-list.component.html, apps/admin-gui/src/app/shared/components/security-teams-list/security-teams-list.component.html, apps/admin-gui/src/app/shared/components/services-list/services-list.component.html, apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html, apps/admin-gui/src/app/shared/components/users-list/users-list.component.html, apps/admin-gui/src/app/vos/components/notification-list/notification-list.component.html, apps/publications/src/app/components/publications-list/publications-list.component.html, apps/publications/src/app/components/thanks-list/thanks-list.component.html, libs/perun/components/src/lib/attributes-list/attributes-list.component.html, libs/perun/components/src/lib/consents-list/consents-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/members-list/members-list.component.html, libs/perun/components/src/lib/owners-list/owners-list.component.html, libs/perun/components/src/lib/resources-list/resources-list.component.html, libs/perun/components/src/lib/services-status-list/services-status-list.component.html, libs/perun/components/src/lib/task-results-list/task-results-list.component.html
* We have this check in ngIf, but we want this ngIf to be always true, so the check should be wrapped as an object no just as a basic condition.
=> fix: broken isAllSelected check

apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.ts
* fixed infinite loader when form does not exist
=> feat(admin): fix non-existing form

apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-associated-users/user-settings-associated-users.component.ts
* Additional info such as email, logins and organization is shown on Account managers page of service user
=> feat(admin): Service user's managers details

apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts
* pages application and application form are not present on overview or side menu for group "members"
=> fix(admin): Hide application form for group members

angular.json, apps/admin-gui/src/app/shared/components/choose-sponsor/choose-sponsor.component.html, apps/admin-gui/src/app/shared/components/choose-sponsor/choose-sponsor.component.ts, apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html, apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-service-members/vo-settings-service-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/models/src/index.ts, libs/perun/models/src/lib/AuthPrivilege.ts, libs/perun/services/src/index.ts, libs/perun/services/src/lib/find-sponsors.service.ts, libs/perun/services/src/lib/gui-auth-resolver.service.ts
* New workflow - there is a new final step in creating the service account process. Now we allow users to sponsor a newly created service account directly in this workflow.
=> feat(admin): connect creating of the service account and sponsoring

apps/admin-gui/src/assets/config/defaultConfig.json, apps/password-reset/src/assets/config/defaultConfig.json, apps/user-profile/src/assets/config/defaultConfig.json
* default configs updated to contain newly added requirement for minimum password length (8 characters)
* CS version of messages were updated as well, if present
=> feat(gui): Minimum password length requirements messages added

apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/pipes/src/lib/group-checkbox-tooltip.pipe.ts, libs/perun/urns/src/lib/perun-urns.ts
* indirect member in group table in member profile section, no longer allows removal of indirect members
=> fix(admin): disable remove of indirect member in groups view

apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-definition-dialog/edit-attribute-definition-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-definition-dialog/edit-attribute-definition-dialog.component.scss, apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-definition-dialog/edit-attribute-definition-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json
* friendly name is visible in attribute edit
* added copy button for friendly name
=> fix(admin-gui): Friendly name is visible

apps/admin-gui/src/assets/config/defaultConfig.json, apps/password-reset/src/app/app-routing.module.ts, apps/password-reset/src/app/app.component.html, apps/password-reset/src/app/app.component.ts, apps/password-reset/src/app/app.module.ts, apps/password-reset/src/app/components/password-reset-form/password-reset-form.component.html, apps/password-reset/src/app/components/password-reset-form/password-reset-form.component.ts, apps/password-reset/src/app/pages/password-reset-page/password-reset-page.component.html, apps/password-reset/src/app/pages/password-reset-page/password-reset-page.component.ts, apps/password-reset/src/assets/config/defaultConfig.json, apps/password-reset/src/assets/i18n/en.json, apps/user-profile/src/assets/config/defaultConfig.json, libs/perun/login/src/lib/login-screen/login-screen.component.ts, libs/perun/models/src/lib/ConfigProperties.ts, libs/perun/namespace-password-form/src/lib/password-form/password-form.component.ts, libs/perun/services/src/index.ts, libs/perun/services/src/lib/error-translate.service.ts, libs/perun/services/src/lib/init-auth.service.ts
* added password labels to configuration
* changed password help to map
* allowed service access for pwd reset
=> feat(pwd-reset): configurable labels

libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.html, libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts
* Service access form can be submited by pressing enter on either field
=> feat: Submit service access with enter key

apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts, apps/password-reset/src/assets/i18n/cs.json, apps/password-reset/src/assets/i18n/en.json, apps/user-profile/src/assets/i18n/cs.json, libs/perun/services/src/lib/ApiInterceptor.ts
* When invalid access token occurs (for example revoked token), then new dialog with better information is opened. In this dialog is also "Sign in" button which start authentication flow.
=> feat: reaction on invalid access token

apps/admin-gui-e2e/src/e2e/facility-management-facility_observer.cy.js, apps/admin-gui-e2e/src/e2e/facility-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/group-management-group_observer.cy.js, apps/admin-gui-e2e/src/e2e/group-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_observer.cy.js, apps/admin-gui-e2e/src/e2e/resource-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/resource-observer-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/resource-self-service-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/sponsor-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/top-group-creator-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/trusted-facility-admin-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/vo-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/vo-observer-perun_admin.cy.js, apps/admin-gui/src/app/shared/side-menu/side-menu.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.html, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html, libs/perun/components/src/lib/notification/notification.component.html
=> fix(admin): e2e repair

apps/admin-gui/src/app/shared/components/dialogs/create-attribute-definition-dialog/create-attribute-definition-dialog.component.ts, libs/perun/models/src/lib/AttributeForm.ts
* otherwise creating array attribute fails
=> fix(admin): use correct type for attribute definitions

apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.css, libs/perun/pipes/src/lib/select-application-link.pipe.ts
* Fixed incorrect if condition.
* Added class for pointer in application-dynamic-list component.
=> fixup! fix(admin): open the correct new window after the mouse middle click

apps/admin-gui/src/app/shared/components/assign-groups-sponsored-members/assign-groups-sponsored-members-component.html, apps/admin-gui/src/app/shared/components/assign-groups-sponsored-members/assign-groups-sponsored-members-component.scss, apps/admin-gui/src/app/shared/components/assign-groups-sponsored-members/assign-groups-sponsored-members-component.ts, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/groups-list/groups-list.component.html
* user can now assign groups while creating sponsored member
* refactored the group assignment step of the dialog
=> feat(admin) add group assignment to create sponsored member dialog

apps/user-profile/src/app/app.component.ts, apps/user-profile/src/assets/i18n/cs.json
* czech localization for service access page was added to user profile
=> fix(profile): Service access page localization

libs/perun/components/src/lib/perun-footer/perun-footer.component.ts, libs/perun/models/src/lib/ConfigProperties.ts
* service access now displays server version in the footer
*  copyright items are correctly shown
=> fix(admin): fix footer

apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html, apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.ts, apps/admin-gui/src/assets/i18n/en.json
* new icon is displayed if user has been anonymized
* buttons for anonymization and edit are disabled is user has been anonymized
=> feat(admin): user detail page updated to show anonymization status

apps/admin-gui/src/app/users/pages/user-detail-page/user-bans/user-bans.component.ts
* the order of ban tabs is correctly assumend
=> fix(admin): user ban tabs correct order

apps/admin-gui/src/app/app.component.html, apps/admin-gui/src/app/app.component.ts, apps/admin-gui/src/assets/i18n/en.json, apps/consolidator/src/assets/i18n/en.json, apps/linker/src/assets/i18n/en.json, apps/password-reset/src/assets/i18n/cs.json, apps/password-reset/src/assets/i18n/en.json, apps/publications/src/assets/i18n/en.json, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/header-menu/header-menu.component.html, libs/perun/models/src/index.ts, libs/perun/models/src/lib/HttpResponseError.ts, libs/perun/services/src/lib/ApiInterceptor.ts, package-lock.json
* Session expiration dialog now does not show with 'invalid_token'
* fixed app undefined behaviour when the token expires
* Dialog now informs, that the user need to log in
* Updated czech translations
=> feat(admin): remove unnecessary login dialog

.github/workflows/build.yml, .github/workflows/release.yml
* will resolve current release action warnings
=> ci: update semantic release version

apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-group-role-dialog/add-group-role-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-user-role-dialog/add-user-role-dialog.component.ts, apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html, apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/index.ts, libs/perun/components/src/lib/groups-list/groups-list.component.ts, libs/perun/pipes/src/index.ts, libs/perun/pipes/src/lib/extract-facility.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts, libs/perun/pipes/src/lib/to-enriched-facility.pipe.ts
* pipes for transforming between EnrichedFacility and Facility created
* admin can select multiple objects for user/group to gain roles/lose roles in
* searching of objects supported
=> feat(admin): user/group can have (un)set roles as a bulk operation

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.ts
* resources were not loaded in ngOnInit() method
=> fix(admin): resources are loaded on resources detail page for facility

apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.ts
* usage of filterValue replaced by filter in add-role-dialog
* redundant filterValue Input removed
* redundant methods from groups-list component removed
=> fix(admin): do not loop in vo groups reloading

apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-dialog/add-member-dialog.component.ts, apps/admin-gui/src/app/vos/components/add-member.service.ts, apps/admin-gui/src/app/vos/components/group-add-member-dialog/group-add-member-dialog.component.html, apps/admin-gui/src/app/vos/components/group-add-member-dialog/group-add-member-dialog.component.ts, apps/admin-gui/src/app/vos/components/vo-add-member-dialog/vo-add-member-dialog.component.html, apps/admin-gui/src/app/vos/components/vo-add-member-dialog/vo-add-member-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/openapi/src/lib/api/membersManager.service.ts, libs/perun/openapi/src/lib/api/registrarManager.service.ts, libs/perun/openapi/src/lib/model/inputAddMemberCandidates.ts, libs/perun/openapi/src/lib/model/inputInviteMemberCandidates.ts
- add members to vo/group
- invite members to vo/group
=> feat(admin): member candidates bulk operations

apps/password-reset/src/app/services/password-reset-config.service.ts
* not loading apps config caused 'brands' variable to be undefined resulting in Error (manifested in console)
=> fix(apps): Apps config were lot loaded

apps/admin-gui/src/app/shared/components/dialogs/add-user-ext-source-dialog/add-user-ext-source-dialog.component.scss, apps/admin-gui/src/styles.scss, apps/consolidator/src/styles.scss, apps/user-profile/src/app/pages/settings-page/settings-overview/settings-overview.component.scss, libs/perun/dialogs/src/lib/add-ssh-dialog/add-ssh-dialog.component.scss, libs/perun/dialogs/src/lib/change-expiration-dialog/change-expiration-dialog.component.scss, libs/perun/dialogs/src/lib/request-change-data-quota-dialog/request-change-data-quota-dialog.component.scss, libs/perun/namespace-password-form/src/lib/password-form/password-form.component.scss
* dealt with mdc-migration TODOs
* a lot of the comments related to unused styles, deleted those
* only issues with the comments were fixed, there a lot more related issues that will be fixed in other commits
=> fix: fix TODO mdc-migration notes

libs/perun/services/src/lib/notificator.service.ts
* To the notificator service were added two new methods (showInstantError and showInstantSuccess).
* These methods manage translation of the notification (title, description and action text).
=> feat: added new method to notificator which manage translation of notification

apps/admin-gui/src/styles.scss, apps/consolidator/src/styles.scss, apps/linker/src/styles.scss, apps/password-reset/src/styles.scss, apps/publications/src/styles.scss, apps/user-profile/src/styles.scss
* as for TODO(V15) comments, only includes were automatically added
=> feat(apps): remove redundant comments and TODO(v15) comments

apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/audit-log-search-select/audit-log-search-select.component.html, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts, libs/perun/components/src/lib/facility-search-select/facility-search-select.component.html, libs/perun/components/src/lib/facility-search-select/facility-search-select.component.ts, libs/perun/components/src/lib/resource-search-select/resource-search-select.component.html, libs/perun/components/src/lib/resource-search-select/resource-search-select.component.ts
* fixed AddMemberToResource dialog where we were still using plain mat-selects instead of our custom search selects
=> fix(admin): replace mat-selects by our custom search selects

apps/admin-gui/src/app/vos/components/applications-dynamic-list/applications-dynamic-list.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/date-range/date-range.component.html, libs/perun/components/src/lib/date-range/date-range.component.ts
* picking date range using 2 date pickers has been replaced by single date-range component from Angular material
=> refactor(admin): use date-range component from Angular material

apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.ts, libs/perun/components/src/index.ts, libs/perun/components/src/lib/application-state-selector/application-state-selector.component.html, libs/perun/components/src/lib/application-state-selector/application-state-selector.component.ts, libs/perun/components/src/lib/perun-components.module.ts, package-lock.json
* logic for filtering applications to VOs and groups has been moved to separate component
=> refactor(admin): move application state selection into separate component

apps/publications/src/app/services/publications-config.service.ts, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json
* added translations for table exporting in user-profile app
* apps config is now loaded correctly in publications app to avoid exceptions
=> fix: bug fixes after angular 15 migration

apps/admin-gui/src/app/app.component.html, apps/admin-gui/src/app/app.component.ts, apps/user-profile/src/app/app.component.html, apps/user-profile/src/app/app.component.ts, libs/perun/services/src/lib/ApiInterceptor.ts
* login page is correctly displayed after session expiration
=> fix(profile): login page is correctly displayed after session expiration

apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/authorized-groups-cell/authorized-groups-cell.component.html, libs/perun/components/src/lib/authorized-groups-cell/authorized-groups-cell.component.scss, libs/perun/components/src/lib/authorized-groups-cell/authorized-groups-cell.component.ts, libs/perun/components/src/lib/facilities-list/facilities-list.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/perun-components.module.ts, libs/perun/components/src/lib/resources-list/resources-list.component.html, libs/perun/components/src/lib/vos-list/vos-list.component.html, libs/perun/components/src/lib/vos-list/vos-list.component.ts
* the column now contains ALL the groups the role is acquired through
* changed the header to 'Role acquired through' and made it the last column in the table to make the table easier to understand
=> feat(admin): extended the authorized group column in roles page list

apps/admin-gui/src/assets/i18n/en.json, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/components/src/lib/settings-ssh-keys/settings-ssh-keys.component.html, libs/perun/components/src/lib/settings-ssh-keys/settings-ssh-keys.component.ts
=> feat(profile): remove the option to add admin ssh key

color-migration.js
* fixed error with luminance, removed usage of color.isLight() when computing contrast
* Using contrast and luminance equations to pick the correct contrast value.
=> fix(admin):color migration luminance fix

apps/admin-gui/src/_styles.scss, apps/consolidator/src/_styles.scss, apps/linker/src/_styles.scss, apps/publications/src/_styles.scss, libs/perun/components/src/lib/deselect-button/deselect-button.component.scss, libs/perun/components/src/lib/refresh-button/refresh-button.component.scss
* fixed color mismatch of icons in service account tiles
=> fix(admin): icon color mismatch

libs/perun/components/src/lib/password-reset/password-reset.component.ts
* changed service password reset table to use reset instead of change
=> feat(admin): service accounts password reset

libs/perun/dialogs/src/lib/expiration-select/expiration-select.component.ts
* fixed a bug where if no max/min date values were passed, the component returned null date
=> fix(admin): fixed bug in expiration-select

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.ts, libs/perun/openapi/src/lib/api/servicesManager.service.ts
Used bulk operations for forcing propagation, blocking, and unblocking services.
=> fix(admin): services status bulk operations

apps/admin-gui/src/_styles.scss, apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html, apps/consolidator/src/_styles.scss, apps/publications/src/_styles.scss, apps/user-profile/src/_styles.scss, libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.css, libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.html, libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
* all tables now have a maximum height set and their scrollbar
* headers are sticky
* removed redundant extra div in attr def list, which caused some issues
=> feat: make table headers sticky and tables scrollable

apps/admin-gui/src/app/admin/pages/admin-page/admin-searcher/admin-searcher.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-searcher/admin-searcher.component.ts, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/admin-services.component.ts
* refactored calling of methods in searcher
* fixed double load on services page init
=> refactor(admin): minor refactoring in the admin pages

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts-detail/facility-hosts-detail.component.html, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts-detail/facility-hosts-detail.component.ts, apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.ts, apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html, apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.ts
* removed double load of the facility entity
* added pointer cursor to the hosts list
* used one-entity-attribute-page.component on the hosts detail page
=> fix(admin): minor fixes to facility hosts page

apps/admin-gui-e2e/cypress.config.ts, apps/admin-gui-e2e/src/e2e/facility-management-facility_observer.cy.js, apps/admin-gui-e2e/src/e2e/facility-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/group-management-group_observer.cy.js, apps/admin-gui-e2e/src/e2e/group-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/perun-admin-management-perun_observer.cy.js, apps/admin-gui-e2e/src/e2e/resource-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/resource-observer-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/resource-self-service-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/sponsor-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/top-group-creator-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/trusted-facility-admin-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/vo-management-perun_admin.cy.js, apps/admin-gui-e2e/src/e2e/vo-observer-perun_admin.cy.js, apps/admin-gui-e2e/src/index.d.ts, apps/admin-gui-e2e/src/support/commands.ts
Added and used new custom command for login.
=> feat(admin): e2e login command

.eslintrc.json, libs/perun/services/src/lib/html-escape.service.ts
* added no-unused-vars to throw error when unused variable appears in the code
=> build: update eslint config

libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.html, libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
Removed div containging the bottom pagination
=> fix(lib): do not display bottom pagination in tables

libs/perun/components/src/lib/group-menu/group-menu.component.html, libs/perun/components/src/lib/group-menu/group-menu.component.scss
* Removed horiz_right class and its only application
* Added flex to buttons-container class and removed nowrap and width that I found no longer needed
=> fix(lib): fix group list icons alignment and margin

apps/admin-gui/src/app/shared/components/assign-groups-sponsored-members/assign-groups-sponsored-members-component.html, apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/copy-members-dialog/copy-members-dialog-component.html, apps/admin-gui/src/app/shared/components/dialogs/copy-sponsored-members-dialog/copy-sponsored-members-dialog.component.html
Removed occurrences of immediate filter which does not exist anymore.
=> fix(admin): removed immediate filter

apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.html, package-lock.json
* Just a quick fix according to the behavior of drop-down menu button.
* All buttons are now disabled during the loading so there is no longer the broken behavior of related dialogs - e.g. dialog for copy members didn't display any sponsors, because they were not fully loaded in the parent component.
=> fix(admin): disable buttons until the sponsors are not loaded

libs/perun/components/src/lib/header-menu/header-menu.component.html, libs/perun/components/src/lib/header-menu/header-menu.component.scss
* Changed flex-wrap: wrap to nowrap
* Replaced align-elements class with bootstrap classes
=> fix(lib): fix unresponsive layout of perun header

apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts
* custom form control variables created for each field in each language used
* fixed console error when undefined value was added into sourceAttributes/destinationAttributes array when corresponding attribute had not been found
* inputs for adding new options separated from the rest of form group
=> fix(admin): application form items i18n correctly displayed

apps/admin-gui/src/app/admin/pages/admin-page/admin-audit-log/admin-audit-log.component.html, apps/admin-gui/src/app/admin/pages/admin-page/admin-blocked-logins/admin-blocked-logins.component.html, apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/applications-list-columns-change-dialog/applications-list-columns-change-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/block-logins-dialog/block-logins-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.ts, libs/perun/components/src/lib/audit-log-search-select/audit-log-search-select.component.html, libs/perun/components/src/lib/audit-log-search-select/audit-log-search-select.component.ts, libs/perun/components/src/lib/deselect-button/deselect-button.component.html, libs/perun/components/src/lib/deselect-button/deselect-button.component.ts, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html, libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts, libs/perun/components/src/lib/namespace-search-select/namespace-search-select.component.ts, libs/perun/components/src/lib/string-search-select/string-search-select.component.html, libs/perun/components/src/lib/string-search-select/string-search-select.component.ts
Deselect button was disabled in places where it was not needed.
=> fix(admin): disable deselect button

angular.json, apps/admin-gui/src/app/shared/components/dialogs/add-group-to-group-registration/add-group-to-group-registration.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-to-group-registration/add-group-to-group-registration.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-group-to-registration/add-group-to-registration.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-to-registration/add-group-to-registration.component.ts, apps/admin-gui/src/app/shared/components/dialogs/add-group-to-vo-registration/add-group-to-vo-registration.component.html, apps/admin-gui/src/app/shared/components/dialogs/add-group-to-vo-registration/add-group-to-vo-registration.component.ts, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.ts, apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.html, apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.ts, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-manage-embedded-groups/group-settings-manage-embedded-groups.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-manage-embedded-groups/group-settings-manage-embedded-groups.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-manage-embedded-groups/vo-settings-manage-embedded-groups.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-manage-embedded-groups/vo-settings-manage-embedded-groups.component.ts, apps/admin-gui/src/app/vos/vos-routing.module.ts, apps/admin-gui/src/app/vos/vos.module.ts, libs/perun/openapi/src/lib/api/groupsManager.service.ts, libs/perun/openapi/src/lib/api/registrarManager.service.ts, package-lock.json, package.json, tsconfig.base.json
* Managing of embedded groups for embedded form items in group form is now available.
* The backend part was chaged, so new methods for get/add/remove are used.
* Managing in vo form was also refactored to avoid code duplication.
=> feat(admin): allow managing embedded groups also in a group form settings

apps/admin-gui/src/_styles.scss
* Added min-width and min-height attribute to perun-icon class, which solves not only disappearing icons on entity detail, but throughout admin-gui
=> fix(admin): fix disappearing icons

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.html
The remove button is disabled after refreshing the list of services status.
=> fix(admin): disable remove button

apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.html, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/vo-search-select/vo-search-select.component.html, libs/perun/components/src/lib/vo-search-select/vo-search-select.component.ts
Auto select of VO in create-resource-dialog was disabled.
=> fix(admin): disable auto select of vo

apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.ts
Enabled to generate multiple hosts at once via range.
=> fix(admin): add host dialog fixed

libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.html, libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts, libs/perun/services/src/lib/auth.service.ts, libs/perun/services/src/lib/init-auth.service.ts
* service-access login component no longer shows sidebar and header after logout
* added logout notification so it is consistent with regular login
=> fix(admin): fix login screen service access component

libs/perun/services/src/lib/ApiInterceptor.ts, libs/perun/services/src/lib/auth.service.ts, libs/perun/services/src/lib/mfa-handler.service.ts
* If the MfaTimeoutError is thrown by backend, then we should force new authentication included first factor and second factor
=> fix: correctly handle MFA timeout

libs/perun/services/src/lib/ApiInterceptor.ts, libs/perun/services/src/lib/mfa-handler.service.ts
* We want to catch this specific exception and according to it hide cancel button in step-up dialog and also force authentication with both factors.
=> fix(lib): handle MfaRoleTimeoutException

apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.html
* Button does not require additional action and so the ellipses was removed
=> fix(profile): Remove ellipses from save mfa button

libs/perun/utils/src/lib/perun-utils.ts
Added option for displaying 1000 items at one page of table.
=> feat(admin): 1000 items in table

libs/perun/services/src/lib/notificator.service.ts
Extended and unified time of displaying notification.
=> fix(admin): notification display time

apps/admin-gui/src/app/app.component.scss
* scrollbar in side menu is now transparent
=> fix(admin): transparent scrollbar

apps/admin-gui/src/_styles.scss, apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html, libs/perun/components/src/lib/attribute-critical-operations-toggles/attribute-critical-operations-toggles.component.html
* added bigger gap under the toggles
=> fix(admin): adjusted spacing between toggles

apps/admin-gui/src/_styles.scss, libs/perun/components/src/lib/group-resource-status/group-resource-status.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.html, libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html, libs/perun/components/src/lib/members-list/members-list.component.html
* Created new class status-change in styles.scss definging circular background that highlights on hover
* Added this new class to appropriate places
=> feat(admin): add feedback on hover to member status

apps/admin-gui/src/_styles.scss, apps/password-reset/src/_styles.scss, apps/publications/src/_styles.scss, apps/user-profile/src/_styles.scss
* Added light gray background to active mat-tab.
=> fix: add background to active tab

libs/perun/components/src/lib/header-menu/header-menu.component.html, libs/perun/components/src/lib/perun-header/perun-header.component.html, libs/perun/components/src/lib/perun-header/perun-header.component.scss
Logout button was moved out of drop-down menu.
=> fix(admin): logout button with icon

libs/perun/services/src/lib/mfa-handler.service.ts
* Fixed incorrect logical operation.
=> fix(lib): mfaTimeoutException check

apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
Correctly refresh managers when coming back from other group detail.
=> fix(admin): refresh group managers

apps/admin-gui/src/app/app.component.html, apps/admin-gui/src/app/app.component.scss, apps/admin-gui/src/app/app.component.ts, libs/perun/services/src/lib/mfa-handler.service.ts
* removed sign-in page when step-up window is opened
=> feat(admin): remove step-up window sign-in page

libs/perun/services/src/lib/mfa-handler.service.ts
Step-up mfa window is responsive.
=> fix(admin): responsive mfa window

apps/admin-gui/src/app/shared/components/choose-sponsor/choose-sponsor.component.html, apps/admin-gui/src/app/shared/components/choose-sponsor/choose-sponsor.component.ts, apps/admin-gui/src/app/shared/components/dialogs/copy-sponsored-members-dialog/copy-sponsored-members-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/sponsor-this-member-dialog/sponsor-this-member-dialog.component.ts, apps/admin-gui/src/app/shared/components/dialogs/sponsor-this-member-dialog/sponsor-this-member-dialog.components.html, apps/admin-gui/src/app/shared/shared.module.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-overview/member-overview.component.ts, apps/admin-gui/src/assets/i18n/en.json
Enable sponsor members from their profile.
=> feat(admin): sponsor this member

.commitlintrc.json, .github/workflows/check.yml, .github/workflows/release.yml, .releaserc.json, README.md, package-lock.json, package.json
* added check.yml workflow
* added .commitlintrc.json with specific rules
* changed README.md for consistency
=> ci: upgrade notes

.releaserc.json
=> ci: commit release notes

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.ts, apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.html, apps/admin-gui/src/app/shared/components/destination-list/destination-list.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/openapi/src/lib/model/richDestination.ts, libs/perun/pipes/src/index.ts, libs/perun/pipes/src/lib/last-successful-propagation.pipe.ts, libs/perun/pipes/src/lib/perun-pipes.module.ts
Added column with time of last successful propagation into destinations table.
=> feat(admin): last successful propagation

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/tag-section/tag-section.component.html, apps/admin-gui/src/assets/i18n/en.json
- Added icon button for adding tag.
- Edited description of tag.
=> fix(admin): tag section

libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
* filter of attributes with empty object failed at null/undefined value
=> fix(admin): filter attributes with empty objects

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.ts
* added binding to reflect change when user inputs data in notification
=> fix(admin): notification values not saved

apps/admin-gui/src/_styles.scss, apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.scss, apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.scss, apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.scss, apps/consolidator/src/_styles.scss, apps/linker/src/_styles.scss, apps/password-reset/src/_styles.scss, apps/publications/src/_styles.scss, apps/user-profile/src/_styles.scss, libs/lib-linker/src/lib/consolidation-result/consolidation-result.component.html, libs/perun/components/src/lib/groups-list/groups-list.component.scss, libs/perun/components/src/lib/menu-buttons-field/menu-buttons-field.component.scss, libs/perun/components/src/lib/notification/notification.component.html, libs/perun/components/src/lib/vos-list/vos-list.component.scss, libs/ui/alerts/src/lib/alert/alert.component.css
* added rounded design for buttons, dialogs, tables...
* updated _styles.scss, to include the changes
=> feat: rounded design for components

apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
* ordering of side menu items is correct even for async added items
=> fix(admin): side menu async items ordering

apps/user-profile/src/assets/i18n/cs.json
* There were missing texts in Czech language for the new Authenticatoin section.
=> fix(profile): add CS translation to the Authentication section

apps/admin-gui/src/assets/i18n/en.json, apps/publications/src/assets/i18n/en.json, apps/user-profile/src/assets/i18n/cs.json, apps/user-profile/src/assets/i18n/en.json, libs/perun/utils/src/index.ts, libs/perun/utils/src/lib/export-table-dialog/export-table-dialog.component.html, libs/perun/utils/src/lib/export-table-dialog/export-table-dialog.component.ts, libs/perun/utils/src/lib/perun-utils.module.ts, libs/perun/utils/src/lib/table-options/table-options.component.html, libs/perun/utils/src/lib/table-options/table-options.component.ts
* replaced mat-menu with a dialog
* functionally it works the same
=> feat(admin): replaced old table export

apps/admin-gui-e2e/src/e2e/admin/perun-admin.cy.js, apps/admin-gui-e2e/src/e2e/admin/perun-observer.cy.js, apps/admin-gui/src/app/admin/pages/admin-page/admin-blocked-logins/admin-blocked-logins.component.html, apps/admin-gui/src/app/shared/components/dialogs/block-logins-dialog/block-logins-dialog.component.html, apps/admin-gui/src/app/shared/components/dialogs/unblock-logins-dialog/unblock-logins-dialog.component.html, libs/perun/components/src/lib/blocked-logins-dynamic-list/blocked-logins-dynamic-list.component.html
Added e2e tests for blocked logins page.
=> test(admin): e2e tests for blocked logins

libs/perun/components/src/lib/expandable-tiles/expandable-tiles.component.html
A section is expanded also after clicking on the title not only the icon.
=> fix(admin): expand section

apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.html
* Fix action-buttons where the icon inside was misaligned
* Buttons in the group application form changed to be consistent with VO
* Settings button in VO application form aligned to be consistent with group
=> fix(admin): missaligned icons in action-buttons

renovate.json
* Renovate Github app needs to be enabled for this repo
* PRs by dependabot need to be disabled (but keep vulnerability alerts enabled, renovate will read them)
=> ci: config for renovate

renovate.json
* Property 'minimumReleaseAge' muset be a string instead of number.
* Last comma removed from extends array.
=> fixup! ci: config for renovate

apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html, apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts, apps/admin-gui/src/app/vos/pages/member-detail-page/member-resources/member-resources.component.ts
Authz of buttons is checked independently of data loading.
=> fix(admin): buttons authz on member pages

apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-detail-page/service-identity-overview/service-identity-overview.component.html, apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-detail-page/service-identity-overview/service-identity-overview.component.ts, libs/perun/components/src/lib/expandable-tiles/expandable-tiles.component.html
* empty sections are not shown
* authentication section under service account was reworked to be expandable
=> feat(admin): hide empty expandable sections

apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/openapi/src/lib/api/registrarManager.service.ts
* Invite button will be disabled if 'isInvitationEnabled' returns false.
* Invitation is enabled if invitation notification exists, application form exists and application can be sumbited - submin/auto-submit button exists in the form.
=> feat(admin): disable member invitation

apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.html, apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.html, apps/admin-gui/src/app/shared/components/one-entity-attribute-page/one-entity-attribute-page.component.ts, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html, apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts, apps/admin-gui/src/assets/i18n/en.json, libs/perun/components/src/lib/attributes-list/attributes-list.component.ts
Filtering of attributes with empty values from table was removed. It is most likely not wanted anywhere and caused problem when adding new attribute.
=> fix: do not filter attributes with empy value

libs/perun/components/src/lib/settings-mailing-lists/mailing-lists.component.ts
Fixed a problem of getting stuck in the mailing lists settings. When navigating away from the component it clears the query params and replaces the old url. The query params need to be removed also from the new component. This is done in the onDestroyed method of the mailing lists.
=> fix(profile): navigation working properly in mailing lists settings

apps/admin-gui-e2e/src/e2e/admin/perun-admin.cy.js, apps/admin-gui-e2e/src/e2e/facilities/facility-admin.cy.js, apps/admin-gui-e2e/src/e2e/facilities/facility-observer.cy.js, apps/admin-gui-e2e/src/e2e/groups/group-admin.cy.js, apps/admin-gui-e2e/src/e2e/groups/group-observer.cy.js, apps/admin-gui-e2e/src/e2e/resources/resource-admin.cy.js, apps/admin-gui-e2e/src/e2e/resources/resource-observer.cy.js, apps/admin-gui-e2e/src/e2e/resources/resource-self-service.cy.js, apps/admin-gui-e2e/src/e2e/resources/trusted-facility-admin.cy.js, apps/admin-gui-e2e/src/e2e/vos/perun-admin.cy.js, apps/admin-gui-e2e/src/e2e/vos/vo-admin.cy.js, apps/admin-gui-e2e/src/e2e/vos/vo-observer.cy.js, apps/admin-gui-e2e/src/support/e2e.ts
* New path to advanced settings (and related logic) broke some tests, so it it fixed now.
* Removed skip from tests which were failing due to the bug with privileges because this bug has been already fixed IMHO (I think it was related to the refreshing roles on BE where we have done some changes to avoid PrivilegeException).
* Fixed some 'hidden' items covered by another item (like header).
=> test(admin): fixing the failing E2E tests

libs/perun/components/src/lib/attributes-list/attribute-value/attribute-value-list/attribute-value-list.component.scss
* Added a new css style to fix alignment
=> fix(lib): align items in attribute value list to the left

libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.css, libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.html, libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.scss, libs/perun/utils/src/lib/table-wrapper/table-wrapper.component.ts
Added input for inserting a wanted page number.
=> feat(admin): jump onto specific page

apps/admin-gui/src/_styles.scss
Changes rgba values to plain rgb as it was not woriking with css variables.
=> fix(admin): entity text color

libs/perun/components/src/lib/member-overview-groups/member-overview-groups.component.ts
* fixed authorization for changing group status to allow group membership managers as well
=> fix(admin): Group membership manager can set group status/expiration

apps/admin-gui/src/app/users/pages/user-detail-page/user-assignments/user-assignments.component.ts
Retrieved all resources for facility instead of only the ones assigned to user
=> fixup! feat(admin): update User section Perun Admin menu

apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html, apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.ts
* Divided the 'loading' variable into two separate variables handling the loading of header and table individually.
=> fix(admin): fix application form page spinners
