CESNET/perun-web-apps

apps/admin-gui/src/app/app.component.html
apps/admin-gui/src/app/app.component.scss
apps/admin-gui/src/app/app.component.ts
apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.html
apps/admin-gui/src/app/shared/perun-footer/perun-footer.component.scss

* There were problems with the old implementation in Safari browser.
This new implementation displays the footer on the bottom of the page
even when the content is low.

Footer reimplemented

---

apps/admin-gui/src/app/admin/components/attr-def-list/attr-def-list.component.ts

* The sorting of attribute definition was case sensitive, now it is not.

AdminGui - attribute definitions sort

---

apps/admin-gui/src/app/core/services/api/ApiInterceptor.ts
apps/admin-gui/src/app/core/services/common/store.service.ts

* If the user is not logged in or has expired, the calls to the perun
backend are cancelled.

No non-authenticated calls to perun

---

apps/admin-gui/src/app/app.component.html

* Sidemenu is closed when window is shrunk so that the style of side menu is changed
* Resolves #114

Bugfix: Close sidebar when changed size of the window

---

apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.ts

* In the subgroups page there was an invalid parameter in the call
getting all subgroups. The method now doesn't allow an empty list of
required attributes. Therefor, I have added a one attribut to this
parameter, which is actually not needed.
* Resolves: #191

AdminGui - fix bug of subgroups page

---

libs/perun/components/src/lib/table-options/table-options.component.scss

* added negative margit to table option button
I guess this could be one of the simpliest solutions
Screen of table where it previously have problem:
Cardbody have padding and I placed the export button to that padding, so that text of the headers don't overlap the options button
resolves #187

Refactor table options button

---

apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.ts

* There was a bug when adding a group admin. When selecting a VO, the
loaded groups were not actually from the selected vo but from some other
vo.
* The implementation has been fixed so the shown groups belong to the
selected vo.

BugFix - add group admin

---

package.json

* The old version command started a regular build instead of a
production build.
* The command has been fixed so it starts the production build.

Fixed version command

---

apps/admin-gui/src/app/core/services/api/ApiInterceptor.ts

* The old implementation did not force the browser not to cache the
request getting localization files. Because of that, when new version
with new localization was released, it used the old localization
instead.
* Fix: added cache control header to requests accessing localization
files.

AdminGui - disable localization cache

---

apps/admin-gui/src/app/app.component.scss

* The beta warning lvl was too height so the dialogs were partially
hidden behind it.

Fixed height of the beta warning

---

apps/admin-gui/src/app/admin/admin-routing.module.ts
apps/admin-gui/src/app/app-routing.module.ts
apps/admin-gui/src/app/shared/components/user-detail-page/user-groups/user-groups.component.html
apps/admin-gui/src/app/shared/components/user-detail-page/user-groups/user-groups.component.ts
apps/admin-gui/src/app/shared/components/user-detail-page/user-organizations/user-organizations.component.html
apps/admin-gui/src/app/shared/components/user-detail-page/user-organizations/user-organizations.component.ts
apps/admin-gui/src/app/shared/components/user-detail-page/user-overview/user-overview.component.ts
apps/admin-gui/src/app/shared/components/user-detail-page/user-settings/user-settings-facility-attributes/user-settings-facility-attributes.component.ts
apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
apps/admin-gui/src/assets/i18n/en.json
apps/admin-gui/src/assets/img/PerunWebImages/home-white.svg
libs/perun/services/src/lib/custom-icon.service.ts

resolves #273 
* fixed bug where users groups and VOs are not the ones from shown user but from principal
* when using user-organizations and user-groups components you have to add parameter to routing module (see  changed code), that determines if you want to show entities related to specified user or principal.
* changed home icon in side menu
* changed subTitles in Side-menu/Home (organizations => my organizations, ...)

users organizations and groups in Admin section 

---

apps/admin-gui/src/assets/config/defaultConfig.json
libs/perun/services/src/lib/auth.service.ts

* We need to be able to configure the loadUserInfo property of OIDC
because of SATOSA. Right now we do not actually need to load the user
info so it can be set to false by default.

OIDC - configurable property load_user_info

---

apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.scss

Closes #330 .
Added css for search-field class in component scss file.
Files Changed: group-members.component.scss

Fix for Issue 330: group - members - search field too short 

---

apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.html
apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.scss
apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.ts
apps/admin-gui/src/assets/config/defaultConfig.json

* On devel instances, we need to be able to distinguish between
production and devel instances. To do this, it is now possible to set a
config boolean variable named `isDevel`. If this is set to true, info is
shown in the nav bar.
* Resolves #386

Devel info

---

apps/admin-gui/src/assets/config/defaultConfig.json
libs/perun/services/src/lib/auth.service.ts

* On some instances we need to be able to change the response type for
oidc.
* Response type is now loaded from the configuration.

Configurable oidc response type

---

libs/perun/services/src/lib/auth.service.ts

* The method isLoggedInPromise didn't check if the current user is
expired, only that it exists. Because of that, when some user expired
and refreshed the page, the application didn't notice that he has
expired and didn't force him to log in.

BugFix - correct detection of not logged users

---

apps/admin-gui/src/app/shared/components/settings-toggle-item/settings-toggle-item.component.html
apps/admin-gui/src/app/vos/components/expiration-settings/expiration-settings.component.ts

* There was a problem where the expiration settings didn't register
changes after saving. It has been fixed.
* Also, the component SettingsToggleItem didn't work well with the model
value. It has been also fixed.

Expiration settings fix

---

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.ts
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.html
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-hosts/facility-hosts.component.ts
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-overview/facility-overview.component.ts
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.html
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-resources/facility-resources.component.ts
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-security-teams/facility-security-teams.component.html
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-security-teams/facility-security-teams.component.ts
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.html
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-service-status/facility-service-status.component.ts
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.html
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-services-destinations/facility-services-destinations.component.ts
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-overview/facility-settings-overview.component.ts
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-owners/facility-settings-owners.component.html
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-settings/facility-settings-owners/facility-settings-owners.component.ts
apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.html
apps/admin-gui/src/app/shared/components/hosts-list/hosts-list.component.ts
apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html
apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts
apps/admin-gui/src/app/shared/components/owners-list/owners-list.component.ts
apps/admin-gui/src/app/shared/components/security-teams-list/security-teams-list.component.ts
apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
libs/perun/components/src/lib/groups-list/groups-list.component.html

Resolves #395 
Added authorization for:
* Overview - items
* Sidemenu - items
* Resources - Add/Remove buttons, routing
* Allowed groups - routing (routing is enabled/disabled specifically for each item in table)
* Service status - buttons
* Service config - this should be working properly once attribute-list changes are approved
* Service destinations - buttons
* Hosts - buttons, routing, host detail should work properly with attribute-list update
* Security teams - buttons (buttons are disabled for now)
* Attributes - ..attribute-list update
* Owners - buttons
* Managers - buttons

Authorization Facility section

---

apps/admin-gui/src/app/shared/components/dialogs/move-group-dialog/move-group-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/move-group-dialog/move-group-dialog.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/group-menu/group-menu.component.html

Resolves #413  and Resolves #414 
* disabled option to move 'members' group as it cannot be moved
* fix bug when moving group under non-existing one would move the group to top level

Move group bug fix

---

libs/perun/components/src/lib/resources-list/resources-list.component.scss

Resolves#366
I found out that in resources-list.component.scss was one class 'mat-row' wrongly named and that caused that rows had smaller height than others lists. So I changed class name 'mat-row' to 'mat-row-height'.

Resource list - height of rows

---

libs/perun/services/src/lib/ApiInterceptor.ts

Resolves #486 
* fixed bug when method dontHandleErrorOnNext would cause unwanted error suppression

Dont handle error on next

---

libs/perun/services/src/lib/ApiInterceptor.ts

* There was a problem which might cause incorrect behaviour of the
service which can be used to disable global handling of notifications.
The problem was, that the information, if the request error should be
handled, was loaded AFTER the response was received. Now, this
information is loaded BEFORE the request is send.

Fixed NOT handling of errors in requests.

---

apps/admin-gui/src/app/app.component.html
apps/admin-gui/src/app/app.component.ts
apps/admin-gui/src/assets/config/defaultConfig.json

* The top bar is now hidden by default, and can be displayed by setting
the `display_warning` to true. Also, the message can be configured to
something else by setting the `warning_message` option.

Configurable warning bar

---

apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts

* The policies were loaded asynchronously, which caused some
race-conditions. Sometimes the policies were not loaded when calling
isAuthorized methods.
* The initialization should now wait for the policies to be loaded.

Fixed async load of policies

---

apps/admin-gui/src/styles.scss
libs/perun/components/src/lib/group-menu/group-menu.component.html
libs/perun/components/src/lib/group-menu/group-menu.component.scss
libs/perun/components/src/lib/groups-tree/groups-tree.component.html
libs/perun/components/src/lib/groups-tree/groups-tree.component.scss
libs/perun/components/src/lib/groups-tree/groups-tree.component.ts

Resolves #540 
* description text is now shown in tooltip only if description is too  long
* made group menu buttons always visible but disabled according to user rights to fix description offset caused by non constant 
number of  buttons shown

Group tree view description

---

apps/admin-gui/src/app/shared/components/dialogs/create-vo-dialog/create-vo-dialog.component.ts

* If user created new VO before this implementation, he or she had to find the created VO manually, if he or she wanted to do something with this VO.
* Now user is automatically redirected to the VO detail after creating a new VO.
* resolves #350

Redirect to a VO detail after creating the VO

---

apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html
apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.ts
libs/perun/components/src/lib/member-search-select/member-search-select.component.html
libs/perun/components/src/lib/user-search-select/user-search-select.component.html
libs/perun/components/src/lib/vo-select-table/vo-select-table.component.ts

* managers page in the mood "Group" is now in the table showing column organization
* policy "getApplicationsForVo_Vo_List<String>_policy" was changed from somebody from core to "getApplicationsForVo_Vo_List<String>_Boolean_policy".
* policy "getApplicationsForGroup_Vo_List<String>_policy" was changed from somebody from core to "getApplicationsForGroup_Group_List<String>_policy".
* to the member search select and user search select, that are used in two attributes pages, were added into the select information about the id so that user can now tell the difference if the users have the same name
* vo table - filtering and sorting improvements

bugfixes and improvements

---

apps/admin-gui/src/styles.scss
libs/perun/components/src/lib/groups-tree/groups-tree.component.html
libs/perun/components/src/lib/groups-tree/groups-tree.component.scss
libs/perun/components/src/lib/groups-tree/groups-tree.component.ts
libs/perun/components/src/lib/perun-components.module.ts

* The tree view of groups was not optimized for a large number of
groups. With the number of groups being high (e.g. 1000) the whole
application would lag and freeze.
* The tree view component has been reworked so it uses a virtual scoll.
This improves the performance by a lot. I have tested this changes on a
vo with 3000 groups and it works much better.
* I have also removed the check that the group description is shown only
if it doesn't fit. This check caused some errors because it used native
html properties to detect this. Also, this way the behaviour is more
consistent.

Groups tree optimization

---

apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.html
apps/admin-gui/src/app/vos/components/applications-list/applications-list.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html

* The paginator on the application list was implemented so it was not
actually used for the first view. The paginator was undefined during the
time it was set to the datasource. This caused the first view to render
all of the applications.
* On vo applications and group applications I have also replaces the
filter by a debounce filter, which is better to use with such large
number of applications. The filtration takes a long time by default.

Fix applications list for many applications

---

apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/create-group-dialog/create-group-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.ts
apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html
apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.css
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.spec.ts
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
libs/perun/components/src/lib/facility-search-select/facility-search-select.component.html
libs/perun/components/src/lib/facility-search-select/facility-search-select.component.ts
libs/perun/components/src/lib/group-search-select/group-search-select.component.html
libs/perun/components/src/lib/group-search-select/group-search-select.component.ts
libs/perun/components/src/lib/member-search-select/member-search-select.component.html
libs/perun/components/src/lib/member-search-select/member-search-select.component.ts
libs/perun/components/src/lib/perun-components.module.ts
libs/perun/components/src/lib/resource-search-select/resource-search-select.component.html
libs/perun/components/src/lib/resource-search-select/resource-search-select.component.ts
libs/perun/components/src/lib/user-search-select/user-search-select.component.html
libs/perun/components/src/lib/user-search-select/user-search-select.component.ts
libs/perun/components/src/lib/vo-search-select/vo-search-select.component.html
libs/perun/components/src/lib/vo-search-select/vo-search-select.component.ts
libs/perun/urns/src/lib/perun-urns.ts

* Search selects now use a virtual scroll so they can work well with a
large number of entities.
* The search select logic was duplicated so I have created a new general
component that is used by all specific searchSelect components.
* The attribute page with members was loading all attributes for members
which was unnecessary since these attributes were not used. I have
specified a single core attribute to be returned. If an empty list was
passed, all attributes were loaded.

Search select rework

---

apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html
apps/admin-gui/src/assets/i18n/en.json

* For now, the backend doesn't support sending english error messages.
Therefore, we have to use a custom predefined english message.

AdminGui - sponsored user pwd error message

---

apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.css
libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.ts
libs/perun/components/src/lib/perun-components.module.ts
libs/perun/services/src/index.ts
libs/perun/services/src/lib/dynamic-paginating.service.ts
libs/perun/services/src/lib/members.datasource.ts

* initially members of vo in vo-members page are dynamically acquired from database
* now backend is supporting options for sorting according to id and names
* buttons "list all" and "search" do not support this because the backend does not support this yet
* implemented according to https://blog.angular-university.io/angular-material-data-table/

dynamic paginating in vo-members page implemented

---

apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/expiration-select/expiration-select.component.html

* when no namespace is selected in generate-sponsored-members-dialog.component on password tab is showed only info that created members will have no password
* in dialogs create-sponsored-member-dialog.component.ts and generate-sponsored-members-dialog.component.ts the radio buttons are now prefilled with the first option so user dont have to click on first option if its what fits him
* changed visuals for expiration-select.component.html

minor changes to sponsored members logic

---

apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.ts

- Loading set to true at the start of the application status processing.
- Loading set to false also in case of errors during the state change.

Reworked loading after application editing

---

apps/admin-gui/src/app/shared/components/dialogs/update-application-form-dialog/update-application-form-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/update-application-form-dialog/update-application-form-dialog.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html
apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts

- Changing embedded group application approval is now possible only when
autoregistration is enabled.
- Also visibility of approval is now relying on the same condition.
- Fixed icons allignment.

Embedded application settings conditional

---

apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts

* In cache-route-reuse-strategy is new check, which is cleaning old matTooltips during the routing.

Fix - matTooltip didn't vanish after routing

---

libs/config/src/lib/app-config.service.ts
libs/perun/services/src/lib/store.service.ts

* instance config now can have property <domainName>_branding and inside this can be any property that is able to be configured
* method "get" now looks for properties in branding(if the branding exist) then it looks on the instanceConfig and then it looks on the defaultConfig
TESTING: the testing domain is gui-dev.org and gui-dev2.org, you can test the branding on these two domain, you need to change settings in apache2, allowed hosts, and also default config(oidc) 
eg. how the instance config can look: `"gui-dev2.org_branding": {
"footer_support_mail": "gui2 mail test"
},
"gui-dev.org_branding": {
"footer_support_mail": "idm@mail.muni.cz",
},`

add branding

---

apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.html
apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.scss
apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.ts
apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.html
apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.scss
apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.ts
apps/admin-gui/src/assets/i18n/en.json

* To the form configuration were added two columns which display hidden and disabled item properties. In columns are also displayed hidden and disabled dependencies.
* To the form preview were added icons which refer to hidden and disabled item properties. In the icon tooltip is dependency info.
* If some item has property disabled='ALWAYS', then is shown as disabled on the form preview.

Displayed item properties hidden/disabled on the form configuration and form preview

---

apps/publications/src/app/app.component.scss

* From now, the header will be displayed properly when viewing a dialog on a scrolled page.

fix(publications): fix header position with dialogs

---

apps/admin-gui/src/styles.scss

* when textarea was prefilled some text from code, some weird scrollbar appeared to the textarea(or arrows) - so I fixed this weird behaviour

fix textarea

---

apps/admin-gui/src/assets/config/defaultConfig.json

* the configuration for sponsor namespace attributes is now loaded from backend

remove unused config property sponsor_namespace_attributes

---

apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts

* remove hidden table and all methods that were needed to support it
* the table was needed here for exporting the logins and passwords because the exporter library needed actual table to export it
* new export method doesnt need an actual table, just data, thus the table is useless

remove unused and useless core from generate-sponsored-members

---

apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts

* The username item type can use the disabled property, however it was not possible to set these properties in admin gui.

fix(admin-gui): Show disabled config for username app item

---

libs/perun/components/src/lib/attributes-list/attributes-list.component.html
libs/perun/components/src/lib/attributes-list/attributes-list.component.scss
libs/perun/components/src/lib/attributes-list/attributes-list.component.ts

* In attribute lists we need to show the urn so the users can identify attributes.

feat(admin-gui): Show urn on attr display names

---

apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.scss
apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.scss
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.scss
apps/admin-gui/src/assets/i18n/en.json

- Placeholder in search fields for searching users and members was
updated because it is now possible to search by user UUID as well.
- Width of search fields was increased so the new placeholder can fit
in.

Searching by UUID hint

---

apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.ts

* If is not set any label for application item, then is displayed its short name on the preview.

Allowed displaying short names instead of labels on preview

---

apps/admin-gui/src/app/shared/components/dialogs/create-resource-dialog/create-resource-dialog.component.ts

* the dialog form items when creating resource are no longer marked as touched and so the items are validated after touching and not right away

fix(perun-web-apps): fix of resource dialog

---

apps/admin-gui/src/app/shared/pipes/transform-member-status.pipe.ts
libs/perun/utils/src/lib/perun-utils.ts

* Inactive member status will be used later, when all names of statuses are updated
* Now it was shown in GUI at some places when real status was set to invalid

fix: Inactive member status

---

.github/workflows/lint.yml

* The pull_request trigger works only for pr from the same repository (not forks). For forks, we need pull_request_target.

ci(GithubCI): Fix pull_request lints

---

libs/perun/components/src/lib/groups-list/groups-list.component.ts

* table of groups now uses only one call to rpc for getting vos names if
VO column is present

refactor(admin-gui): refactor of group table and getting vos

---

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html
apps/admin-gui/src/styles.scss
libs/perun/components/src/lib/group-resource-status/group-resource-status.component.html
libs/perun/components/src/lib/groups-list/groups-list.component.html
libs/perun/components/src/lib/groups-list/groups-list.component.ts
libs/perun/components/src/lib/resources-list/resources-list.component.html
libs/perun/components/src/lib/resources-list/resources-list.component.ts

- The group-resource status in table in group-list component was placed
after description column. Now, it is placed after name column like in
other tables, e.g. in members-list.
- Each status icon has now different color.

fix(admin): Fix order of columns in groups list

---

libs/perun/components/src/lib/groups-list/groups-list.component.ts

* there existed case(roles page) where the group list was viewed on page
but there were no data so error appeared

fix(admin-gui): fix groups list when there are no groups present

---

apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts

* when user wanted to edit some of 'RADIO', 'COMBOBOX', 'CHECKBOX', 'SELECTIONBOX' types of application form item the gui was displaying blank page and throwing errors on console

fix(admin-gui): fix of selection/combo box of edit application form item

---

apps/user-profile/src/app/app.component.ts
apps/user-profile/src/app/components/header/header.component.html
apps/user-profile/src/app/components/header/header.component.scss

* The header menu used to be placed out of the screen on mobile view.
* In this PR has been also fixed error 'ExpressionChangedAfterItHasBeenCheckedError', which was visible only in development mode.

fix(profile): fix header menu for mobile view

---

apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts

* Fixed workflow bug where user wasn't shown why he/she couldn't continue from 2nd to 3rd steps in process of creation sponsored member
* Fixed bug where in the last step, first option in radio button group was always checked by default, even if it was disabled

fix(admin-gui): fixed workflow of creating sponsored member

---

apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.html
apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/header-menu/header-menu.component.html
libs/perun/components/src/lib/header-menu/header-menu.component.ts

* Removed reload roles from header menu because it is no longer
needed. It was only needed for one demo.

fix: Remove reload roles

---

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-tags/resource-tags.component.html
apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-tags/resource-tags.component.ts

* Button to create a resource tag was added to the assigned tags of
resource page so a user does not have to go back and forth to add
a new tag to resource.

feat(admin): Add create tag to resource page

---

libs/perun/services/src/lib/auth.service.ts

* When no default filter was defined or when there were no filters, the application would send
acr_values=null to the oidc server, which caused it to fail the authentication.We need to set this
property only if there is some filter values.

fix: don't send acr_values=null if no filter should be used

---

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.html
apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.ts
libs/perun/utils/src/lib/perun-utils.ts

* Dashboard used to show also objects which were already deleted.
* In this PR was also added tootlip for subgroups on dashboard (tooltip shows whole fullname).

fix(admin): don't show non-existent objects on dashboard

---

.github/workflows/release.yml
.releaserc.json

* Change the Github workflow so it is run also on maintanance branches.
* Updated semantic release configuration to perform releasing on maintanance branches.

ci(githubci): add maintanance branches for semantic releasing

---

apps/user-profile/src/app/pages/identities-page/identities-page.component.html
apps/user-profile/src/app/pages/identities-page/identities-page.component.ts
apps/user-profile/src/assets/i18n/cs.json

* Other identities in section Linked identities cannot be deleted now.
* Fixed text in info tooltip.
BREAKING CHANGE: Other identities cannot be deleted any longer.

feat(profile): disable delete Other identities

---

apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
apps/admin-gui/src/app/vos/pages/member-detail-page/member-attributes/member-attributes.component.ts
libs/perun/openapi/src/lib/api/attributesManager.service.ts
libs/perun/openapi/src/lib/api/groupsManager.service.ts
libs/perun/openapi/src/lib/api/resourcesManager.service.ts
libs/perun/openapi/src/lib/api/usersManager.service.ts
libs/perun/openapi/src/lib/model/assignedGroup.ts
libs/perun/openapi/src/lib/model/assignedMember.ts
libs/perun/openapi/src/lib/model/models.ts

* All resources are now shown in member-attribute drop-down menu,
not just those with ACTIVE GroupResourceStatus.
* Regenerated openapi to access new method.

fix: Show all resources in member-attributes page

---

.releaserc.json

* Change configuration so that `alpha` and `beta` branches can release new alpha/beta releases.

ci(githubci): add alpha and beta releases

---

libs/perun/components/src/lib/perun-footer/perun-footer.component.html
libs/perun/components/src/lib/perun-footer/perun-footer.component.scss

* Items in footer columns were not aligned properly and it looked weird. From now, the items are
centered.

fix: align footer items

---

apps/publications/src/app/pages/create-publication-page/create-single-publication-page/create-single-publication-page.component.html
apps/publications/src/app/pages/create-publication-page/create-single-publication-page/create-single-publication-page.component.ts

* Create single publication page used to throw an error and it wasn't possible to create some publication (in form group control definition are properties in lower case, but in code were called these properties with upper case).

fix(publications): fix bug on create single publication page

---

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts
apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html
apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.css
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
libs/perun/components/src/lib/group-search-select/group-search-select.component.html
libs/perun/components/src/lib/group-search-select/group-search-select.component.ts
libs/perun/components/src/lib/groups-list/groups-list.component.ts
libs/perun/components/src/lib/resource-search-select/resource-search-select.component.html
libs/perun/components/src/lib/resources-list/resources-list.component.ts
libs/perun/models/src/index.ts
libs/perun/models/src/lib/GroupWithStatus.ts
libs/perun/models/src/lib/ResourceWithStatus.ts

* On group-resource and resource-group attributes page used to be only groups/resources with active
assignment status. Now there are groups/resources with all statuses (type of assignment status is
visible in search select component).

feat(admin): add all assignment statuses to group/resource attribute settings

---

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-groups/facility-allowed-groups.component.html
apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts
apps/admin-gui/src/app/shared/components/dialogs/add-member-group-dialog/add-member-group-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/add-member-to-resource-dialog/add-member-to-resource-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/create-relation-dialog/create-relation-dialog.component.html
apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.html
apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/groups-list/groups-list.component.html
libs/perun/components/src/lib/groups-list/groups-list.component.ts
libs/perun/components/src/lib/resources-list/resources-list.component.html
libs/perun/components/src/lib/resources-list/resources-list.component.ts
libs/perun/models/src/lib/GroupWithStatus.ts
libs/perun/models/src/lib/ResourceWithStatus.ts

* on page assigned groups and assigned resources we are now showing an
indicator if the group/resource was assigned automatically
* the remove
action is disabled for these groups/resources

feat(admin-gui): show automatically assigned subgroups/resources

---

apps/admin-gui/src/app/admin/pages/admin-page/admin-users/admin-users.component.html
apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/connect-identity-dialog/connect-identity-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-definition-dialog/delete-attribute-definition-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/remove-destination-dialog/remove-destination-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html
apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.html
apps/admin-gui/src/app/shared/components/member-overview-groups/member-overview-groups.component.html
apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-resources/vo-resources-states/vo-resources-states.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-application-form/vo-settings-application-form.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.html
apps/publications/src/app/components/authors-list/authors-list.component.html
apps/publications/src/app/components/publication-systems-list/publication-systems-list.component.html
apps/publications/src/app/components/thanks-list/thanks-list.component.html
apps/publications/src/app/dialogs/add-authors-dialog/add-authors-dialog.component.html
apps/publications/src/app/pages/create-publication-page/import-publications-page/import-publications-page.component.html
apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html
libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
libs/perun/components/src/lib/members-list/members-list.component.html
libs/ui/alerts/src/lib/alert/alert.component.css
libs/ui/alerts/src/lib/alert/alert.component.html

* Design of our ui alerts was unified.
* Fixed wrong usage of info/warn/error alerts in some html files.
* Fixed alert text in publication-systems-list.
* Unified definition of alert type in html files - we mainly use definition alert_type="string", but in some files was definition [alert_type]="'string'" - it was unified to definition alert_type="string".

style: unify info/warn/error alerts

---

apps/admin-gui/src/assets/i18n/en.json
libs/perun/dialogs/src/lib/change-group-resource-assigment-dialog/change-group-resource-assigment-dialog.component.html

* Label on submit button has been changed from 'Submit' to 'Activate'/'Deactivate' depending on the current status

feat(admin): change label of submit button in Change group resource assignment dialog

---

apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html
apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.ts
apps/user-profile/src/assets/config/defaultConfig.json

By setting the property "enable_security_image" under the block "mfa" in
the instanceConfig.json (defaultConfig.json), the block with security
image in the authentication settings can be displayed or hidden. Value
of the option is boolean, defaults to true (security image block
enabled).
✅ Closes: #893

feat: 🎸 Add possiblity to hide security image block

---

apps/admin-gui/src/app/shared/components/dialogs/disconnect-identity-dialog/disconnect-identity-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/disconnect-identity-dialog/disconnect-identity-dialog.component.ts
apps/admin-gui/src/assets/i18n/en.json

- Users are now warned when they are disconnecting themselves from
service accounts or when the last identity is about to be disconnected.

feat(admin): warn before disconnecting users from service accounts

---

libs/ui/alerts/src/lib/alert/alert.component.html

* instead of showing alert icon centered to block of text it will be shown at the top

fix(lib): show alert icon at top

---

apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/generate-sponsored-members-dialog/generate-sponsored-members-dialog.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/services/src/index.ts
libs/perun/services/src/lib/pdf.service.ts
libs/perun/services/src/lib/sponsored-members-pdf.service.ts
libs/ui/alerts/src/lib/alert/alert.component.css
libs/ui/alerts/src/lib/alert/alert.component.html
libs/ui/alerts/src/lib/alert/alert.component.ts
package-lock.json
package.json

feat(admin): add PDF output for generated sponsored members
* When the generation of sponsored members is now finished, a dialog apperas with the result of the generation. The result can be either 'success' or 'finished with warnings'. The later is shown id generation of some of the memebers has failed.
* On this dialog, user can download the result in two formats: CSV and PDF.
* Added new library `pdfMake`. This library is quite huge so it is lazyly loaded once it is actually needed.
feat: add success alert type
* Added new alert type `success` which can be used to show information about some successful operation.

feat(admin): add PDF output for generated sponsored members

---

apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts
apps/admin-gui/src/app/shared/perun-nav/perun-nav.component.ts
apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/user-dashboard.component.ts
apps/admin-gui/src/assets/config/defaultConfig.json
apps/user-profile/src/app/components/header/header.component.ts
apps/user-profile/src/app/services/user-profile-config.service.ts
apps/user-profile/src/assets/config/defaultConfig.json
libs/config/src/lib/app-config.service.ts
libs/perun/components/src/lib/password-reset/password-reset.component.ts
libs/perun/services/src/index.ts
libs/perun/services/src/lib/force-router.service.ts
libs/perun/services/src/lib/other-applications.service.ts
libs/perun/services/src/lib/store.service.ts

* Now are used all urls to other applications according to brand configuation.
* If no brand fix to domain, then will be used default brand.
* If the url for new app isn't defined for this brand, then will be used url for old gui.
BREAKING CHANGE: deleted "pwd_reset_base_url" property from defaultConfig files

fix: urls to other applications based on brand configuration

---

apps/admin-gui/src/app/shared/components/create-service-member-dialog/create-service-member-dialog.component.ts

* reservePasswordForLogin fails for voadmin with insufficient rights
* reservePasswordForUser can distinguish service account and allow voadmin

fix(admin): reserve password for service account with correct rights

---

apps/admin-gui/src/assets/i18n/en.json

* add missing text for "password"

fix(admin): missing text in create sponsored member dialog

---

apps/admin-gui/src/app/shared/components/audit-messages-list/audit-messages-list.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/services/src/index.ts
libs/perun/services/src/lib/custom-mat-paginator.ts

* If the total count of audit messages is greater than 1000, then is the total count only estimated.
* This estimated count is represented by `1 000 +`, `10 000 +` or `100 000 +`.

feat(admin): use estimated count of audit messages in custom paginator

---

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
apps/admin-gui/src/app/shared/components/dialogs/add-group-resource-dialog/add-group-resource-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-resources/group-resources.component.ts

* on page resource-groups the button for assign was hidden
for
combination of roles trustedFacilityAdmin+FacilityAdmin
and
resource-selfService + groupAdmin
* on dialogs
assign-group-to-resource and add-group-resource the filtration of
entities shown in table added so the user in table sees only the
entities which he 1. have the priviledge to assign 2. are not already
assigned

fix(admin): fix assign group/assign resource button auth

---

apps/admin-gui/src/assets/i18n/en.json

* dialog changed to inform user that only source group will be assigned with INACTIVE status (if chosen), subgroups should always be assigned with ACTIVE status

fix(admin): group-resource assignment dialog for active/inactive status adjusted

---

apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.ts
apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-service-identities/service-identity-detail-page/service-identity-detail-page.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts

* Some ids of entities were stored in storage with type `string` instead of `number`, which used to break authorization to some objects in the admin-gui.

fix(admin): store entity id in storage with correct type

---

apps/admin-gui/src/app/shared/components/dialogs/add-host-dialog/add-host-dialog.component.html
apps/admin-gui/src/assets/i18n/en.json

* hint below the input area has been wrapped by info alert
* title changed to placeholder text and input area is now focused from the start

feat(admin): UX change in dialog for adding hosts

---

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.ts
apps/admin-gui/src/app/shared/components/dialogs/assign-group-to-resource-dialog/assign-group-to-resource-dialog.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/groups-list/groups-list.component.html
libs/perun/models/src/lib/GroupWithStatus.ts

* Each group is displayed in this table only once now.
* If some group is assigned manually and also automatically, it will have a special icon with info in the tooltip. This group will be also able to remove (then will stay only automatic assignment).
* If some group is assigned only automatically, now will be possible to assign this group also manually in the assign-group-to-resource dialog.

feat(admin): improve list of assigned groups to resource

---

apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/selection-item-search-select/selection-item-search-select.component.ts

* The setting of a federation attribute used to be broken - user wasn't able to change the federation attribute via dialog.
* In this PR was also fixed the setting of a custom federation attribute.
* In this PR was also added a check which disables to add a required item which is hidden or disabled (uneditable) and also has no source or federation attribute (it can't have any prefilled value).

fix(admin): the setting of a federation attribute for some application form item

---

libs/perun/services/src/lib/other-applications.service.ts

* Fixed link to old password reset in admin gui and in user profile. Namespace used to be forgotten
in url to old password reset.

fix(lib): link to old password reset

---

apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.html
apps/admin-gui/src/app/shared/components/sponsored-members-list/sponsored-members-list.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-sponsored-members/vo-settings-sponsored-members.component.ts
apps/admin-gui/src/assets/i18n/en.json

* added column logins and email to sponsored member list so sponsor can
view his sponsored members and also his email and logins (the sponsor
have access to that information when creating the sponsored member, so
he should also have preview on the list - he doest have priviledge to go
to member detail)
this PR is reaction to RT ticket:
Dobrý den,
rád bych se zeptal, jak je to s oprávněním běžného zaměstnance v perunu. Nemyslím teď IT technika. Uživatelka si vytvořila sponzorovaný účet a potom v přehledu svých sponzorovaných účtů si ale nemůže jednotlivé účty rozkliknout a zkontrolovat např. učo. Pokud si tedy hned po vygenerování účtu neuloží údaje, tak se k nim už posléze nedostane.
Děkuji,
BTW - this PR doesnt resolve this problem completely - problem is that sponsor doesnt have the …

feat(admin): added columns to sponsored members list

---

libs/perun/login/src/lib/login-screen/login-screen.component.ts

* when user is logged in and goes to /login, the login component isn't displayed and the user is redirected to /home instead

fix: redirect from login page to home if user logged in

---

angular.json
apps/user-profile/src/app/app-routing.module.ts
apps/user-profile/src/app/app.module.ts
apps/user-profile/src/app/pages/consents-page/consent-request/consent-request.component.html
apps/user-profile/src/app/pages/consents-page/consent-request/consent-request.component.scss
apps/user-profile/src/app/pages/consents-page/consent-request/consent-request.component.ts
apps/user-profile/src/app/pages/consents-page/consents-page.component.html
apps/user-profile/src/app/pages/consents-page/consents-page.component.ts
apps/user-profile/src/app/pages/consents-page/consents-preview/consents-preview.component.html
apps/user-profile/src/app/pages/consents-page/consents-preview/consents-preview.component.ts
apps/user-profile/src/app/services/side-menu-item.service.ts
apps/user-profile/src/assets/config/defaultConfig.json
apps/user-profile/src/assets/i18n/cs.json
apps/user-profile/src/assets/i18n/en.json
apps/user-profile/src/styles.scss
libs/config/table-config/src/lib/table-config.service.ts
libs/perun/components/src/lib/consent-status/consent-status.component.html
libs/perun/components/src/lib/consent-status/consent-status.component.scss
libs/perun/components/src/lib/consent-status/consent-status.component.ts
libs/perun/components/src/lib/consents-list/consents-list.component.css
libs/perun/components/src/lib/consents-list/consents-list.component.html
libs/perun/components/src/lib/consents-list/consents-list.component.ts
libs/perun/components/src/lib/perun-components.module.ts
libs/perun/openapi/src/lib/api/consentsManager.service.ts
libs/ui/material/src/lib/ui-material.module.ts

* user can manage his consents in consents page
* the user is redirected
from email url to page /profile/consents/:consentId
BREAKING CHANGE: * add new item 'consents' to 'displayed_tabs' array if you want to show consents page in menu

feat(profile): manage consents

---

apps/admin-gui/src/app/admin/admin-routing.module.ts
apps/admin-gui/src/app/admin/admin.module.ts
apps/admin-gui/src/app/admin/pages/admin-page/admin-overview/admin-overview.component.ts
apps/admin-gui/src/app/admin/pages/admin-page/admin-searcher/admin-searcher.component.html
apps/admin-gui/src/app/admin/pages/admin-page/admin-searcher/admin-searcher.component.ts
apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts
apps/admin-gui/src/app/shared/components/dialogs/application-form-copy-items-dialog/application-form-copy-items-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/notifications-copy-mails-dialog/notifications-copy-mails-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/sponsor-existing-member-dialog/sponsor-existing-member-dialog.component.html
apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-service-members/vo-settings-service-members.component.html
apps/admin-gui/src/assets/i18n/en.json
libs/config/table-config/src/lib/table-config.service.ts
libs/perun/components/src/lib/attribute-search-select/attribute-search-select.component.html
libs/perun/components/src/lib/attribute-search-select/attribute-search-select.component.ts
libs/perun/components/src/lib/members-list/members-list.component.html
libs/perun/components/src/lib/members-list/members-list.component.ts
libs/perun/components/src/lib/perun-components.module.ts
libs/perun/components/src/lib/resources-list/resources-list.component.html
libs/perun/components/src/lib/resources-list/resources-list.component.ts
libs/perun/components/src/lib/vo-search-select/vo-search-select.component.ts
libs/perun/dialogs/src/lib/change-member-status-dialog/change-member-status-dialog.component.ts
libs/perun/openapi/src/lib/api/searcher.service.ts
libs/perun/pipes/src/lib/member-status-tooltip.pipe.ts
libs/perun/services/src/lib/custom-icon.service.ts
libs/perun/utils/src/lib/perun-utils.ts

* Added Searcher page with four tabs (users, members, facilities, resources).
* To members-list and resources-list were added new columns according to the old GUI.
* At this moment, we get the Member object from BE, but member status tooltip and member expiation settings require RichMember, so some other components have to be changed.

feat(admin): add Searcher to the admin section

---

apps/admin-gui/src/app/admin/pages/admin-page/admin-consent-hubs/admin-consent-hubs.component.html
apps/admin-gui/src/app/admin/pages/admin-page/admin-consent-hubs/admin-consent-hubs.component.ts
apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.html
apps/admin-gui/src/app/admin/pages/admin-page/admin-services/service-detail-page/service-detail-page.component.ts
apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-tags/resource-tags.component.ts
apps/admin-gui/src/app/shared/components/consent-hubs-list/consent-hubs-list.component.html
apps/admin-gui/src/app/shared/components/consent-hubs-list/consent-hubs-list.component.ts
apps/admin-gui/src/app/vos/components/application-detail/application-detail.component.ts
apps/admin-gui/src/app/vos/components/application-form-manage-groups/application-form-manage-groups.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-member-organizations/vo-settings-member-organizations.component.ts
apps/admin-gui/src/assets/i18n/en.json
apps/publications/src/app/components/add-authors/add-authors.component.ts
apps/publications/src/app/components/add-thanks/add-thanks.component.ts
libs/perun/dialogs/src/index.ts
libs/perun/dialogs/src/lib/perun-dialogs.module.ts
libs/perun/dialogs/src/lib/universal-confirmation-items-dialog/universal-confirmation-items-dialog.component.html
libs/perun/dialogs/src/lib/universal-confirmation-items-dialog/universal-confirmation-items-dialog.component.ts
libs/perun/openapi/src/lib/api/consentsManager.service.ts
libs/perun/openapi/src/lib/model/service.ts
package-lock.json

* on service detail, new button added to initiate consent evaluation for given service
* on consent hubs page, new column for checkboxes added
* also, new button added to initiate consent evaluation for selected consent hubs
Note: This PR is waiting for its backend counterpart to be merged.

feat(admin-gui): manual consent evaluation for service and consent hub

---

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-detail-page.component.ts
apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-detail-page.component.ts
apps/admin-gui/src/app/shared/destroy-entity-detail.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-detail-page.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-detail-page.component.ts

* created mixin to handle unsubscribing from reload when destroyed
* entity details now extend this mixin
* this should fix sidemenu showing items for wrong entity

fix(admin): entity detail unsubscribe on destroy

---

apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.ts

* Now is possible to deploy user-profile without security images.
* If the property enable_security_image is set to false, then the Profile->Settings->Authentication page will contain just enforce mfa functionality (without security images).

feat(profile): authentication settings page can be without security images

---

apps/admin-gui/src/app/users/pages/user-detail-page/user-attributes/user-attributes.component.ts

* We tried to parse userId from url and if it was undefined, then we parsed it from principal. As we
changed type notation from as number to Number(), the userId is equal to NaN (if it isn't present in
the url) and the check just for undefined was failing, so we didn't parse the userId from principal.

fix(admin): parsing userId on myProfile/attributes page

---

apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html
libs/perun/pipes/src/index.ts
libs/perun/pipes/src/lib/member-checkbox-label.pipe.ts
libs/perun/pipes/src/lib/member-list-checkbox-disabled.pipe.ts
libs/perun/pipes/src/lib/perun-pipes.module.ts
libs/perun/urns/src/lib/perun-urns.ts

* on the members section of a VO, disable checkboxes for members that come from member VOs, which previously was doable and resulted in an error.

fix(admin): disable checkboxes for members from member VOs

---

apps/admin-gui-e2e/src/integration/facility-management-perun_admin.spec.js
libs/perun/services/src/lib/init-auth.service.ts

* If a logged-out user tried to access some specific url, immediately after logging in gui told
him/her that he/she is not authorized to access this page even if he/she has rights to access it
(route policy was checked before the principal was loaded).
* E2E test file for facility admin was also edited according to this new behavior.

fix(admin): evaluating route authorization

---

apps/admin-gui/src/app/app.module.ts
apps/consolidator/src/app/app.module.ts
apps/linker/src/app/app.module.ts
apps/password-reset/src/app/app.module.ts
apps/publications/src/app/app.module.ts
apps/user-profile/src/app/app.module.ts
libs/perun/services/src/lib/auth.service.ts

* storing tokens is moved from session storage to local storage because session storage is storing the data only for one tab,
but we want to share tokens across multiple tabs
* refreshing token is now only triggered when access token is expired
* expiration of tokens was moved from 0.75(default) to random number from 0.5 to 0.75 so the refreshing of the token is not triggered by multiple tabs at the same time
* sidemenu items url links members applications and groups fixed

fix: use localStorage for storing access token/refresh token

---

apps/user-profile/src/app/pages/settings-page/settings-mailing-lists/settings-mailing-lists.component.ts

* vos and resources are now sorted alphabetically on the mailing lists opt-out page

fix(profile): sort vos and resources on the mailing lists page

---

apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/services-status-list/services-status-list.component.html

* if no destination is set for service on facility, warning is shown in services status view
* this way user is informed why is the task not running

feat(admin): show warning if no destinations set for service

---

apps/user-profile/src/app/pages/settings-page/settings-mailing-lists/settings-mailing-lists.component.ts
libs/perun/openapi/src/lib/api/resourcesManager.service.ts

Previous workflow were not optimal. We were using method that obtained ALL member resources and then we checked whether they have mailing service assigned. Now, only resources with mailing service(s) present are returned from method used for it.
* new method returns only those resources that have mailing service(s) and given member assigned
* method generated using openApi

feat(user-profile): method for obtaining member resources changed

---

libs/perun/components/src/lib/members-dynamic-list/members-dynamic-list.component.html

Previous solution didn't cause problems, since the group members page didn't provide the Lifecycle attribute to dynamic members list, however with https://github.com/CESNET/perun-web-apps/pull/1083 its now necessary and this bug was revealed.

fix(admin): fixed a bug where checkboxes were disabled in group members page

---

apps/admin-gui/src/app/facilities/pages/resource-detail-page/resource-groups/resource-groups.component.html
apps/admin-gui/src/app/shared/components/dialogs/remove-group-from-resource-dialog/remove-group-from-resource-dialog.component.html

Redundant > symbols from html files were removed.

fix: remove redundant symbols

---

apps/user-profile/src/app/app.module.ts
apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.html
apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.ts
apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html
apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.ts
apps/user-profile/src/assets/i18n/cs.json
apps/user-profile/src/assets/i18n/en.json
libs/perun/services/src/index.ts
libs/perun/services/src/lib/mfa-api.service.ts

* To the authentication page was added advanced MFA settings. Now is possible to select categories
and services (rps) which requires mfa.
* If enforce mfa is set to true, then all categories are selected and they are not allowed for disabling.
* If enforce mfa (for all services) is set to false, then user can select particular categories and services.
BREAKING CHANGE: For this functionality is required new oauh scope - authn_details in instance
config. Also new version of MFA API which supports this functionality is required.

feat(profile): add advanced MFA settings

---

apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts

* components are now cached per page, before only one instance was cached and could result in mismatch between data and entity

fix(admin): cache multiple component instances

---

apps/admin-gui/src/styles.scss
apps/consolidator/src/styles.scss
apps/linker/src/styles.scss
apps/password-reset/src/styles.scss
apps/publications/src/styles.scss
apps/user-profile/src/styles.scss

* mat icons now inherit overflow instead of default hidden across all apps

fix: prevent mat icons from being clipped

---

apps/admin-gui/src/app/admin/pages/admin-page/admin-consent-hubs/admin-consent-hubs.component.html
apps/admin-gui/src/app/admin/pages/admin-page/admin-consent-hubs/admin-consent-hubs.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/models/src/lib/ConfigProperties.ts

* if enforce_consents is false on the instance, display a warning informing the user that any changes on the consent hubs page will have no effect
* when consents globally disabled, disabled the 'Evaluate consents' button and added a tooltip

feat(admin): warning on consents hub page when global consent enforcing is disabled

---

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.ts

* Adding tags to html notifications was broken because in html file is used ngIf for inputs and
textareas, so item(1) never exists - plainText item(0) is replaced by htmlText item(0).

fix(admin): add tag to html notification

---

apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts

* after manager was removed the whole page was reloaded resulting in tab and role selection reseting to default

fix(admin): do not change tab when removed manager

---

apps/admin-gui/src/app/vos/components/add-member.service.ts
apps/admin-gui/src/app/vos/components/group-add-member-dialog/group-add-member-dialog.component.ts
apps/admin-gui/src/app/vos/components/vo-add-member-dialog/vo-add-member-dialog.component.ts

* When MFA error occurs in this dialog and user clicks on cancel in MFA dialog, the previous dialog for member adding stayed in loading state.

fix(admin): add member dialog behavior on MFA error

---

apps/admin-gui/src/app/shared/components/member-overview-membership/member-overview-membership.component.ts
apps/admin-gui/src/app/shared/route-auth-guard.service.ts
apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
apps/admin-gui/src/app/vos/components/add-member.service.ts
apps/admin-gui/src/app/vos/components/group-add-member-dialog/group-add-member-dialog.component.ts
apps/admin-gui/src/app/vos/components/vo-add-member-dialog/vo-add-member-dialog.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-members/group-members.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-overview/group-overview.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-expiration/group-settings-expiration.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.ts
apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-overview/group-settings-overview.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-members/vo-members.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-expiration/vo-settings-expiration.component.ts
apps/admin-gui/src/app/vos/pages/vo-select-page/vo-select-page.component.ts
apps/linker/src/app/service/link-identities.service.ts
apps/user-profile/src/app/pages/consents-page/consent-request/consent-request.component.ts
libs/perun/namespace-password-form/src/lib/perun-namespace-password-form.ts
libs/perun/services/src/lib/api.service.ts

* Due to changes in ApiInterceptor there are some bugs in how we handle RPC errors. We used to "catch" HttpErrorResponse in components and then we unwrapped the inner RPC error. Now we have to catch the RPC inner error directly in all components.

fix: correctly handle RPC error in all components

---

apps/admin-gui/src/app/app.component.html
apps/publications/src/app/app.component.html
apps/user-profile/src/app/app.component.html

* when sidenav is hidden and reopened, the below window's width is not recalculated
* currently this is only a case in admin-gui, the fix is applied also to publications and profile as a precaution

fix: resize window on sidenav reopening

---

apps/admin-gui/src/assets/i18n/en.json
apps/consolidator/src/assets/i18n/en.json
apps/linker/src/assets/i18n/en.json
apps/password-reset/src/assets/i18n/cs.json
apps/password-reset/src/assets/i18n/en.json
apps/publications/src/assets/i18n/en.json
apps/user-profile/src/assets/i18n/cs.json
apps/user-profile/src/assets/i18n/en.json
libs/perun/multi-factor-authentication/src/lib/mfa-required-dialog/mfa-required-dialog.component.html
libs/perun/multi-factor-authentication/src/lib/mfa-required-dialog/mfa-required-dialog.component.ts
libs/perun/services/src/lib/ApiInterceptor.ts
libs/perun/services/src/lib/mfa-handler.service.ts

* If there is the MfaRolePrivilegeException, we want to hide the cancel button.
* Previously after clicking on the cancel button there appeared another dialog with a refresh button, which only redirects the user back to the first dialog, so the cancel button is useless for this use case with role exception.

feat: better workflow for MFA dialog with MfaRolePrivilegeException

---

apps/user-profile/src/app/app.module.ts
apps/user-profile/src/app/components/dialogs/add-auth-text-dialog/add-auth-text-dialog.component.html
apps/user-profile/src/app/components/dialogs/add-auth-text-dialog/add-auth-text-dialog.component.ts
apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.html
apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.scss
apps/user-profile/src/app/pages/settings-page/settings-authorization/settings-authentication.component.ts
apps/user-profile/src/assets/config/defaultConfig.json
apps/user-profile/src/assets/i18n/cs.json
apps/user-profile/src/assets/i18n/en.json
libs/perun/models/src/lib/ConfigProperties.ts

* In Settings->Authentication section we already have support for security images. We wanted to add support also for security texts.

feat(profile): support securityText attribute

---

apps/admin-gui/src/app/vos/pages/group-detail-page/group-applications/group-applications.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-applications/vo-applications.component.html

* 'pending' applications are preselected in the filer
* the order of the selection makes the dropdown sidebar slide downwards, which is confusing for the users as they don't see the top options
* prioritized the pending applications field to keep sidebar at top when filter menu is opened

fix(admin): move default filter option in applications up

---

apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-notifications/group-settings-notifications.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-notifications/vo-settings-notifications.component.ts

* Privilidge to copy notifications were wrongly evaluated
* Now correct policy is used for both vo and group

fix(admin): Fix copy of notifications

---

apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.html
apps/admin-gui/src/app/vos/components/application-form-preview/application-form-preview.component.html

* In the preview column in the application form list and also on the preview page there are now the HTML items displayed correctly with CSS styles.

fix(admin): show styles correctly on preview for HTML form items

---

libs/perun/services/src/lib/other-applications.service.ts

* If no brand domain is the same as current domain, return the default brand.

fix(lib): links to other applications

---

libs/perun/login/src/lib/login-screen/login-screen.component.ts

Previously if user was logged in and tried to access login page he would be redirected to "/home" which does not exist on all applications. Now he is redirected to "" (just base url). Each application than correctly navigates to it's "home" page.

fix: Login page redirect to correct "home" page

---

apps/admin-gui/src/app/shared/components/dialogs/create-attribute-dialog/create-attribute-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/delete-attribute-dialog/delete-attribute-dialog.component.ts
libs/perun/dialogs/src/lib/edit-attribute-dialog/edit-attribute-dialog.component.ts

* on resource and facility details, it was not possible to correctly work with two-entity attributes
* now they are correctly shown, filtered, updatable and removable

fix(admin): fixed two-entity attributes selection, setting and removal

---

.openapi-generator/templates/api.service.mustache

* added description for the useNon parameter in services
* changes will be visible after next openapi generation

fix: added jdocs for useNon parameter

---

libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts
libs/perun/login/src/lib/login-screen/login-screen.component.ts

* fixed bug where if user tried to log in by manually typing /service-access in the url, the login page would be displayed even after authentication (instead of homepage of the app)

fix: don't display login page after user has been logged in

---

apps/admin-gui/src/app/vos/pages/member-detail-page/member-bans/member-bans.component.ts

* member's bans are returned as null as opposed to empty list responses of similar methods

fix(admin): fix member bans view

---

apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.html
apps/admin-gui/src/app/shared/components/attr-def-list/attr-def-list.component.ts
apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-settings-app-configuration/user-settings-app-configuration.component.html
apps/admin-gui/src/assets/i18n/en.json
libs/config/table-config/src/lib/table-config.service.ts
libs/perun/components/src/lib/attributes-list/attributes-list.component.html

* attributes and attribute definition lists are now sorted by display name by default
* added display name column to admin attribute definitions list
* the mentioned lists now display 25 entities on one page by default
* fixed the personal preferred table page size config (changes didn't take effect correctly before)

fix(admin): sort attributes list by display name

---

apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.html
apps/admin-gui/src/app/shared/components/entityless-attribute-keys-list/entityless-attribute-keys-list.component.ts
libs/perun/services/src/lib/table-checkbox.service.ts

* fixed problem when adding new key-value pair for attribute definition, table was not rendered (loaded) properly - missing newly prepared row
* checkboxes fixed
* mat-sort-header keyword removed from table headers (for now)

fix(admin): entityless attributes key-value pairs correctly displayed

---

libs/perun/components/src/lib/perun-footer/perun-footer.component.ts

* fixed a bug where if the call for rpc version returned a different response than expected, a type error would happen and the whole footer would not load

fix: footer loads properly even when RPC version cannot be parsed

---

apps/admin-gui/src/app/shared/components/dialogs/invite-member-dialog/invite-member-dialog.component.ts

* Sending an invitatoin via dialog for a single member did not send in a request also a requested name (tag in notification is {displayName}). The name filled in a dialog is now send as a part of the request, so it is also correctly send in an email notification.

fix(admin): send invitation to one member

---

apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html
apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.ts
apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.html
apps/admin-gui/src/app/users/pages/user-detail-page/user-settings/user-roles/user-roles.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/facilities-list/facilities-list.component.html
libs/perun/components/src/lib/facilities-list/facilities-list.component.ts
libs/perun/components/src/lib/groups-list/groups-list.component.html
libs/perun/components/src/lib/groups-list/groups-list.component.ts
libs/perun/components/src/lib/resources-list/resources-list.component.html
libs/perun/components/src/lib/resources-list/resources-list.component.ts
libs/perun/components/src/lib/vos-list/vos-list.component.html
libs/perun/components/src/lib/vos-list/vos-list.component.ts
libs/perun/openapi/src/lib/api/authzResolver.service.ts
libs/perun/services/src/lib/role.service.ts

* user-detail page splits his roles by source (directly assigned or obtained as a member of authorized group)
* tabs added to change what source we want to see
* authorized-group-based roles cannot be managed, only viewed

feat(admin): user roles are split by source

---

apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/create-sponsored-member-dialog/create-sponsored-member-dialog.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/namespace-password-form/src/lib/password-form/password-form.component.ts

* login and password input fields are disabled by default (namespace must be selected first)
* internationalized message added

feat(admin): sponsored member create dialog input fields fix

---

apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.html
apps/admin-gui/src/app/facilities/pages/facility-detail-page/facility-allowed-users/facility-allowed-users.component.ts
apps/admin-gui/src/app/vos/pages/member-detail-page/member-bans/member-bans.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-hierarchical-inclusion/vo-settings-hierarchical-inclusion.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-settings/vo-settings-member-organizations/add-member-organization-dialog/add-member-organization-dialog.component.html

* fixed a bug where user could skip to second step of the add member org dialog without actually picking a VO
* removed "No filter" dummy objects from resource assigned users page filters
* fixed a bug where the bans table for the member wouldn't load if the user had no bans, also added Vo object to the EnrichedBanForVo object to avoid exceptions in ban on entity list
* fixed a bug where user could try to add a group inclusion without a VO selected, resulting in an empty dialog

fix: bug fixes after angular 15 migration

---

apps/admin-gui/src/_styles.scss
apps/consolidator/src/assets/config/defaultConfig.json
apps/linker/src/assets/config/defaultConfig.json
apps/password-reset/src/_styles.scss
apps/password-reset/src/assets/config/defaultConfig.json
apps/publications/src/_styles.scss
apps/user-profile/src/_styles.scss
apps/user-profile/src/app/pages/settings-page/settings-samba-password/settings-samba-password.component.html
apps/user-profile/src/app/pages/settings-page/settings-samba-password/settings-samba-password.component.scss
libs/perun/components/src/lib/settings-mailing-lists/mailing-lists.component.html

* added user style to defaultConfig.json in apps it was missing, since it now won't load without it
* fixed mailing lists checkbox misalignment
* added the visibility icon to the form field in settings-samba-password.component
* fixed a bug that made password form jump when spinner was visible (global spinner margin was removed, it was added just for a slight visual change, I believe we can do without it)

fix: minor visual bug fixes after angular 15 migration

---

.github/workflows/release.yml

* To the release workflow was added parameter --legacy-peer-deps to the npm ci.

ci: fixed npm install in release workflow

---

libs/perun/components/src/lib/password-reset/password-reset.component.ts

* There was a bug during the process of changing password - when user is in the dialog and finish the it by clicking on Cancel or Confirm, then the browser back button behaves incorrectly.

fix: browser history for change password dialog

---

apps/admin-gui/src/app/core/services/common/cache-route-reuse-strategy.ts

* if the back button was used while an overlay component was present on a cached page, the component would not close and block the rest of the gui
* components in the overlay are no longer cached

fix: fixed bug that caused overlay components to block gui

---

apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.html
apps/user-profile/src/app/pages/settings-page/settings-authorization/mfa-settings/mfa-settings.component.ts
apps/user-profile/src/assets/i18n/cs.json
apps/user-profile/src/assets/i18n/en.json

* when call to MFA API fails on setting-auth page, display meaningful message instead of telling the user he has no active MFA tokens

fix(profile): add a meaningful error message when call to MFA API fails.

---

apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.html
apps/admin-gui/src/app/admin/pages/admin-user-detail-page/admin-user-detail-page.component.ts
apps/admin-gui/src/assets/config/defaultConfig.json
apps/admin-gui/src/assets/i18n/en.json
libs/perun/dialogs/src/index.ts
libs/perun/dialogs/src/lib/delete-entity-dialog/delete-entity-dialog.component.html
libs/perun/dialogs/src/lib/delete-user-dialog/delete-user-dialog.component.html
libs/perun/dialogs/src/lib/delete-user-dialog/delete-user-dialog.component.ts
libs/perun/dialogs/src/lib/perun-dialogs.module.ts
libs/perun/models/src/lib/ConfigProperties.ts

* There is new config property 'user_deletion_forced' which defines if users on instance can be deleted or anonymized (this is the default option).
* This task is related to new backend implementation where deletion of user is now connected with blocking of user's logins.
* The new configuration property 'user_deletion_forced' (default false) was added. When this property is not set, still the default anonymization will be applied.
BREAKING-CHANGE: new configuration property 'user_deletion_forced'

feat(admin): allow deletion of users according to config property

---

apps/admin-gui/src/app/shared/components/dialogs/add-edit-notification-dialog/add-edit-notification-dialog.component.ts

Previous refactor caused variable to be left out unitialized, which prevented the internals of dialogue window to be loaded when it has been opened for group notifications

fix: 🐛 Fix loading of add/edit notification dialog

---

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-card/dashboard-card.component.html

Added display property for cover-image to align icons with the text.

fix(admin): align icons of Manageable entities on home page with text

---

apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.html
apps/admin-gui/src/app/facilities/pages/facility-select-page/facility-select-page.component.ts
apps/admin-gui/src/assets/i18n/en.json

* There was used a policy which evaluates also given object (facility), so there is not possible to paste an empty array.
* Now the button is removed, when user doesn't have any suficient role (facility admin or perun admin) and if user has facility admin, authorization for selected facility will be evaluated additionally.
* This issue was discovered thanks to e2e tests and this PR should fix then again.

fix(admin): authorization for delete facility

---

apps/admin-gui/src/app/app.module.ts
apps/consolidator/src/app/app.module.ts
apps/linker/src/app/app.module.ts
apps/password-reset/src/app/app.module.ts
apps/publications/src/app/app.module.ts
apps/user-profile/src/app/app.module.ts
libs/perun/utils/src/lib/perun-utils.ts

* without sending cookies, sessions for service-access (basic auth) are renewed on backend for each request
* that causes extsource loa to be updated which then updates relevant attribute (2 audit messages for EACH request!)
* this was not a problem for oidc access, because session was not renewed in case of missing cookies
* withCredentials header will solve problem for renewing sessions, but requests will fail if apache configuration does not allow domain for this behavior
* localhost is not supported origin, therefore we only add withCredentials header to calls from domain not coming from localhost

feat: use cookies in requests

---

apps/user-profile/src/app/components/membership-list/membership-list.component.html
apps/user-profile/src/app/components/membership-list/membership-list.component.ts
apps/user-profile/src/app/pages/groups-page/groups-page.component.html
apps/user-profile/src/app/pages/groups-page/groups-page.component.ts
apps/user-profile/src/app/pages/vos-page/vos-page.component.html
apps/user-profile/src/app/pages/vos-page/vos-page.component.ts
apps/user-profile/src/assets/i18n/cs.json
apps/user-profile/src/assets/i18n/en.json

* Instant spinners were displayed for use cases when array of loaded vos/groups was empty - now the behavior is fixed also for cases when the user doesn't have any memberhip.
* Also the bug of vos filter on Groups page was fixed (filter wasn't applied if there was no group membership under the selected vo).

fix(profile): loading edge cases of Organizations and Groups pages

---

libs/perun/pipes/src/lib/user-full-name.pipe.ts

* All parts of full name are joined with space, but if there is some part of the name missing (e.g. middle name), there are more white spaces in the full name.

fix(lib): remove white spaces from the full name pipe

---

libs/perun/services/src/lib/ApiInterceptor.ts

* There was a bug that during step-up authentication process the session expiration dialog was shown.
* I believe that this one added condition should solve this problem without any other side effects.

fix: do not show sesssion expiration dialog during mfa

---

apps/admin-gui/src/assets/config/defaultConfig.json
apps/consolidator/src/assets/config/defaultConfig.json
apps/linker/src/assets/config/defaultConfig.json
apps/password-reset/src/assets/config/defaultConfig.json
apps/publications/src/assets/config/defaultConfig.json
apps/user-profile/src/assets/config/defaultConfig.json
libs/perun/models/src/lib/ConfigProperties.ts
libs/perun/services/src/lib/auth.service.ts

* There is a new option to define default acr value in config file.
* The default value of this property enables to correctly handle information about already performed mfa - if the idp requires mfa by itself, Perun applications should skip its own mfa logic, because user already has valid mfa session on proxy.
BREAKING CHANGE: new string property oauth_acr_value in defaultConfig.json

fix: add new defaul acr value

---

apps/admin-gui/src/_styles.scss
apps/consolidator/src/_styles.scss
apps/publications/src/_styles.scss
apps/user-profile/src/_styles.scss

* Table header is now bold to distinguish form table cells

fix: Highlight table column headers

---

apps/admin-gui/src/app/shared/components/roles-list/roles-page.component.html

Removed icons from individual roles on roles overveiw page, because they served no real purpose, providing no additional information.

fix(admin): remove icons on roles overview page

---

apps/admin-gui/src/app/shared/components/settings-toggle-item/settings-toggle-item.component.html
apps/admin-gui/src/app/vos/components/expiration-settings/expiration-settings.component.html
apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html
apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
libs/perun/components/src/lib/attribute-critical-operations-toggles/attribute-critical-operations-toggles.component.html
libs/perun/components/src/lib/attribute-unique-toggle/attribute-unique-toggle.component.html

* The color attribute was removed from mat-slide-toggle tags so the default accent color is used across all GUI.

fix(admin): unify color of mat-slide-toggles

---

apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.html
apps/admin-gui/src/app/vos/pages/group-detail-page/group-settings/group-settings-application-form/group-settings-application-form.component.ts
apps/admin-gui/src/assets/i18n/en.json

* Now it is possible to set approval style also for embedded group applications on a subgroup level.
* Toogle was replaced by info text. Previously it was possible to change autoRegistration on an organization level from app detail, but now we don't want to allow this feature due to subgroup level of autoRegistration.
* Also some little refactor was done for this page.

fix(admin): allow to change approval style for embedded group applications

---

libs/perun/dialogs/src/lib/delete-entity-dialog/delete-entity-dialog.component.html
libs/perun/dialogs/src/lib/delete-entity-dialog/delete-entity-dialog.component.scss

* changed delete-entity-dialog margins to fix text overlap

fix: don't overlap text in delete dialog

---

.github/workflows/check.yml

* Fix commitlint rules to correctly ignore 'dependabot/npm_and_yarn/' branch prefix for a source branch.

fixup! chore: change commitlint rules

---

apps/admin-gui/src/app/shared/components/dialogs/block-logins-dialog/block-logins-dialog.component.html

The chosen namespace does not disappear while changing block options.

fix(admin): fixed block logins dialog

---

libs/perun/components/src/lib/attributes-list/attributes-list.component.ts

Added a filter that filters out attributes whose value is an object that is otherwise empty.

fix(lib): hide attributes without values

---

apps/admin-gui/src/app/shared/components/dialogs/edit-attribute-definition-dialog/edit-attribute-definition-dialog.component.html

Cancel button is now on the left in the edit attribute definition dialog.

fix(admin): correct button layout in edit attribute definition dialog

---

libs/perun/services/src/lib/auth.service.ts

* even when proxy_logout was false, oauth-service redirected to logout page specified in openid-configuration. This no longer happens

fix: do not redirect to proxy logout page when not required

---

libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.html

* When the user is logged out from service-access, he/she can see the info alter about successfull log out. Then if the user try to log in again with incorrect credentials, another alert will be displayed, but the old one used to be still presented on login page.

fix(lib): display just one alert on login page

---

apps/admin-gui/src/assets/i18n/en.json
apps/user-profile/src/assets/i18n/cs.json
apps/user-profile/src/assets/i18n/en.json
libs/perun/components/src/lib/password-reset/password-reset.component.html
libs/perun/components/src/lib/password-reset/password-reset.component.ts
libs/perun/dialogs/src/index.ts
libs/perun/dialogs/src/lib/password-reset-dialog/password-reset-dialog.component.html
libs/perun/dialogs/src/lib/password-reset-dialog/password-reset-dialog.component.ts
libs/perun/dialogs/src/lib/perun-dialogs.module.ts

Password reset, when clicked on in profile, now opens a modal window instead of redirecting to separate application.
* Created a new password reset dialog
* Modified password-reset component to use this new dialog.

feat(lib): password reset on profile opens modal window

---

apps/admin-gui/src/assets/i18n/en.json
apps/consolidator/src/assets/i18n/en.json
apps/linker/src/assets/i18n/en.json
apps/password-reset/src/assets/i18n/cs.json
apps/password-reset/src/assets/i18n/en.json
apps/publications/src/assets/i18n/en.json
apps/user-profile/src/assets/i18n/cs.json
apps/user-profile/src/assets/i18n/en.json
libs/general/src/index.ts
libs/general/src/lib/general.module.ts
libs/general/src/lib/user-not-allowed-access/user-not-allowed-access.component.html
libs/general/src/lib/user-not-allowed-access/user-not-allowed-access.component.ts
libs/perun/services/src/lib/init-auth.service.ts

* service accounts are now not able to log in
* a new dialog has been added, that can redirect users to /login or /service-access
* the dialog logic is evaluated when principal is loading

feat: remove access for service-accounts

---

apps/admin-gui/src/app/vos/pages/group-detail-page/group-subgroups/group-subgroups.component.html
apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.html
apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.scss
apps/admin-gui/src/app/vos/pages/member-detail-page/member-groups/member-groups.component.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-groups/vo-groups.component.html
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/groups-list/groups-list.component.html
libs/perun/components/src/lib/groups-list/groups-list.component.ts
libs/perun/components/src/lib/groups-tree/groups-tree.component.html
libs/perun/components/src/lib/groups-tree/groups-tree.component.ts

* Member groups page was extended by tree view (previously there was just list view).
* Groups-tree component was extended by group status icon and expiration functionality (expiration can be edited also from tree view).

feat(admin): added tree view also to member-groups page

---

apps/admin-gui/src/app/shared/components/dialogs/delete-application-form-item-dialog/delete-application-form-item-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/delete-application-form-item-dialog/delete-application-form-item-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.html
apps/admin-gui/src/app/shared/components/dialogs/edit-application-form-item-dialog/edit-application-form-item-dialog.component.ts
apps/admin-gui/src/app/vos/components/application-form-list/application-form-list.component.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.css
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.html
libs/perun/components/src/lib/entity-search-select/entity-search-select.component.ts
libs/perun/components/src/lib/selection-item-search-select/selection-item-search-select.component.html
libs/perun/components/src/lib/selection-item-search-select/selection-item-search-select.component.ts

* Provide a warning message when trying to change source or destination attribute for items which are marked as hidden or disabled dependency for another form item.
* Display an error in dialog when trying to delete an item which is marked as hidden or disabled dependency for another form item (it used to throw an uncatched exception).

feat(admin): check disabled and hidden dependencies for application items

---

apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.html
apps/admin-gui/src/app/shared/side-menu/side-menu-item/side-menu-item.component.ts
apps/user-profile/src/app/components/side-menu/side-menu.component.html
apps/user-profile/src/app/pages/authentication-page/authentication-overview/authentication-overview.component.html
apps/user-profile/src/app/pages/authentication-page/authentication-overview/authentication-overview.component.scss
apps/user-profile/src/app/pages/settings-page/settings-overview/settings-overview.component.html
apps/user-profile/src/app/pages/settings-page/settings-overview/settings-overview.component.scss
libs/perun/directives/src/lib/middle-click-router-link.ts

* On a ctrl (command) + left mouse click is now opened the application in the new tab and routing is stopped in the parent tab.
* This is now implemented also for side menu, tables and inner page menu in user-profile (authentication and settings).

fix: open application in the new tab

---

apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
apps/admin-gui/src/app/vos/pages/vo-detail-page/vo-overview/vo-overview.component.html
libs/perun/models/src/lib/ExpandabelTiles.ts
libs/perun/services/src/lib/expanded-tiles-store.service.ts
libs/perun/utils/src/lib/perun-utils.ts

* Expandable tiles functionality added 'resources' as a new key to localStorage, but this key had been already used by recently visited functionality.
* This caused that if expandable functionality change the value in localStorage to 'true', the resource list will be broken due to recently visited functionality.
* Key for expandable tiles in localStorage is changed to 'resourcesExpandable'.

fix(admin): key 'resources' duplicated in localStorage

---

apps/user-profile/src/app/pages/identities-page/identities-page.component.ts
apps/user-profile/src/assets/config/defaultConfig.json
libs/perun/models/src/lib/ConfigProperties.ts

* Changed the consolidator_base_url property to consolidator_url, which now includes the full url, thus no fed/cert rerouting is done in code.
BREAKING CHANGE: The consolidator_base_url config property needs to be changed to consolidator_url and include the complete url.

feat(profile): consolidator config uses full url

---

libs/perun/services/src/lib/ApiInterceptor.ts
libs/perun/services/src/lib/auth.service.ts

The reauthentication of user in multiple tabs works fine. However the session expired dialog stayed present aand prevented usage of the app. This is no longer the case

feat: close session expired dialog in all tabs

---

apps/user-profile/src/app/pages/identities-page/identities-page.component.html
apps/user-profile/src/app/pages/identities-page/identities-page.component.ts
apps/user-profile/src/assets/config/defaultConfig.json
libs/perun/models/src/lib/ConfigProperties.ts

DEPLOYMENT NOTE: Added new config option "consolidator_url_cert" in order to support different URLs for consolidator with federated and certificate authentication.

fix(profile): support adding both fed and cert identity types

---

apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.html
apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts
apps/admin-gui/src/app/shared/components/users-list/users-list.component.html
apps/admin-gui/src/app/shared/components/users-list/users-list.component.scss
apps/admin-gui/src/app/shared/components/users-list/users-list.component.ts
apps/admin-gui/src/assets/i18n/en.json

* Under the group on the managers page there is now available to optionally display also indirect managers of this group.

feat(admin): display also indirect managers

---

apps/admin-gui-e2e/src/e2e/facilities/facility-admin.cy.js
apps/admin-gui-e2e/src/e2e/groups/group-admin.cy.js
apps/admin-gui-e2e/src/e2e/vos/vo-admin.cy.js

* Previously changed table header is now higher than before which (in my opinion) cause that some buttons are now out of visible screen for cypress - the click event must be forced for these buttons.

test(admin): fix failing tests

---

apps/admin-gui/src/app/admin/admin-routing.module.ts
apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.html
apps/admin-gui/src/app/shared/components/two-entity-attribute-page/two-entity-attribute-page.component.ts
apps/admin-gui/src/app/shared/side-menu/side-menu-item.service.ts
apps/admin-gui/src/app/users/pages/user-detail-page/user-accounts/user-accounts.component.html
apps/admin-gui/src/app/users/pages/user-detail-page/user-assignments/user-assignments.component.html
apps/admin-gui/src/app/users/pages/user-detail-page/user-assignments/user-assignments.component.scss
apps/admin-gui/src/app/users/pages/user-detail-page/user-assignments/user-assignments.component.ts
apps/admin-gui/src/app/users/pages/user-detail-page/user-overview/user-overview.component.ts
apps/admin-gui/src/app/users/users.module.ts
apps/admin-gui/src/assets/i18n/en.json
libs/perun/openapi/src/lib/api/usersManager.service.ts

* 'Organizations' and 'Groups' pages were removed from the admin version of the 'User' section since information from both of these pages is contained in 'Accounts'
* 'Resources' and 'Facilities' pages were merged into new 'Assignments' page that works similarly to 'Accounts'
* Updated two entity attribute component to allow fixed second entity and did some necessary tweaks to allow displaying Member-Resource attributes per resource in fixed facility
* Fixed a bug where the initial selected object didn't match the displayed attributes on two-entity attributes page
* Aligned loading spinner on 'Accounts' page
* Updated openapi
DEPLOYMENT NOTE: Removed 'Organizations', 'Groups', 'Resources' and 'Facilities' pages from the admin version of the User section. Refer admins to 'Accounts' page …

feat(admin): update User section Perun Admin menu

---

libs/perun/login/src/lib/login-screen-service-access/login-screen-service-access.component.ts

While using service access, the logout alert is hidden after a page refresh.

fix(lib): hide logout alert

---

apps/admin-gui/src/app/vos/pages/member-detail-page/member-applications/member-applications.component.html

* Due to recent move of this component from admin-gui folder to the lib folder was changed the prefix of the component, but it was not changed on member-applications page.

fix(admin): use renamed html tag for application dynamic list

---

apps/admin-gui/src/app/users/pages/user-detail-page/user-dashboard/dashboard-recently-viewed-button-field/dashboard-recently-viewed-button-field.component.ts
libs/perun/utils/src/lib/perun-utils.ts

* There was just a technical problem of matching type RichGroup/Group after some recent changes of loading groups.
* This matching was fixed on the dashboard and also in the related service.

fix(admin): display groups on recently viewed dashboard

---

apps/admin-gui/src/app/shared/components/dialogs/add-group-manager-dialog/add-group-manager-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/add-manager-dialog/add-manager-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/add-role-dialog/add-role-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/remove-group-manager-dialog/remove-group-manager-dialog.component.ts
apps/admin-gui/src/app/shared/components/dialogs/remove-manager-dialog/remove-manager-dialog.component.ts
apps/admin-gui/src/app/shared/components/managers-page/managers-page.component.ts
libs/perun/openapi/src/lib/api/authzResolver.service.ts
libs/perun/openapi/src/lib/model/setRoleWithGroupComplementaryObject.ts
libs/perun/openapi/src/lib/model/setRoleWithGroupComplementaryObjects.ts
libs/perun/openapi/src/lib/model/setRoleWithUserComplementaryObject.ts
libs/perun/openapi/src/lib/model/setRoleWithUserComplementaryObjects.ts
libs/perun/openapi/src/lib/model/unsetRoleWithGroupComplementaryObject.ts
libs/perun/openapi/src/lib/model/unsetRoleWithGroupComplementaryObjects.ts
libs/perun/openapi/src/lib/model/unsetRoleWithUserComplementaryObject.ts
libs/perun/openapi/src/lib/model/unsetRoleWithUserComplementaryObjects.ts

* Regenerate openapi with new comments about supported objects for complementaryObjet(s) parameter.
* Unify a type of complementaryObject variable to PerunBean object across classes in admin-gui.
* The information about supported objects has been left just in openapi documentation to avoid future need of changing it on several places.
* Little refactor of edited files has been done.

refactor(admin): unify complementaryObject parameter

---

apps/admin-gui/src/_styles.scss
apps/admin-gui/src/app/core/services/common/admin-gui-config.service.ts

* Fix a misspelling in cssVariable name for side_submenu_active_text_color variable.

fix(admin): edit variable for sidemenu submenu active text color
